// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_Advanced_AwaTypeNone represents the None enum in the Destiny.Advanced.AwaType component.
    Destiny_Advanced_AwaTypeNone int32 = 0

    // Destiny_Advanced_AwaTypeInsertPlugs represents the InsertPlugs enum in the Destiny.Advanced.AwaType component.
    //
    // Insert plugs into sockets.
    Destiny_Advanced_AwaTypeInsertPlugs int32 = 1
)
