// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Content_Models_ContentTypeDefaultValue struct {
    // WhenClause.
    //
    // 
    WhenClause string `json:"whenClause"`

    // WhenValue.
    //
    // 
    WhenValue string `json:"whenValue"`

    // DefaultValue.
    //
    // 
    DefaultValue string `json:"defaultValue"`
}
