// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type User_EmailOptInDefinition struct {
    // DependentSubscriptions.
    //
    // Information about the dependent subscriptions for this opt-in.
    DependentSubscriptions []User_EmailSubscriptionDefinition `json:"dependentSubscriptions"`

    // Name.
    //
    // The unique identifier for this opt-in category.
    Name string `json:"name"`

    // SetByDefault.
    //
    // If true, this opt-in setting should be set by default in situations where accounts are created without explicit choices about what they're opting into.
    SetByDefault bool `json:"setByDefault"`

    // Value.
    //
    // The flag value for this opt-in category. For historical reasons, this is defined as a flags enum.
    Value int64 `json:"value"`
}
