// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_Sockets_DestinyPlugSetDefinition struct {
    // DisplayProperties.
    //
    // If you want to show these plugs in isolation, these are the display properties for them.
    DisplayProperties any `json:"displayProperties"`

    // Hash.
    //
    // The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.
    //
    // When entities refer to each other in Destiny content, it is this hash that they are referring to.
    Hash uint32 `json:"hash"`

    // Index.
    //
    // The index of the entity as it was found in the investment tables.
    Index int32 `json:"index"`

    // IsFakePlugSet.
    //
    // Mostly for our debugging or reporting bugs, BNet is making "fake" plug sets in a desperate effort to reduce socket sizes.
    //
    //  If this is true, the plug set was generated by BNet: if it looks wrong, that's a good indicator that it's bungie.net that fucked this up.
    IsFakePlugSet bool `json:"isFakePlugSet"`

    // Redacted.
    //
    // If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry!
    Redacted bool `json:"redacted"`

    // ReusablePlugItems.
    //
    // This is a list of pre-determined plugs that can be plugged into this socket, without the character having the plug in their inventory.
    //
    // If this list is populated, you will not be allowed to plug an arbitrary item in the socket: you will only be able to choose from one of these reusable plugs.
    ReusablePlugItems []Destiny_Definitions_DestinyItemSocketEntryPlugItemRandomizedDefinition `json:"reusablePlugItems"`
}
