// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_Advanced_AwaResponseReasonNone represents the None enum in the Destiny.Advanced.AwaResponseReason component.
    Destiny_Advanced_AwaResponseReasonNone int32 = 0

    // Destiny_Advanced_AwaResponseReasonAnswered represents the Answered enum in the Destiny.Advanced.AwaResponseReason component.
    //
    // User provided an answer
    Destiny_Advanced_AwaResponseReasonAnswered int32 = 1

    // Destiny_Advanced_AwaResponseReasonTimedOut represents the TimedOut enum in the Destiny.Advanced.AwaResponseReason component.
    //
    // The HTTP request timed out, a new request may be made and an answer may still be provided.
    Destiny_Advanced_AwaResponseReasonTimedOut int32 = 2

    // Destiny_Advanced_AwaResponseReasonReplaced represents the Replaced enum in the Destiny.Advanced.AwaResponseReason component.
    //
    // This request was replaced by another request.
    Destiny_Advanced_AwaResponseReasonReplaced int32 = 3
)
