// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_FireteamFinderCodeOptionTypeNone represents the None enum in the Destiny.FireteamFinderCodeOptionType component.
    Destiny_FireteamFinderCodeOptionTypeNone int32 = 0

    // Destiny_FireteamFinderCodeOptionTypeApplicationOnly represents the ApplicationOnly enum in the Destiny.FireteamFinderCodeOptionType component.
    Destiny_FireteamFinderCodeOptionTypeApplicationOnly int32 = 1

    // Destiny_FireteamFinderCodeOptionTypeOnlineOnly represents the OnlineOnly enum in the Destiny.FireteamFinderCodeOptionType component.
    Destiny_FireteamFinderCodeOptionTypeOnlineOnly int32 = 2

    // Destiny_FireteamFinderCodeOptionTypePlayerCount represents the PlayerCount enum in the Destiny.FireteamFinderCodeOptionType component.
    Destiny_FireteamFinderCodeOptionTypePlayerCount int32 = 3

    // Destiny_FireteamFinderCodeOptionTypeTitle represents the Title enum in the Destiny.FireteamFinderCodeOptionType component.
    Destiny_FireteamFinderCodeOptionTypeTitle int32 = 4

    // Destiny_FireteamFinderCodeOptionTypeTags represents the Tags enum in the Destiny.FireteamFinderCodeOptionType component.
    Destiny_FireteamFinderCodeOptionTypeTags int32 = 5

    // Destiny_FireteamFinderCodeOptionTypeFinderActivityGraph represents the FinderActivityGraph enum in the Destiny.FireteamFinderCodeOptionType component.
    Destiny_FireteamFinderCodeOptionTypeFinderActivityGraph int32 = 6

    // Destiny_FireteamFinderCodeOptionTypeMicrophoneRequired represents the MicrophoneRequired enum in the Destiny.FireteamFinderCodeOptionType component.
    Destiny_FireteamFinderCodeOptionTypeMicrophoneRequired int32 = 7
)
