// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Applications_ApplicationStatusNone represents the None enum in the Applications.ApplicationStatus component.
    //
    // No value assigned
    Applications_ApplicationStatusNone int32 = 0

    // Applications_ApplicationStatusPrivate represents the Private enum in the Applications.ApplicationStatus component.
    //
    // Application exists and works but will not appear in any public catalog. New applications start in this state, test applications will remain in this state.
    Applications_ApplicationStatusPrivate int32 = 1

    // Applications_ApplicationStatusPublic represents the Public enum in the Applications.ApplicationStatus component.
    //
    // Active applications that can appear in an catalog.
    Applications_ApplicationStatusPublic int32 = 2

    // Applications_ApplicationStatusDisabled represents the Disabled enum in the Applications.ApplicationStatus component.
    //
    // Application disabled by the owner. All authorizations will be treated as terminated while in this state. Owner can move back to private or public state.
    Applications_ApplicationStatusDisabled int32 = 3

    // Applications_ApplicationStatusBlocked represents the Blocked enum in the Applications.ApplicationStatus component.
    //
    // Application has been blocked by Bungie. It cannot be transitioned out of this state by the owner. Authorizations are terminated when an application is in this state.
    Applications_ApplicationStatusBlocked int32 = 4
)
