// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_DestinyBreakerTypeNone represents the None enum in the Destiny.DestinyBreakerType component.
    Destiny_DestinyBreakerTypeNone int32 = 0

    // Destiny_DestinyBreakerTypeShieldPiercing represents the ShieldPiercing enum in the Destiny.DestinyBreakerType component.
    Destiny_DestinyBreakerTypeShieldPiercing int32 = 1

    // Destiny_DestinyBreakerTypeDisruption represents the Disruption enum in the Destiny.DestinyBreakerType component.
    Destiny_DestinyBreakerTypeDisruption int32 = 2

    // Destiny_DestinyBreakerTypeStagger represents the Stagger enum in the Destiny.DestinyBreakerType component.
    Destiny_DestinyBreakerTypeStagger int32 = 3
)
