// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Components_ComponentPrivacySettingNone represents the None enum in the Components.ComponentPrivacySetting component.
    Components_ComponentPrivacySettingNone int32 = 0

    // Components_ComponentPrivacySettingPublic represents the Public enum in the Components.ComponentPrivacySetting component.
    Components_ComponentPrivacySettingPublic int32 = 1

    // Components_ComponentPrivacySettingPrivate represents the Private enum in the Components.ComponentPrivacySetting component.
    Components_ComponentPrivacySettingPrivate int32 = 2
)
