// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // FireteamFinder_DestinyFireteamFinderListingFilterRangeTypeUnknown represents the Unknown enum in the FireteamFinder.DestinyFireteamFinderListingFilterRangeType component.
    FireteamFinder_DestinyFireteamFinderListingFilterRangeTypeUnknown  = 0

    // FireteamFinder_DestinyFireteamFinderListingFilterRangeTypeAll represents the All enum in the FireteamFinder.DestinyFireteamFinderListingFilterRangeType component.
    FireteamFinder_DestinyFireteamFinderListingFilterRangeTypeAll  = 1

    // FireteamFinder_DestinyFireteamFinderListingFilterRangeTypeAny represents the Any enum in the FireteamFinder.DestinyFireteamFinderListingFilterRangeType component.
    FireteamFinder_DestinyFireteamFinderListingFilterRangeTypeAny  = 2

    // FireteamFinder_DestinyFireteamFinderListingFilterRangeTypeInRangeInclusive represents the InRangeInclusive enum in the FireteamFinder.DestinyFireteamFinderListingFilterRangeType component.
    FireteamFinder_DestinyFireteamFinderListingFilterRangeTypeInRangeInclusive  = 3

    // FireteamFinder_DestinyFireteamFinderListingFilterRangeTypeInRangeExclusive represents the InRangeExclusive enum in the FireteamFinder.DestinyFireteamFinderListingFilterRangeType component.
    FireteamFinder_DestinyFireteamFinderListingFilterRangeTypeInRangeExclusive  = 4

    // FireteamFinder_DestinyFireteamFinderListingFilterRangeTypeGreaterThan represents the GreaterThan enum in the FireteamFinder.DestinyFireteamFinderListingFilterRangeType component.
    FireteamFinder_DestinyFireteamFinderListingFilterRangeTypeGreaterThan  = 5

    // FireteamFinder_DestinyFireteamFinderListingFilterRangeTypeGreaterThanOrEqualTo represents the GreaterThanOrEqualTo enum in the FireteamFinder.DestinyFireteamFinderListingFilterRangeType component.
    FireteamFinder_DestinyFireteamFinderListingFilterRangeTypeGreaterThanOrEqualTo  = 6

    // FireteamFinder_DestinyFireteamFinderListingFilterRangeTypeLessThan represents the LessThan enum in the FireteamFinder.DestinyFireteamFinderListingFilterRangeType component.
    FireteamFinder_DestinyFireteamFinderListingFilterRangeTypeLessThan  = 7

    // FireteamFinder_DestinyFireteamFinderListingFilterRangeTypeLessThanOrEqualTo represents the LessThanOrEqualTo enum in the FireteamFinder.DestinyFireteamFinderListingFilterRangeType component.
    FireteamFinder_DestinyFireteamFinderListingFilterRangeTypeLessThanOrEqualTo  = 8
)
