// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type FireteamFinder_DestinyFireteamFinderSearchListingsByClanRequest struct {
    // LobbyState.
    //
    // 
    LobbyState int32 `json:"lobbyState"`

    // PageSize.
    //
    // 
    PageSize int32 `json:"pageSize"`

    // PageToken.
    //
    // 
    PageToken string `json:"pageToken"`
}
