// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // GroupsV2_GroupMemberCountFilterAll represents the All enum in the GroupsV2.GroupMemberCountFilter component.
    GroupsV2_GroupMemberCountFilterAll int32 = 0

    // GroupsV2_GroupMemberCountFilterOneToTen represents the OneToTen enum in the GroupsV2.GroupMemberCountFilter component.
    GroupsV2_GroupMemberCountFilterOneToTen int32 = 1

    // GroupsV2_GroupMemberCountFilterElevenToOneHundred represents the ElevenToOneHundred enum in the GroupsV2.GroupMemberCountFilter component.
    GroupsV2_GroupMemberCountFilterElevenToOneHundred int32 = 2

    // GroupsV2_GroupMemberCountFilterGreaterThanOneHundred represents the GreaterThanOneHundred enum in the GroupsV2.GroupMemberCountFilter component.
    GroupsV2_GroupMemberCountFilterGreaterThanOneHundred int32 = 3
)
