// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type FireteamFinder_DestinyFireteamFinderKickPlayerRequest struct {
    // TargetMembershipType.
    //
    // 
    TargetMembershipType int32 `json:"targetMembershipType"`

    // TargetCharacterId.
    //
    // 
    TargetCharacterId int64 `json:"targetCharacterId"`
}
