// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type FireteamFinder_DestinyFireteamFinderJoinLobbyRequest struct {
    // LobbyId.
    //
    // 
    LobbyId int64 `json:"lobbyId"`

    // OfferId.
    //
    // 
    OfferId int64 `json:"offerId"`
}
