// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Components_Metrics_DestinyMetricComponent struct {
    // Invisible.
    //
    // 
    Invisible bool `json:"invisible"`

    // ObjectiveProgress.
    //
    // Returns data about a character's status with a given Objective. Combine with DestinyObjectiveDefinition static data for display purposes.
    ObjectiveProgress any `json:"objectiveProgress"`
}
