// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // GroupsV2_ChatSecuritySettingGroup represents the Group enum in the GroupsV2.ChatSecuritySetting component.
    GroupsV2_ChatSecuritySettingGroup int32 = 0

    // GroupsV2_ChatSecuritySettingAdmins represents the Admins enum in the GroupsV2.ChatSecuritySetting component.
    GroupsV2_ChatSecuritySettingAdmins int32 = 1
)
