// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Requests_Actions_DestinyPostmasterTransferRequest struct {
    // CharacterId.
    //
    // 
    CharacterId int64 `json:"characterId"`

    // ItemId.
    //
    // The instance ID of the item for this action request.
    ItemId int64 `json:"itemId"`

    // ItemReferenceHash.
    //
    // 
    ItemReferenceHash uint32 `json:"itemReferenceHash"`

    // MembershipType.
    //
    // 
    MembershipType int32 `json:"membershipType"`

    // StackSize.
    //
    // 
    StackSize int32 `json:"stackSize"`
}
