// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // FireteamFinder_DestinyFireteamFinderLobbyStateUnknown represents the Unknown enum in the FireteamFinder.DestinyFireteamFinderLobbyState component.
    FireteamFinder_DestinyFireteamFinderLobbyStateUnknown int32 = 0

    // FireteamFinder_DestinyFireteamFinderLobbyStateInactive represents the Inactive enum in the FireteamFinder.DestinyFireteamFinderLobbyState component.
    FireteamFinder_DestinyFireteamFinderLobbyStateInactive int32 = 1

    // FireteamFinder_DestinyFireteamFinderLobbyStateActive represents the Active enum in the FireteamFinder.DestinyFireteamFinderLobbyState component.
    FireteamFinder_DestinyFireteamFinderLobbyStateActive int32 = 2

    // FireteamFinder_DestinyFireteamFinderLobbyStateExpired represents the Expired enum in the FireteamFinder.DestinyFireteamFinderLobbyState component.
    FireteamFinder_DestinyFireteamFinderLobbyStateExpired int32 = 3

    // FireteamFinder_DestinyFireteamFinderLobbyStateClosed represents the Closed enum in the FireteamFinder.DestinyFireteamFinderLobbyState component.
    FireteamFinder_DestinyFireteamFinderLobbyStateClosed int32 = 4

    // FireteamFinder_DestinyFireteamFinderLobbyStateCanceled represents the Canceled enum in the FireteamFinder.DestinyFireteamFinderLobbyState component.
    FireteamFinder_DestinyFireteamFinderLobbyStateCanceled int32 = 5

    // FireteamFinder_DestinyFireteamFinderLobbyStateDeleted represents the Deleted enum in the FireteamFinder.DestinyFireteamFinderLobbyState component.
    FireteamFinder_DestinyFireteamFinderLobbyStateDeleted int32 = 6
)
