// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_Common_DestinyPositionDefinition struct {
    // Z.
    //
    // 
    Z int32 `json:"z"`

    // X.
    //
    // 
    X int32 `json:"x"`

    // Y.
    //
    // 
    Y int32 `json:"y"`
}
