// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_SpecialItemTypeNone represents the None enum in the Destiny.SpecialItemType component.
    Destiny_SpecialItemTypeNone int32 = 0

    // Destiny_SpecialItemTypeSpecialCurrency represents the SpecialCurrency enum in the Destiny.SpecialItemType component.
    Destiny_SpecialItemTypeSpecialCurrency int32 = 1

    // Destiny_SpecialItemTypeArmor represents the Armor enum in the Destiny.SpecialItemType component.
    Destiny_SpecialItemTypeArmor int32 = 8

    // Destiny_SpecialItemTypeWeapon represents the Weapon enum in the Destiny.SpecialItemType component.
    Destiny_SpecialItemTypeWeapon int32 = 9

    // Destiny_SpecialItemTypeEngram represents the Engram enum in the Destiny.SpecialItemType component.
    Destiny_SpecialItemTypeEngram int32 = 23

    // Destiny_SpecialItemTypeConsumable represents the Consumable enum in the Destiny.SpecialItemType component.
    Destiny_SpecialItemTypeConsumable int32 = 24

    // Destiny_SpecialItemTypeExchangeMaterial represents the ExchangeMaterial enum in the Destiny.SpecialItemType component.
    Destiny_SpecialItemTypeExchangeMaterial int32 = 25

    // Destiny_SpecialItemTypeMissionReward represents the MissionReward enum in the Destiny.SpecialItemType component.
    Destiny_SpecialItemTypeMissionReward int32 = 27

    // Destiny_SpecialItemTypeCurrency represents the Currency enum in the Destiny.SpecialItemType component.
    Destiny_SpecialItemTypeCurrency int32 = 29
)
