// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_Presentation_DestinyPresentationNodeCraftableChildEntry struct {
    // NodeDisplayPriority.
    //
    // Use this value to sort the presentation node children in ascending order.
    NodeDisplayPriority uint32 `json:"nodeDisplayPriority"`

    // CraftableItemHash.
    //
    // 
    CraftableItemHash uint32 `json:"craftableItemHash"`
}
