// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type FireteamFinder_DestinyFireteamFinderPlayerId struct {
    // MembershipId.
    //
    // 
    MembershipId int64 `json:"membershipId"`

    // MembershipType.
    //
    // 
    MembershipType int32 `json:"membershipType"`

    // CharacterId.
    //
    // 
    CharacterId int64 `json:"characterId"`
}
