// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type FireteamFinder_DestinyFireteamFinderRespondToOfferResponse struct {
    // OfferId.
    //
    // 
    OfferId int64 `json:"offerId"`

    // Revision.
    //
    // 
    Revision int32 `json:"revision"`

    // State.
    //
    // 
    State int32 `json:"state"`
}
