// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type GroupsV2_GroupV2ClanInfo struct {
    // ClanCallsign.
    //
    // 
    ClanCallsign string `json:"clanCallsign"`

    // ClanBannerData.
    //
    // 
    ClanBannerData any `json:"clanBannerData"`
}
