// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Components_Social_DestinySocialCommendationsComponent struct {
    // CommendationNodePercentagesByHash.
    //
    // The percentage for each commendation type out of total received
    CommendationNodePercentagesByHash map[uint32]uint32 `json:"commendationNodePercentagesByHash"`

    // CommendationNodeScoresByHash.
    //
    // 
    CommendationNodeScoresByHash map[uint32]int32 `json:"commendationNodeScoresByHash"`

    // CommendationScoresByHash.
    //
    // 
    CommendationScoresByHash map[uint32]int32 `json:"commendationScoresByHash"`

    // ScoreDetailValues.
    //
    // 
    ScoreDetailValues []int32 `json:"scoreDetailValues"`

    // TotalScore.
    //
    // 
    TotalScore int32 `json:"totalScore"`
}
