// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_DestinyTalentNodeCategory struct {
    // IsLoreDriven.
    //
    // If true, we found the localized content in a related DestinyLoreDefinition instead of local BNet localization files. This is mostly for ease of my own future investigations.
    IsLoreDriven bool `json:"isLoreDriven"`

    // NodeHashes.
    //
    // The set of all hash identifiers for Talent Nodes (DestinyTalentNodeDefinition) in this Talent Grid that are part of this Category.
    NodeHashes []uint32 `json:"nodeHashes"`

    // DisplayProperties.
    //
    // Will contain at least the "name", which will be the title of the category. We will likely not have description and an icon yet, but I'm going to keep my options open.
    DisplayProperties any `json:"displayProperties"`

    // Identifier.
    //
    // Mostly just for debug purposes, but if you find it useful you can have it. This is BNet's manually created identifier for this category.
    Identifier string `json:"identifier"`
}
