// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Advanced_AwaUserResponse struct {
    // Nonce.
    //
    // Secret nonce received via the PUSH notification.
    Nonce []byte `json:"nonce"`

    // Selection.
    //
    // Indication of the selection the user has made (Approving or rejecting the action)
    Selection int32 `json:"selection"`

    // CorrelationId.
    //
    // Correlation ID of the request
    CorrelationId string `json:"correlationId"`
}
