// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_BucketScopeCharacter represents the Character enum in the Destiny.BucketScope component.
    Destiny_BucketScopeCharacter int32 = 0

    // Destiny_BucketScopeAccount represents the Account enum in the Destiny.BucketScope component.
    Destiny_BucketScopeAccount int32 = 1
)
