// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Requests_Actions_DestinyInsertPlugsFreeActionRequest struct {
    // MembershipType.
    //
    // 
    MembershipType int32 `json:"membershipType"`

    // Plug.
    //
    // The plugs being inserted.
    Plug any `json:"plug"`

    // CharacterId.
    //
    // 
    CharacterId int64 `json:"characterId"`

    // ItemId.
    //
    // The instance ID of the item for this action request.
    ItemId int64 `json:"itemId"`
}
