// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_DestinyProgressionDefinition struct {
    // Redacted.
    //
    // If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry!
    Redacted bool `json:"redacted"`

    // Hash.
    //
    // The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.
    //
    // When entities refer to each other in Destiny content, it is this hash that they are referring to.
    Hash uint32 `json:"hash"`

    // RankIcon.
    //
    // For progressions that have it, this is the rank icon we use in the Companion, displayed above the progressions' rank value.
    RankIcon string `json:"rankIcon"`

    // RepeatLastStep.
    //
    // If this is True, then the progression doesn't have a maximum level.
    RepeatLastStep bool `json:"repeatLastStep"`

    // Color.
    //
    // The #RGB string value for the color related to this progression, if there is one.
    Color any `json:"color"`

    // FactionHash.
    //
    // If the value exists, this is the hash identifier for the Faction that owns this Progression.
    //
    // This is purely for convenience, if you're looking at a progression and want to know if and who it's related to in terms of Faction Reputation.
    FactionHash uint32 `json:"factionHash"`

    // RewardItems.
    //
    // 
    RewardItems []Destiny_Definitions_DestinyProgressionRewardItemQuantity `json:"rewardItems"`

    // Scope.
    //
    // The "Scope" of the progression indicates the source of the progression's live data.
    //
    // See the DestinyProgressionScope enum for more info: but essentially, a Progression can either be backed by a stored value, or it can be a calculated derivative of other values.
    Scope int32 `json:"scope"`

    // Source.
    //
    // If there's a description of how to earn this progression in the local config, this will be that localized description.
    Source string `json:"source"`

    // Steps.
    //
    // Progressions are divided into Steps, which roughly equate to "Levels" in the traditional sense of a Progression. Notably, the last step can be repeated indefinitely if repeatLastStep is true, meaning that the calculation for your level is not as simple as comparing your current progress to the max progress of the steps. 
    //
    // These and more calculations are done for you if you grab live character progression data, such as in the DestinyCharacterProgressionComponent.
    Steps []Destiny_Definitions_DestinyProgressionStepDefinition `json:"steps"`

    // Visible.
    //
    // If true, the Progression is something worth showing to users.
    //
    // If false, BNet isn't going to show it. But that doesn't mean you can't. We're all friends here.
    Visible bool `json:"visible"`

    // DisplayProperties.
    //
    // 
    DisplayProperties Destiny_Definitions_DestinyProgressionDisplayPropertiesDefinition `json:"displayProperties"`

    // Index.
    //
    // The index of the entity as it was found in the investment tables.
    Index int32 `json:"index"`
}
