// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type DictionaryComponentResponseOfint64AndDestinyCharacterProgressionComponent struct {
    // Data.
    //
    // 
    Data map[int64]Destiny_Entities_Characters_DestinyCharacterProgressionComponent `json:"data"`

    // Disabled.
    //
    // If true, this component is disabled.
    Disabled *bool `json:"disabled"`

    // Privacy.
    //
    // 
    Privacy int32 `json:"privacy"`
}
