// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type DestinyItemComponentSetOfint64 struct {
    // Perks.
    //
    // 
    Perks DictionaryComponentResponseOfint64AndDestinyItemPerksComponent `json:"perks"`

    // RenderData.
    //
    // 
    RenderData DictionaryComponentResponseOfint64AndDestinyItemRenderComponent `json:"renderData"`

    // Sockets.
    //
    // 
    Sockets DictionaryComponentResponseOfint64AndDestinyItemSocketsComponent `json:"sockets"`

    // Instances.
    //
    // 
    Instances DictionaryComponentResponseOfint64AndDestinyItemInstanceComponent `json:"instances"`

    // Objectives.
    //
    // 
    Objectives DictionaryComponentResponseOfint64AndDestinyItemObjectivesComponent `json:"objectives"`

    // Stats.
    //
    // 
    Stats DictionaryComponentResponseOfint64AndDestinyItemStatsComponent `json:"stats"`

    // PlugObjectives.
    //
    // 
    PlugObjectives DictionaryComponentResponseOfint64AndDestinyItemPlugObjectivesComponent `json:"plugObjectives"`

    // PlugStates.
    //
    // 
    PlugStates DictionaryComponentResponseOfuint32AndDestinyItemPlugComponent `json:"plugStates"`

    // ReusablePlugs.
    //
    // 
    ReusablePlugs DictionaryComponentResponseOfint64AndDestinyItemReusablePlugsComponent `json:"reusablePlugs"`

    // TalentGrids.
    //
    // 
    TalentGrids DictionaryComponentResponseOfint64AndDestinyItemTalentGridComponent `json:"talentGrids"`
}
