// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_Presentation_DestinyPresentationChildBlock struct {
    // ParentPresentationNodeHashes.
    //
    // 
    ParentPresentationNodeHashes []uint32 `json:"parentPresentationNodeHashes"`

    // PresentationNodeType.
    //
    // 
    PresentationNodeType int32 `json:"presentationNodeType"`

    // DisplayStyle.
    //
    // 
    DisplayStyle int32 `json:"displayStyle"`
}
