// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_Records_DestinyRecordTitleBlock struct {
    // TitlesByGenderHash.
    //
    // For those who prefer to use the definitions.
    TitlesByGenderHash any `json:"titlesByGenderHash"`

    // GildingTrackingRecordHash.
    //
    // 
    GildingTrackingRecordHash uint32 `json:"gildingTrackingRecordHash"`

    // HasTitle.
    //
    // 
    HasTitle bool `json:"hasTitle"`

    // TitlesByGender.
    //
    // 
    TitlesByGender any `json:"titlesByGender"`
}
