// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Components_Presentation_DestinyPresentationNodesComponent struct {
    // Nodes.
    //
    // 
    Nodes map[uint32]Destiny_Components_Presentation_DestinyPresentationNodeComponent `json:"nodes"`
}
