// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Trending_TrendingCategory struct {
    // Entries.
    //
    // 
    Entries any `json:"entries"`

    // CategoryId.
    //
    // 
    CategoryId string `json:"categoryId"`

    // CategoryName.
    //
    // 
    CategoryName string `json:"categoryName"`
}
