// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // FireteamFinder_DestinyFireteamFinderPlayerReadinessStateUnknown represents the Unknown enum in the FireteamFinder.DestinyFireteamFinderPlayerReadinessState component.
    FireteamFinder_DestinyFireteamFinderPlayerReadinessStateUnknown int32 = 0

    // FireteamFinder_DestinyFireteamFinderPlayerReadinessStateReserved represents the Reserved enum in the FireteamFinder.DestinyFireteamFinderPlayerReadinessState component.
    FireteamFinder_DestinyFireteamFinderPlayerReadinessStateReserved int32 = 1

    // FireteamFinder_DestinyFireteamFinderPlayerReadinessStateDisconnected represents the Disconnected enum in the FireteamFinder.DestinyFireteamFinderPlayerReadinessState component.
    FireteamFinder_DestinyFireteamFinderPlayerReadinessStateDisconnected int32 = 2

    // FireteamFinder_DestinyFireteamFinderPlayerReadinessStateInLobbyUnready represents the InLobbyUnready enum in the FireteamFinder.DestinyFireteamFinderPlayerReadinessState component.
    FireteamFinder_DestinyFireteamFinderPlayerReadinessStateInLobbyUnready int32 = 3

    // FireteamFinder_DestinyFireteamFinderPlayerReadinessStateInLobbyReady represents the InLobbyReady enum in the FireteamFinder.DestinyFireteamFinderPlayerReadinessState component.
    FireteamFinder_DestinyFireteamFinderPlayerReadinessStateInLobbyReady int32 = 4

    // FireteamFinder_DestinyFireteamFinderPlayerReadinessStateSummoned represents the Summoned enum in the FireteamFinder.DestinyFireteamFinderPlayerReadinessState component.
    FireteamFinder_DestinyFireteamFinderPlayerReadinessStateSummoned int32 = 5
)
