// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_FireteamFinder_DestinyActivityInteractableReference struct {
    // ActivityInteractableElementIndex.
    //
    // 
    ActivityInteractableElementIndex int32 `json:"activityInteractableElementIndex"`

    // ActivityInteractableHash.
    //
    // 
    ActivityInteractableHash uint32 `json:"activityInteractableHash"`
}
