// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // User_OptInFlagsNone represents the None enum in the User.OptInFlags component.
    User_OptInFlagsNone int64 = 0

    // User_OptInFlagsNewsletter represents the Newsletter enum in the User.OptInFlags component.
    User_OptInFlagsNewsletter int64 = 1

    // User_OptInFlagsSystem represents the System enum in the User.OptInFlags component.
    User_OptInFlagsSystem int64 = 2

    // User_OptInFlagsMarketing represents the Marketing enum in the User.OptInFlags component.
    User_OptInFlagsMarketing int64 = 4

    // User_OptInFlagsUserResearch represents the UserResearch enum in the User.OptInFlags component.
    User_OptInFlagsUserResearch int64 = 8

    // User_OptInFlagsCustomerService represents the CustomerService enum in the User.OptInFlags component.
    User_OptInFlagsCustomerService int64 = 16

    // User_OptInFlagsSocial represents the Social enum in the User.OptInFlags component.
    User_OptInFlagsSocial int64 = 32

    // User_OptInFlagsPlayTests represents the PlayTests enum in the User.OptInFlags component.
    User_OptInFlagsPlayTests int64 = 64

    // User_OptInFlagsPlayTestsLocal represents the PlayTestsLocal enum in the User.OptInFlags component.
    User_OptInFlagsPlayTestsLocal int64 = 128

    // User_OptInFlagsCareers represents the Careers enum in the User.OptInFlags component.
    User_OptInFlagsCareers int64 = 256
)
