// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_ItemBindStatusNotBound represents the NotBound enum in the Destiny.ItemBindStatus component.
    Destiny_ItemBindStatusNotBound int32 = 0

    // Destiny_ItemBindStatusBoundToCharacter represents the BoundToCharacter enum in the Destiny.ItemBindStatus component.
    Destiny_ItemBindStatusBoundToCharacter int32 = 1

    // Destiny_ItemBindStatusBoundToAccount represents the BoundToAccount enum in the Destiny.ItemBindStatus component.
    Destiny_ItemBindStatusBoundToAccount int32 = 2

    // Destiny_ItemBindStatusBoundToGuild represents the BoundToGuild enum in the Destiny.ItemBindStatus component.
    Destiny_ItemBindStatusBoundToGuild int32 = 3
)
