// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_HistoricalStats_DestinyHistoricalStatsWithMerged struct {
    // Merged.
    //
    // 
    Merged Destiny_HistoricalStats_DestinyHistoricalStatsByPeriod `json:"merged"`

    // Results.
    //
    // 
    Results any `json:"results"`
}
