// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_FireteamFinderOptionSearchFilterTypeNone represents the None enum in the Destiny.FireteamFinderOptionSearchFilterType component.
    Destiny_FireteamFinderOptionSearchFilterTypeNone int32 = 0

    // Destiny_FireteamFinderOptionSearchFilterTypeAll represents the All enum in the Destiny.FireteamFinderOptionSearchFilterType component.
    Destiny_FireteamFinderOptionSearchFilterTypeAll int32 = 1

    // Destiny_FireteamFinderOptionSearchFilterTypeAny represents the Any enum in the Destiny.FireteamFinderOptionSearchFilterType component.
    Destiny_FireteamFinderOptionSearchFilterTypeAny int32 = 2

    // Destiny_FireteamFinderOptionSearchFilterTypeInRangeInclusive represents the InRangeInclusive enum in the Destiny.FireteamFinderOptionSearchFilterType component.
    Destiny_FireteamFinderOptionSearchFilterTypeInRangeInclusive int32 = 3

    // Destiny_FireteamFinderOptionSearchFilterTypeInRangeExclusive represents the InRangeExclusive enum in the Destiny.FireteamFinderOptionSearchFilterType component.
    Destiny_FireteamFinderOptionSearchFilterTypeInRangeExclusive int32 = 4

    // Destiny_FireteamFinderOptionSearchFilterTypeGreaterThan represents the GreaterThan enum in the Destiny.FireteamFinderOptionSearchFilterType component.
    Destiny_FireteamFinderOptionSearchFilterTypeGreaterThan int32 = 5

    // Destiny_FireteamFinderOptionSearchFilterTypeGreaterThanOrEqualTo represents the GreaterThanOrEqualTo enum in the Destiny.FireteamFinderOptionSearchFilterType component.
    Destiny_FireteamFinderOptionSearchFilterTypeGreaterThanOrEqualTo int32 = 6

    // Destiny_FireteamFinderOptionSearchFilterTypeLessThan represents the LessThan enum in the Destiny.FireteamFinderOptionSearchFilterType component.
    Destiny_FireteamFinderOptionSearchFilterTypeLessThan int32 = 7

    // Destiny_FireteamFinderOptionSearchFilterTypeLessThanOrEqualTo represents the LessThanOrEqualTo enum in the Destiny.FireteamFinderOptionSearchFilterType component.
    Destiny_FireteamFinderOptionSearchFilterTypeLessThanOrEqualTo int32 = 8
)
