// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_ActivityGraphNodeHighlightTypeNone represents the None enum in the Destiny.ActivityGraphNodeHighlightType component.
    Destiny_ActivityGraphNodeHighlightTypeNone int32 = 0

    // Destiny_ActivityGraphNodeHighlightTypeNormal represents the Normal enum in the Destiny.ActivityGraphNodeHighlightType component.
    Destiny_ActivityGraphNodeHighlightTypeNormal int32 = 1

    // Destiny_ActivityGraphNodeHighlightTypeHyper represents the Hyper enum in the Destiny.ActivityGraphNodeHighlightType component.
    Destiny_ActivityGraphNodeHighlightTypeHyper int32 = 2

    // Destiny_ActivityGraphNodeHighlightTypeComet represents the Comet enum in the Destiny.ActivityGraphNodeHighlightType component.
    Destiny_ActivityGraphNodeHighlightTypeComet int32 = 3

    // Destiny_ActivityGraphNodeHighlightTypeRiseOfIron represents the RiseOfIron enum in the Destiny.ActivityGraphNodeHighlightType component.
    Destiny_ActivityGraphNodeHighlightTypeRiseOfIron int32 = 4
)
