// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_DestinyItemPreviewBlockDefinition struct {
    // ArtifactHash.
    //
    // If this item should show you Artifact information when you preview it, this is the hash identifier of the DestinyArtifactDefinition for the artifact whose data should be shown.
    ArtifactHash *uint32 `json:"artifactHash"`

    // DerivedItemCategories.
    //
    // This is a list of the items being previewed, categorized in the same way as they are in the preview UI.
    DerivedItemCategories []Destiny_Definitions_Items_DestinyDerivedItemCategoryDefinition `json:"derivedItemCategories"`

    // PreviewActionString.
    //
    // If the preview has an associated action (like "Open"), this will be the localized string for that action.
    PreviewActionString string `json:"previewActionString"`

    // PreviewVendorHash.
    //
    // If the preview data is derived from a fake "Preview" Vendor, this will be the hash identifier for the DestinyVendorDefinition of that fake vendor.
    PreviewVendorHash uint32 `json:"previewVendorHash"`

    // ScreenStyle.
    //
    // A string that the game UI uses as a hint for which detail screen to show for the item. You, too, can leverage this for your own custom screen detail views. Note, however, that these are arbitrarily defined by designers: there's no guarantees of a fixed, known number of these - so fall back to something reasonable if you don't recognize it.
    ScreenStyle string `json:"screenStyle"`
}
