// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_Milestones_DestinyMilestoneQuestRewardsDefinition struct {
    // Items.
    //
    // The items that represent your reward for completing the quest.
    //
    // Be warned, these could be "dummy" items: items that are only used to render a good-looking in-game tooltip, but aren't the actual items themselves.
    //
    // For instance, when experience is given there's often a dummy item representing "experience", with quantity being the amount of experience you got. We don't have a programmatic association between those and whatever Progression is actually getting that experience... yet.
    Items []Destiny_Definitions_Milestones_DestinyMilestoneQuestRewardItem `json:"items"`
}
