// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_Definitions_DestinyTalentNodeStepWeaponPerformancesNone represents the None enum in the Destiny.Definitions.DestinyTalentNodeStepWeaponPerformances component.
    Destiny_Definitions_DestinyTalentNodeStepWeaponPerformancesNone int32 = 0

    // Destiny_Definitions_DestinyTalentNodeStepWeaponPerformancesRateOfFire represents the RateOfFire enum in the Destiny.Definitions.DestinyTalentNodeStepWeaponPerformances component.
    Destiny_Definitions_DestinyTalentNodeStepWeaponPerformancesRateOfFire int32 = 1

    // Destiny_Definitions_DestinyTalentNodeStepWeaponPerformancesDamage represents the Damage enum in the Destiny.Definitions.DestinyTalentNodeStepWeaponPerformances component.
    Destiny_Definitions_DestinyTalentNodeStepWeaponPerformancesDamage int32 = 2

    // Destiny_Definitions_DestinyTalentNodeStepWeaponPerformancesAccuracy represents the Accuracy enum in the Destiny.Definitions.DestinyTalentNodeStepWeaponPerformances component.
    Destiny_Definitions_DestinyTalentNodeStepWeaponPerformancesAccuracy int32 = 4

    // Destiny_Definitions_DestinyTalentNodeStepWeaponPerformancesRange represents the Range enum in the Destiny.Definitions.DestinyTalentNodeStepWeaponPerformances component.
    Destiny_Definitions_DestinyTalentNodeStepWeaponPerformancesRange int32 = 8

    // Destiny_Definitions_DestinyTalentNodeStepWeaponPerformancesZoom represents the Zoom enum in the Destiny.Definitions.DestinyTalentNodeStepWeaponPerformances component.
    Destiny_Definitions_DestinyTalentNodeStepWeaponPerformancesZoom int32 = 16

    // Destiny_Definitions_DestinyTalentNodeStepWeaponPerformancesRecoil represents the Recoil enum in the Destiny.Definitions.DestinyTalentNodeStepWeaponPerformances component.
    Destiny_Definitions_DestinyTalentNodeStepWeaponPerformancesRecoil int32 = 32

    // Destiny_Definitions_DestinyTalentNodeStepWeaponPerformancesReady represents the Ready enum in the Destiny.Definitions.DestinyTalentNodeStepWeaponPerformances component.
    Destiny_Definitions_DestinyTalentNodeStepWeaponPerformancesReady int32 = 64

    // Destiny_Definitions_DestinyTalentNodeStepWeaponPerformancesReload represents the Reload enum in the Destiny.Definitions.DestinyTalentNodeStepWeaponPerformances component.
    Destiny_Definitions_DestinyTalentNodeStepWeaponPerformancesReload int32 = 128

    // Destiny_Definitions_DestinyTalentNodeStepWeaponPerformancesHairTrigger represents the HairTrigger enum in the Destiny.Definitions.DestinyTalentNodeStepWeaponPerformances component.
    Destiny_Definitions_DestinyTalentNodeStepWeaponPerformancesHairTrigger int32 = 256

    // Destiny_Definitions_DestinyTalentNodeStepWeaponPerformancesAmmoAndMagazine represents the AmmoAndMagazine enum in the Destiny.Definitions.DestinyTalentNodeStepWeaponPerformances component.
    Destiny_Definitions_DestinyTalentNodeStepWeaponPerformancesAmmoAndMagazine int32 = 512

    // Destiny_Definitions_DestinyTalentNodeStepWeaponPerformancesTrackingAndDetonation represents the TrackingAndDetonation enum in the Destiny.Definitions.DestinyTalentNodeStepWeaponPerformances component.
    Destiny_Definitions_DestinyTalentNodeStepWeaponPerformancesTrackingAndDetonation int32 = 1024

    // Destiny_Definitions_DestinyTalentNodeStepWeaponPerformancesShotgunSpread represents the ShotgunSpread enum in the Destiny.Definitions.DestinyTalentNodeStepWeaponPerformances component.
    Destiny_Definitions_DestinyTalentNodeStepWeaponPerformancesShotgunSpread int32 = 2048

    // Destiny_Definitions_DestinyTalentNodeStepWeaponPerformancesChargeTime represents the ChargeTime enum in the Destiny.Definitions.DestinyTalentNodeStepWeaponPerformances component.
    Destiny_Definitions_DestinyTalentNodeStepWeaponPerformancesChargeTime int32 = 4096

    // Destiny_Definitions_DestinyTalentNodeStepWeaponPerformancesAll represents the All enum in the Destiny.Definitions.DestinyTalentNodeStepWeaponPerformances component.
    Destiny_Definitions_DestinyTalentNodeStepWeaponPerformancesAll int32 = 8191
)
