// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_ItemPerkVisibilityVisible represents the Visible enum in the Destiny.ItemPerkVisibility component.
    Destiny_ItemPerkVisibilityVisible int32 = 0

    // Destiny_ItemPerkVisibilityDisabled represents the Disabled enum in the Destiny.ItemPerkVisibility component.
    Destiny_ItemPerkVisibilityDisabled int32 = 1

    // Destiny_ItemPerkVisibilityHidden represents the Hidden enum in the Destiny.ItemPerkVisibility component.
    Destiny_ItemPerkVisibilityHidden int32 = 2
)
