// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_Items_DestinyItemPlugDefinition struct {
    // AlternatePlugStyle.
    //
    // The alternate plug of the plug: only applies when the item is in states that only the server can know about and control, unfortunately. See AlternateUiPlugLabel for the related label info.
    AlternatePlugStyle int32 `json:"alternatePlugStyle"`

    // AlternateUiPlugLabel.
    //
    // If the plug meets certain state requirements, it may have an alternative label applied to it. This is the alternative label that will be applied in such a situation.
    AlternateUiPlugLabel string `json:"alternateUiPlugLabel"`

    // EnabledMaterialRequirementHash.
    //
    // It's not enough for the plug to be inserted. It has to be enabled as well. For it to be enabled, it may require materials. This is the hash identifier for the DestinyMaterialRequirementSetDefinition for those requirements, if there is one.
    EnabledMaterialRequirementHash uint32 `json:"enabledMaterialRequirementHash"`

    // EnabledRules.
    //
    // The rules around whether the plug, once inserted, is enabled and providing its benefits.
    //
    // The live data DestinyItemPlugComponent.enableFailIndexes will be an index into this array, so you can pull out the failure strings appropriate for the user.
    EnabledRules []Destiny_Definitions_Items_DestinyPlugRuleDefinition `json:"enabledRules"`

    // EnergyCapacity.
    //
    // IF not null, this plug provides Energy capacity to the item in which it is socketed. In Armor 2.0 for example, is implemented in a similar way to Masterworks, where visually it's a single area of the UI being clicked on to "Upgrade" to higher energy levels, but it's actually socketing new plugs.
    EnergyCapacity any `json:"energyCapacity"`

    // EnergyCost.
    //
    // IF not null, this plug has an energy cost. This contains the details of that cost.
    EnergyCost any `json:"energyCost"`

    // InsertionMaterialRequirementHash.
    //
    // If inserting this plug requires materials, this is the hash identifier for looking up the DestinyMaterialRequirementSetDefinition for those requirements.
    InsertionMaterialRequirementHash uint32 `json:"insertionMaterialRequirementHash"`

    // InsertionRules.
    //
    // The rules around when this plug can be inserted into a socket, aside from the socket's individual restrictions.
    //
    // The live data DestinyItemPlugComponent.insertFailIndexes will be an index into this array, so you can pull out the failure strings appropriate for the user.
    InsertionRules []Destiny_Definitions_Items_DestinyPlugRuleDefinition `json:"insertionRules"`

    // IsDummyPlug.
    //
    // If TRUE, this plug is used for UI display purposes only, and doesn't have any interesting effects of its own.
    IsDummyPlug bool `json:"isDummyPlug"`

    // OnActionRecreateSelf.
    //
    // If you successfully socket the item, this will determine whether or not you get "refunded" on the plug.
    OnActionRecreateSelf bool `json:"onActionRecreateSelf"`

    // ParentItemOverride.
    //
    // Do you ever get the feeling that a system has become so overburdened by edge cases that it probably should have become some other system entirely? So do I!
    //
    // In totally unrelated news, Plugs can now override properties of their parent items. This is some of the relevant definition data for those overrides.
    //
    // If this is populated, it will have the override data to be applied when this plug is applied to an item.
    ParentItemOverride any `json:"parentItemOverride"`

    // PlugAvailability.
    //
    // Indicates the rules about when this plug can be used. See the PlugAvailabilityMode enumeration for more information!
    PlugAvailability int32 `json:"plugAvailability"`

    // PlugCategoryHash.
    //
    // The hash for the plugCategoryIdentifier. You can use this instead if you wish: I put both in the definition for debugging purposes.
    PlugCategoryHash uint32 `json:"plugCategoryHash"`

    // PlugCategoryIdentifier.
    //
    // The string identifier for the plug's category. Use the socket's DestinySocketTypeDefinition.plugWhitelist to determine whether this plug can be inserted into the socket.
    PlugCategoryIdentifier string `json:"plugCategoryIdentifier"`

    // PlugStyle.
    //
    // 
    PlugStyle int32 `json:"plugStyle"`

    // PreviewItemOverrideHash.
    //
    // In the game, if you're inspecting a plug item directly, this will be the item shown with the plug attached. Look up the DestinyInventoryItemDefinition for this hash for the item.
    PreviewItemOverrideHash uint32 `json:"previewItemOverrideHash"`

    // UiPlugLabel.
    //
    // Plugs can have arbitrary, UI-defined identifiers that the UI designers use to determine the style applied to plugs. Unfortunately, we have neither a definitive list of these labels nor advance warning of when new labels might be applied or how that relates to how they get rendered. If you want to, you can refer to known labels to change your own styles: but know that new ones can be created arbitrarily, and we have no way of associating the labels with any specific UI style guidance... you'll have to piece that together on your end. Or do what we do, and just show plugs more generically, without specialized styles.
    UiPlugLabel string `json:"uiPlugLabel"`
}
