// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Tokens_TwitchDropHistoryResponse struct {
    // ClaimState.
    //
    // 
    ClaimState *byte `json:"ClaimState"`

    // CreatedAt.
    //
    // 
    CreatedAt *string `json:"CreatedAt"`

    // Description.
    //
    // 
    Description string `json:"Description"`

    // Title.
    //
    // 
    Title string `json:"Title"`
}
