// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_DestinyLocationReleaseDefinition struct {
    // ActivityHash.
    //
    // The Activity being pointed to by this location.
    ActivityHash uint32 `json:"activityHash"`

    // DestinationHash.
    //
    // The Destination being pointed to by this location.
    DestinationHash uint32 `json:"destinationHash"`

    // SpawnPoint.
    //
    // If we had map information, this spawnPoint would be interesting. But sadly, we don't have that info.
    SpawnPoint uint32 `json:"spawnPoint"`

    // ActivityPathDestination.
    //
    // If we had map information, this would tell us about path information related to destination on the map. Sad. Maybe you can do something cool with it. Go to town man.
    ActivityPathDestination uint32 `json:"activityPathDestination"`

    // MapIcon.
    //
    // 
    MapIcon string `json:"mapIcon"`

    // SmallTransparentIcon.
    //
    // 
    SmallTransparentIcon string `json:"smallTransparentIcon"`

    // ActivityGraphHash.
    //
    // The Activity Graph being pointed to by this location.
    ActivityGraphHash uint32 `json:"activityGraphHash"`

    // ActivityGraphNodeHash.
    //
    // The Activity Graph Node being pointed to by this location. (Remember that Activity Graph Node hashes are only unique within an Activity Graph: so use the combination to find the node being spoken of)
    ActivityGraphNodeHash uint32 `json:"activityGraphNodeHash"`

    // LargeTransparentIcon.
    //
    // 
    LargeTransparentIcon string `json:"largeTransparentIcon"`

    // NavPointType.
    //
    // The type of Nav Point that this represents. See the enumeration for more info.
    NavPointType int32 `json:"navPointType"`

    // ActivityPathBundle.
    //
    // If we had map information, this would tell us something cool about the path this location wants you to take. I wish we had map information.
    ActivityPathBundle uint32 `json:"activityPathBundle"`

    // DisplayProperties.
    //
    // Sadly, these don't appear to be populated anymore (ever?)
    DisplayProperties any `json:"displayProperties"`

    // WorldPosition.
    //
    // Looks like it should be the position on the map, but sadly it does not look populated... yet?
    WorldPosition []any `json:"worldPosition"`

    // ActivityBubbleName.
    //
    // The Activity Bubble within the Destination. Look this up in the DestinyDestinationDefinition's bubbles and bubbleSettings properties.
    ActivityBubbleName uint32 `json:"activityBubbleName"`
}
