// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Config_ClanBanner_ClanBannerDecal struct {
    // ForegroundPath.
    //
    // 
    ForegroundPath string `json:"foregroundPath"`

    // Identifier.
    //
    // 
    Identifier string `json:"identifier"`

    // BackgroundPath.
    //
    // 
    BackgroundPath string `json:"backgroundPath"`
}
