// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_Seasons_DestinySeasonDefinition struct {
    // Acts.
    //
    // A list of Acts for the Episode
    Acts []Destiny_Definitions_Seasons_DestinySeasonActDefinition `json:"acts"`

    // ArtifactItemHash.
    //
    // 
    ArtifactItemHash *uint32 `json:"artifactItemHash"`

    // BackgroundImagePath.
    //
    // 
    BackgroundImagePath string `json:"backgroundImagePath"`

    // DisplayProperties.
    //
    // Many Destiny*Definition contracts - the "first order" entities of Destiny that have their own tables in the Manifest Database - also have displayable information. This is the base class for that display information.
    DisplayProperties Destiny_Definitions_Common_DestinyDisplayPropertiesDefinition `json:"displayProperties"`

    // EndDate.
    //
    // 
    EndDate *string `json:"endDate"`

    // Hash.
    //
    // The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.
    //
    // When entities refer to each other in Destiny content, it is this hash that they are referring to.
    Hash uint32 `json:"hash"`

    // Index.
    //
    // The index of the entity as it was found in the investment tables.
    Index int32 `json:"index"`

    // Preview.
    //
    // Optional - Defines the promotional text, images, and links to preview this season.
    Preview any `json:"preview"`

    // Redacted.
    //
    // If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry!
    Redacted bool `json:"redacted"`

    // SealPresentationNodeHash.
    //
    // 
    SealPresentationNodeHash *uint32 `json:"sealPresentationNodeHash"`

    // SeasonNumber.
    //
    // 
    SeasonNumber int32 `json:"seasonNumber"`

    // SeasonPassHash.
    //
    // 
    SeasonPassHash *uint32 `json:"seasonPassHash"`

    // SeasonPassProgressionHash.
    //
    // 
    SeasonPassProgressionHash *uint32 `json:"seasonPassProgressionHash"`

    // SeasonalChallengesPresentationNodeHash.
    //
    // 
    SeasonalChallengesPresentationNodeHash *uint32 `json:"seasonalChallengesPresentationNodeHash"`

    // StartDate.
    //
    // 
    StartDate *string `json:"startDate"`
}
