// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_HistoricalStats_DestinyHistoricalStatsAccountResult struct {
    // Characters.
    //
    // 
    Characters []Destiny_HistoricalStats_DestinyHistoricalStatsPerCharacter `json:"characters"`

    // MergedAllCharacters.
    //
    // 
    MergedAllCharacters any `json:"mergedAllCharacters"`

    // MergedDeletedCharacters.
    //
    // 
    MergedDeletedCharacters any `json:"mergedDeletedCharacters"`
}
