// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // GroupsV2_GroupHomepageWall represents the Wall enum in the GroupsV2.GroupHomepage component.
    GroupsV2_GroupHomepageWall int32 = 0

    // GroupsV2_GroupHomepageForum represents the Forum enum in the GroupsV2.GroupHomepage component.
    GroupsV2_GroupHomepageForum int32 = 1

    // GroupsV2_GroupHomepageAllianceForum represents the AllianceForum enum in the GroupsV2.GroupHomepage component.
    GroupsV2_GroupHomepageAllianceForum int32 = 2
)
