// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type FireteamFinder_DestinyFireteamFinderGetPlayerOffersResponse struct {
    // Offers.
    //
    // All offers that this player has recieved.
    Offers []FireteamFinder_DestinyFireteamFinderOffer `json:"offers"`
}
