// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Responses_PersonalDestinyVendorSaleItemSetComponent struct {
    // SaleItems.
    //
    // 
    SaleItems map[int32]Destiny_Entities_Vendors_DestinyVendorSaleItemComponent `json:"saleItems"`
}
