// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_TierTypeUnknown represents the Unknown enum in the Destiny.TierType component.
    Destiny_TierTypeUnknown int32 = 0

    // Destiny_TierTypeCurrency represents the Currency enum in the Destiny.TierType component.
    Destiny_TierTypeCurrency int32 = 1

    // Destiny_TierTypeBasic represents the Basic enum in the Destiny.TierType component.
    Destiny_TierTypeBasic int32 = 2

    // Destiny_TierTypeCommon represents the Common enum in the Destiny.TierType component.
    Destiny_TierTypeCommon int32 = 3

    // Destiny_TierTypeRare represents the Rare enum in the Destiny.TierType component.
    Destiny_TierTypeRare int32 = 4

    // Destiny_TierTypeSuperior represents the Superior enum in the Destiny.TierType component.
    Destiny_TierTypeSuperior int32 = 5

    // Destiny_TierTypeExotic represents the Exotic enum in the Destiny.TierType component.
    Destiny_TierTypeExotic int32 = 6
)
