// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Content_ContentRepresentation struct {
    // Name.
    //
    // 
    Name string `json:"name"`

    // Path.
    //
    // 
    Path string `json:"path"`

    // ValidationString.
    //
    // 
    ValidationString string `json:"validationString"`
}
