// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_HistoricalStats_DestinyActivityHistoryResults struct {
    // Activities.
    //
    // List of activities, the most recent activity first.
    Activities []Destiny_HistoricalStats_DestinyHistoricalStatsPeriodGroup `json:"activities"`
}
