// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type GroupsV2_GroupV2ClanInfoAndInvestment struct {
    // ClanBannerData.
    //
    // 
    ClanBannerData GroupsV2_ClanBanner `json:"clanBannerData"`

    // ClanCallsign.
    //
    // 
    ClanCallsign string `json:"clanCallsign"`

    // D2ClanProgressions.
    //
    // 
    D2ClanProgressions map[uint32]Destiny_DestinyProgression `json:"d2ClanProgressions"`
}
