// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type GlobalAlert struct {
    // AlertHtml.
    //
    // 
    AlertHtml string `json:"AlertHtml"`

    // AlertKey.
    //
    // 
    AlertKey string `json:"AlertKey"`

    // AlertLevel.
    //
    // 
    AlertLevel int32 `json:"AlertLevel"`

    // AlertLink.
    //
    // 
    AlertLink string `json:"AlertLink"`

    // AlertTimestamp.
    //
    // 
    AlertTimestamp string `json:"AlertTimestamp"`

    // AlertType.
    //
    // 
    AlertType int32 `json:"AlertType"`

    // StreamInfo.
    //
    // 
    StreamInfo StreamInfo `json:"StreamInfo"`
}
