// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_FireteamFinder_DestinyFireteamFinderOptionSearcherSettings struct {
    // Control.
    //
    // 
    Control any `json:"control"`

    // SearchFilterType.
    //
    // 
    SearchFilterType int32 `json:"searchFilterType"`
}
