// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Social_Friends_PlatformFriend struct {
    // BungieGlobalDisplayName.
    //
    // 
    BungieGlobalDisplayName string `json:"bungieGlobalDisplayName"`

    // BungieGlobalDisplayNameCode.
    //
    // 
    BungieGlobalDisplayNameCode int16 `json:"bungieGlobalDisplayNameCode"`

    // BungieNetMembershipId.
    //
    // 
    BungieNetMembershipId int64 `json:"bungieNetMembershipId"`

    // DestinyMembershipId.
    //
    // 
    DestinyMembershipId int64 `json:"destinyMembershipId"`

    // DestinyMembershipType.
    //
    // 
    DestinyMembershipType int32 `json:"destinyMembershipType"`

    // FriendPlatform.
    //
    // 
    FriendPlatform int32 `json:"friendPlatform"`

    // PlatformDisplayName.
    //
    // 
    PlatformDisplayName string `json:"platformDisplayName"`
}
