// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_HistoricalStats_DestinyLeaderboard struct {
    // Entries.
    //
    // 
    Entries []Destiny_HistoricalStats_DestinyLeaderboardEntry `json:"entries"`

    // StatId.
    //
    // 
    StatId string `json:"statId"`
}
