// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_DestinyProgressionSocketPlugOverride struct {
    // OverrideSingleItemHash.
    //
    // 
    OverrideSingleItemHash uint32 `json:"overrideSingleItemHash"`

    // SocketTypeHash.
    //
    // 
    SocketTypeHash uint32 `json:"socketTypeHash"`
}
