// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Applications_ApplicationScopesReadBasicUserProfile represents the ReadBasicUserProfile enum in the Applications.ApplicationScopes component.
    //
    // Read basic user profile information such as the user's handle, avatar icon, etc.
    Applications_ApplicationScopesReadBasicUserProfile int64 = 1

    // Applications_ApplicationScopesReadGroups represents the ReadGroups enum in the Applications.ApplicationScopes component.
    //
    // Read Group/Clan Forums, Wall, and Members for groups and clans that the user has joined.
    Applications_ApplicationScopesReadGroups int64 = 2

    // Applications_ApplicationScopesWriteGroups represents the WriteGroups enum in the Applications.ApplicationScopes component.
    //
    // Write Group/Clan Forums, Wall, and Members for groups and clans that the user has joined.
    Applications_ApplicationScopesWriteGroups int64 = 4

    // Applications_ApplicationScopesAdminGroups represents the AdminGroups enum in the Applications.ApplicationScopes component.
    //
    // Administer Group/Clan Forums, Wall, and Members for groups and clans that the user is a founder or an administrator.
    Applications_ApplicationScopesAdminGroups int64 = 8

    // Applications_ApplicationScopesBnetWrite represents the BnetWrite enum in the Applications.ApplicationScopes component.
    //
    // Create new groups, clans, and forum posts, along with other actions that are reserved for Bungie.net elevated scope: not meant to be used by third party applications.
    Applications_ApplicationScopesBnetWrite int64 = 16

    // Applications_ApplicationScopesMoveEquipDestinyItems represents the MoveEquipDestinyItems enum in the Applications.ApplicationScopes component.
    //
    // Move or equip Destiny items
    Applications_ApplicationScopesMoveEquipDestinyItems int64 = 32

    // Applications_ApplicationScopesReadDestinyInventoryAndVault represents the ReadDestinyInventoryAndVault enum in the Applications.ApplicationScopes component.
    //
    // Read Destiny 1 Inventory and Vault contents. For Destiny 2, this scope is needed to read anything regarded as private. This is the only scope a Destiny 2 app needs for read operations against Destiny 2 data such as inventory, vault, currency, vendors, milestones, progression, etc.
    Applications_ApplicationScopesReadDestinyInventoryAndVault int64 = 64

    // Applications_ApplicationScopesReadUserData represents the ReadUserData enum in the Applications.ApplicationScopes component.
    //
    // Read user data such as who they are web notifications, clan/group memberships, recent activity, muted users.
    Applications_ApplicationScopesReadUserData int64 = 128

    // Applications_ApplicationScopesEditUserData represents the EditUserData enum in the Applications.ApplicationScopes component.
    //
    // Edit user data such as preferred language, status, motto, avatar selection and theme.
    Applications_ApplicationScopesEditUserData int64 = 256

    // Applications_ApplicationScopesReadDestinyVendorsAndAdvisors represents the ReadDestinyVendorsAndAdvisors enum in the Applications.ApplicationScopes component.
    //
    // Access vendor and advisor data specific to a user. OBSOLETE. This scope is only used on the Destiny 1 API.
    Applications_ApplicationScopesReadDestinyVendorsAndAdvisors int64 = 512

    // Applications_ApplicationScopesReadAndApplyTokens represents the ReadAndApplyTokens enum in the Applications.ApplicationScopes component.
    //
    // Read offer history and claim and apply tokens for the user.
    Applications_ApplicationScopesReadAndApplyTokens int64 = 1024

    // Applications_ApplicationScopesAdvancedWriteActions represents the AdvancedWriteActions enum in the Applications.ApplicationScopes component.
    //
    // Can perform actions that will result in a prompt to the user via the Destiny app.
    Applications_ApplicationScopesAdvancedWriteActions int64 = 2048

    // Applications_ApplicationScopesPartnerOfferGrant represents the PartnerOfferGrant enum in the Applications.ApplicationScopes component.
    //
    // Can use the partner offer api to claim rewards defined for a partner
    Applications_ApplicationScopesPartnerOfferGrant int64 = 4096

    // Applications_ApplicationScopesDestinyUnlockValueQuery represents the DestinyUnlockValueQuery enum in the Applications.ApplicationScopes component.
    //
    // Allows an app to query sensitive information like unlock flags and values not available through normal methods.
    Applications_ApplicationScopesDestinyUnlockValueQuery int64 = 8192

    // Applications_ApplicationScopesUserPiiRead represents the UserPiiRead enum in the Applications.ApplicationScopes component.
    //
    // Allows an app to query sensitive user PII, most notably email information.
    Applications_ApplicationScopesUserPiiRead int64 = 16384
)
