// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_Milestones_DestinyMilestoneChallengeActivityGraphNodeEntry struct {
    // ActivityGraphNodeHash.
    //
    // 
    ActivityGraphNodeHash uint32 `json:"activityGraphNodeHash"`

    // ActivityGraphHash.
    //
    // 
    ActivityGraphHash uint32 `json:"activityGraphHash"`
}
