// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Entities_Vendors_DestinyVendorCategory struct {
    // DisplayCategoryIndex.
    //
    // An index into the DestinyVendorDefinition.displayCategories property, so you can grab the display data for this category.
    DisplayCategoryIndex int32 `json:"displayCategoryIndex"`

    // ItemIndexes.
    //
    // An ordered list of indexes into items being sold in this category (DestinyVendorDefinition.itemList) which will contain more information about the items being sold themselves. Can also be used to index into DestinyVendorSaleItemComponent data, if you asked for that data to be returned.
    ItemIndexes []any `json:"itemIndexes"`
}
