// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_DestinyJoinClosedReasonsNone represents the None enum in the Destiny.DestinyJoinClosedReasons component.
    Destiny_DestinyJoinClosedReasonsNone int32 = 0

    // Destiny_DestinyJoinClosedReasonsInMatchmaking represents the InMatchmaking enum in the Destiny.DestinyJoinClosedReasons component.
    //
    // The user is currently in matchmaking.
    Destiny_DestinyJoinClosedReasonsInMatchmaking int32 = 1

    // Destiny_DestinyJoinClosedReasonsLoading represents the Loading enum in the Destiny.DestinyJoinClosedReasons component.
    //
    // The user is currently in a loading screen.
    Destiny_DestinyJoinClosedReasonsLoading int32 = 2

    // Destiny_DestinyJoinClosedReasonsSoloMode represents the SoloMode enum in the Destiny.DestinyJoinClosedReasons component.
    //
    // The user is in an activity that requires solo play.
    Destiny_DestinyJoinClosedReasonsSoloMode int32 = 4

    // Destiny_DestinyJoinClosedReasonsInternalReasons represents the InternalReasons enum in the Destiny.DestinyJoinClosedReasons component.
    //
    // The user can't be joined for one of a variety of internal reasons. Basically, the game can't let you join at this time, but for reasons that aren't under the control of this user.
    Destiny_DestinyJoinClosedReasonsInternalReasons int32 = 8

    // Destiny_DestinyJoinClosedReasonsDisallowedByGameState represents the DisallowedByGameState enum in the Destiny.DestinyJoinClosedReasons component.
    //
    // The user's current activity/quest/other transitory game state is preventing joining.
    Destiny_DestinyJoinClosedReasonsDisallowedByGameState int32 = 16

    // Destiny_DestinyJoinClosedReasonsOffline represents the Offline enum in the Destiny.DestinyJoinClosedReasons component.
    //
    // The user appears to be offline.
    Destiny_DestinyJoinClosedReasonsOffline int32 = 32768
)
