// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Components_StringVariables_DestinyStringVariablesComponent struct {
    // IntegerValuesByHash.
    //
    // 
    IntegerValuesByHash any `json:"integerValuesByHash"`
}
