// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Interpolation_InterpolationPoint struct {
    // Value.
    //
    // 
    Value int32 `json:"value"`

    // Weight.
    //
    // 
    Weight int32 `json:"weight"`
}
