// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type SingleComponentResponseOfDestinySocialCommendationsComponent struct {
    // Data.
    //
    // 
    Data Destiny_Components_Social_DestinySocialCommendationsComponent `json:"data"`

    // Disabled.
    //
    // If true, this component is disabled.
    Disabled bool `json:"disabled"`

    // Privacy.
    //
    // 
    Privacy int32 `json:"privacy"`
}
