// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Components_Inventory_DestinyMaterialRequirementState struct {
    // Count.
    //
    // The amount of the material required.
    Count int32 `json:"count"`

    // ItemHash.
    //
    // The hash identifier of the material required. Use it to look up the material's DestinyInventoryItemDefinition.
    ItemHash uint32 `json:"itemHash"`

    // StackSize.
    //
    // A value for the amount of a (possibly virtual) material on some scope. For example: Dawning cookie baking material requirements.
    StackSize int32 `json:"stackSize"`
}
