// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type SingleComponentResponseOfDestinyCharacterActivitiesComponent struct {
    // Disabled.
    //
    // If true, this component is disabled.
    Disabled bool `json:"disabled"`

    // Privacy.
    //
    // 
    Privacy int32 `json:"privacy"`

    // Data.
    //
    // This component holds activity data for a character. It will tell you about the character's current activity status, as well as activities that are available to the user.
    Data Destiny_Entities_Characters_DestinyCharacterActivitiesComponent `json:"data"`
}
