// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type GroupsV2_GroupApplicationListRequest struct {
    // Memberships.
    //
    // 
    Memberships []User_UserMembership `json:"memberships"`

    // Message.
    //
    // 
    Message string `json:"message"`
}
