// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Tokens_PartnerOfferClaimRequest struct {
    // BungieNetMembershipId.
    //
    // 
    BungieNetMembershipId int64 `json:"BungieNetMembershipId"`

    // PartnerOfferId.
    //
    // 
    PartnerOfferId string `json:"PartnerOfferId"`

    // TransactionId.
    //
    // 
    TransactionId string `json:"TransactionId"`
}
