// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_DestinyProgressionStepDisplayEffectNone represents the None enum in the Destiny.DestinyProgressionStepDisplayEffect component.
    Destiny_DestinyProgressionStepDisplayEffectNone int32 = 0

    // Destiny_DestinyProgressionStepDisplayEffectCharacter represents the Character enum in the Destiny.DestinyProgressionStepDisplayEffect component.
    Destiny_DestinyProgressionStepDisplayEffectCharacter int32 = 1

    // Destiny_DestinyProgressionStepDisplayEffectItem represents the Item enum in the Destiny.DestinyProgressionStepDisplayEffect component.
    Destiny_DestinyProgressionStepDisplayEffectItem int32 = 2
)
