// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Reporting_Requests_DestinyReportOffensePgcrRequest struct {
    // OffendingCharacterId.
    //
    // Within the PGCR provided when calling the Reporting endpoint, this should be the character ID of the user that you thought was violating terms of use. They must exist in the PGCR provided.
    OffendingCharacterId int64 `json:"offendingCharacterId"`

    // ReasonCategoryHashes.
    //
    // So you've decided to report someone instead of cursing them and their descendants. Well, okay then. This is the category or categorie(s) of infractions for which you are reporting the user. These are hash identifiers that map to DestinyReportReasonCategoryDefinition entries.
    ReasonCategoryHashes []uint32 `json:"reasonCategoryHashes"`

    // ReasonHashes.
    //
    // If applicable, provide a more specific reason(s) within the general category of problems provided by the reasonHash. This is also an identifier for a reason. All reasonHashes provided must be children of at least one the reasonCategoryHashes provided.
    ReasonHashes []uint32 `json:"reasonHashes"`
}
