// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type FireteamFinder_DestinyFireteamFinderUpdateLobbySettingsResponse struct {
    // UpdatedListing.
    //
    // 
    UpdatedListing any `json:"updatedListing"`

    // UpdatedLobby.
    //
    // 
    UpdatedLobby any `json:"updatedLobby"`
}
