// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_DestinyProgressionScopeAccount represents the Account enum in the Destiny.DestinyProgressionScope component.
    Destiny_DestinyProgressionScopeAccount int32 = 0

    // Destiny_DestinyProgressionScopeCharacter represents the Character enum in the Destiny.DestinyProgressionScope component.
    Destiny_DestinyProgressionScopeCharacter int32 = 1

    // Destiny_DestinyProgressionScopeClan represents the Clan enum in the Destiny.DestinyProgressionScope component.
    Destiny_DestinyProgressionScopeClan int32 = 2

    // Destiny_DestinyProgressionScopeItem represents the Item enum in the Destiny.DestinyProgressionScope component.
    Destiny_DestinyProgressionScopeItem int32 = 3

    // Destiny_DestinyProgressionScopeImplicitFromEquipment represents the ImplicitFromEquipment enum in the Destiny.DestinyProgressionScope component.
    Destiny_DestinyProgressionScopeImplicitFromEquipment int32 = 4

    // Destiny_DestinyProgressionScopeMapped represents the Mapped enum in the Destiny.DestinyProgressionScope component.
    Destiny_DestinyProgressionScopeMapped int32 = 5

    // Destiny_DestinyProgressionScopeMappedAggregate represents the MappedAggregate enum in the Destiny.DestinyProgressionScope component.
    Destiny_DestinyProgressionScopeMappedAggregate int32 = 6

    // Destiny_DestinyProgressionScopeMappedStat represents the MappedStat enum in the Destiny.DestinyProgressionScope component.
    Destiny_DestinyProgressionScopeMappedStat int32 = 7

    // Destiny_DestinyProgressionScopeMappedUnlockValue represents the MappedUnlockValue enum in the Destiny.DestinyProgressionScope component.
    Destiny_DestinyProgressionScopeMappedUnlockValue int32 = 8
)
