// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Trending_TrendingEntryCommunityCreation struct {
    // Author.
    //
    // 
    Author string `json:"author"`

    // AuthorMembershipId.
    //
    // 
    AuthorMembershipId int64 `json:"authorMembershipId"`

    // Body.
    //
    // 
    Body string `json:"body"`

    // Media.
    //
    // 
    Media string `json:"media"`

    // PostId.
    //
    // 
    PostId int64 `json:"postId"`

    // Title.
    //
    // 
    Title string `json:"title"`

    // Upvotes.
    //
    // 
    Upvotes int32 `json:"upvotes"`
}
