// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_Director_DestinyLinkedGraphEntryDefinition struct {
    // ActivityGraphHash.
    //
    // 
    ActivityGraphHash uint32 `json:"activityGraphHash"`
}
