// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Tags_Models_Contracts_TagResponse struct {
    // IgnoreStatus.
    //
    // 
    IgnoreStatus Ignores_IgnoreResponse `json:"ignoreStatus"`

    // TagText.
    //
    // 
    TagText string `json:"tagText"`
}
