// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_DestinyActivityUnlockStringDefinition struct {
    // DisplayString.
    //
    // The string to be displayed if the conditions are met.
    DisplayString string `json:"displayString"`
}
