// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Fireteam_FireteamPublicSearchOptionPublicAndPrivate represents the PublicAndPrivate enum in the Fireteam.FireteamPublicSearchOption component.
    Fireteam_FireteamPublicSearchOptionPublicAndPrivate byte = 0

    // Fireteam_FireteamPublicSearchOptionPublicOnly represents the PublicOnly enum in the Fireteam.FireteamPublicSearchOption component.
    Fireteam_FireteamPublicSearchOptionPublicOnly byte = 1

    // Fireteam_FireteamPublicSearchOptionPrivateOnly represents the PrivateOnly enum in the Fireteam.FireteamPublicSearchOption component.
    Fireteam_FireteamPublicSearchOptionPrivateOnly byte = 2
)
