// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_DestinyVendorItemStateNone represents the None enum in the Destiny.DestinyVendorItemState component.
    //
    // There are no augments on the item.
    Destiny_DestinyVendorItemStateNone int32 = 0

    // Destiny_DestinyVendorItemStateIncomplete represents the Incomplete enum in the Destiny.DestinyVendorItemState component.
    //
    // Deprecated forever (probably). There was a time when Records were going to be implemented through Vendors, and this field was relevant. Now they're implemented through Presentation Nodes, and this field doesn't matter anymore.
    Destiny_DestinyVendorItemStateIncomplete int32 = 1

    // Destiny_DestinyVendorItemStateRewardAvailable represents the RewardAvailable enum in the Destiny.DestinyVendorItemState component.
    //
    // Deprecated forever (probably). See the description of the "Incomplete" value for the juicy scoop.
    Destiny_DestinyVendorItemStateRewardAvailable int32 = 2

    // Destiny_DestinyVendorItemStateComplete represents the Complete enum in the Destiny.DestinyVendorItemState component.
    //
    // Deprecated forever (probably). See the description of the "Incomplete" value for the juicy scoop.
    Destiny_DestinyVendorItemStateComplete int32 = 4

    // Destiny_DestinyVendorItemStateNew represents the New enum in the Destiny.DestinyVendorItemState component.
    //
    // This item is considered to be "newly available", and should have some UI showing how shiny it is.
    Destiny_DestinyVendorItemStateNew int32 = 8

    // Destiny_DestinyVendorItemStateFeatured represents the Featured enum in the Destiny.DestinyVendorItemState component.
    //
    // This item is being "featured", and should be shiny in a different way from items that are merely new.
    Destiny_DestinyVendorItemStateFeatured int32 = 16

    // Destiny_DestinyVendorItemStateEnding represents the Ending enum in the Destiny.DestinyVendorItemState component.
    //
    // This item is only available for a limited time, and that time is approaching.
    Destiny_DestinyVendorItemStateEnding int32 = 32

    // Destiny_DestinyVendorItemStateOnSale represents the OnSale enum in the Destiny.DestinyVendorItemState component.
    //
    // This item is "on sale". Get it while it's hot.
    Destiny_DestinyVendorItemStateOnSale int32 = 64

    // Destiny_DestinyVendorItemStateOwned represents the Owned enum in the Destiny.DestinyVendorItemState component.
    //
    // This item is already owned.
    Destiny_DestinyVendorItemStateOwned int32 = 128

    // Destiny_DestinyVendorItemStateWideView represents the WideView enum in the Destiny.DestinyVendorItemState component.
    //
    // This item should be shown with a "wide view" instead of normal icon view.
    Destiny_DestinyVendorItemStateWideView int32 = 256

    // Destiny_DestinyVendorItemStateNexusAttention represents the NexusAttention enum in the Destiny.DestinyVendorItemState component.
    //
    // This indicates that you should show some kind of attention-requesting indicator on the item, in a similar manner to items in the nexus that have such notifications.
    Destiny_DestinyVendorItemStateNexusAttention int32 = 512

    // Destiny_DestinyVendorItemStateSetDiscount represents the SetDiscount enum in the Destiny.DestinyVendorItemState component.
    //
    // This indicates that the item has some sort of a 'set' discount.
    Destiny_DestinyVendorItemStateSetDiscount int32 = 1024

    // Destiny_DestinyVendorItemStatePriceDrop represents the PriceDrop enum in the Destiny.DestinyVendorItemState component.
    //
    // This indicates that the item has a price drop.
    Destiny_DestinyVendorItemStatePriceDrop int32 = 2048

    // Destiny_DestinyVendorItemStateDailyOffer represents the DailyOffer enum in the Destiny.DestinyVendorItemState component.
    //
    // This indicates that the item is a daily offer.
    Destiny_DestinyVendorItemStateDailyOffer int32 = 4096

    // Destiny_DestinyVendorItemStateCharity represents the Charity enum in the Destiny.DestinyVendorItemState component.
    //
    // This indicates that the item is for charity.
    Destiny_DestinyVendorItemStateCharity int32 = 8192

    // Destiny_DestinyVendorItemStateSeasonalRewardExpiration represents the SeasonalRewardExpiration enum in the Destiny.DestinyVendorItemState component.
    //
    // This indicates that the item has a seasonal reward expiration.
    Destiny_DestinyVendorItemStateSeasonalRewardExpiration int32 = 16384

    // Destiny_DestinyVendorItemStateBestDeal represents the BestDeal enum in the Destiny.DestinyVendorItemState component.
    //
    // This indicates that the sale item is the best deal among different choices.
    Destiny_DestinyVendorItemStateBestDeal int32 = 32768

    // Destiny_DestinyVendorItemStatePopular represents the Popular enum in the Destiny.DestinyVendorItemState component.
    //
    // This indicates that the sale item is popular.
    Destiny_DestinyVendorItemStatePopular int32 = 65536

    // Destiny_DestinyVendorItemStateFree represents the Free enum in the Destiny.DestinyVendorItemState component.
    //
    // This indicates that the sale item is free.
    Destiny_DestinyVendorItemStateFree int32 = 131072

    // Destiny_DestinyVendorItemStateLocked represents the Locked enum in the Destiny.DestinyVendorItemState component.
    //
    // This indicates that the sale item is locked.
    Destiny_DestinyVendorItemStateLocked int32 = 262144

    // Destiny_DestinyVendorItemStateParacausal represents the Paracausal enum in the Destiny.DestinyVendorItemState component.
    //
    // This indicates that the sale item is paracausal.
    Destiny_DestinyVendorItemStateParacausal int32 = 524288

    // Destiny_DestinyVendorItemStateCryptarch represents the Cryptarch enum in the Destiny.DestinyVendorItemState component.
    Destiny_DestinyVendorItemStateCryptarch int32 = 1048576

    // Destiny_DestinyVendorItemStateArtifactPerkOwned represents the ArtifactPerkOwned enum in the Destiny.DestinyVendorItemState component.
    Destiny_DestinyVendorItemStateArtifactPerkOwned int32 = 2097152

    // Destiny_DestinyVendorItemStateSavings represents the Savings enum in the Destiny.DestinyVendorItemState component.
    Destiny_DestinyVendorItemStateSavings int32 = 4194304

    // Destiny_DestinyVendorItemStateIneligible represents the Ineligible enum in the Destiny.DestinyVendorItemState component.
    Destiny_DestinyVendorItemStateIneligible int32 = 8388608

    // Destiny_DestinyVendorItemStateArtifactPerkBoosted represents the ArtifactPerkBoosted enum in the Destiny.DestinyVendorItemState component.
    Destiny_DestinyVendorItemStateArtifactPerkBoosted int32 = 16777216
)
