// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_Records_DestinyRecordCompletionBlock struct {
    // PartialCompletionObjectiveCountThreshold.
    //
    // The number of objectives that must be completed before the objective is considered "complete"
    PartialCompletionObjectiveCountThreshold int32 `json:"partialCompletionObjectiveCountThreshold"`

    // ScoreValue.
    //
    // 
    ScoreValue int32 `json:"ScoreValue"`

    // ShouldFireToast.
    //
    // 
    ShouldFireToast bool `json:"shouldFireToast"`

    // ToastStyle.
    //
    // 
    ToastStyle int32 `json:"toastStyle"`
}
