// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Social_Friends_PlatformFriendTypeUnknown represents the Unknown enum in the Social.Friends.PlatformFriendType component.
    Social_Friends_PlatformFriendTypeUnknown int32 = 0

    // Social_Friends_PlatformFriendTypeXbox represents the Xbox enum in the Social.Friends.PlatformFriendType component.
    Social_Friends_PlatformFriendTypeXbox int32 = 1

    // Social_Friends_PlatformFriendTypePSN represents the PSN enum in the Social.Friends.PlatformFriendType component.
    Social_Friends_PlatformFriendTypePSN int32 = 2

    // Social_Friends_PlatformFriendTypeSteam represents the Steam enum in the Social.Friends.PlatformFriendType component.
    Social_Friends_PlatformFriendTypeSteam int32 = 3

    // Social_Friends_PlatformFriendTypeEgs represents the Egs enum in the Social.Friends.PlatformFriendType component.
    Social_Friends_PlatformFriendTypeEgs int32 = 4
)
