// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Trending_TrendingCategories struct {
    // Categories.
    //
    // 
    Categories []Trending_TrendingCategory `json:"categories"`
}
