// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_HistoricalStats_DestinyHistoricalStatsPerCharacter struct {
    // CharacterId.
    //
    // 
    CharacterId int64 `json:"characterId"`

    // Deleted.
    //
    // 
    Deleted bool `json:"deleted"`

    // Merged.
    //
    // 
    Merged Destiny_HistoricalStats_DestinyHistoricalStatsByPeriod `json:"merged"`

    // Results.
    //
    // 
    Results any `json:"results"`
}
