// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // GroupsV2_GroupPotentialMemberStatusNone represents the None enum in the GroupsV2.GroupPotentialMemberStatus component.
    GroupsV2_GroupPotentialMemberStatusNone int32 = 0

    // GroupsV2_GroupPotentialMemberStatusApplicant represents the Applicant enum in the GroupsV2.GroupPotentialMemberStatus component.
    GroupsV2_GroupPotentialMemberStatusApplicant int32 = 1

    // GroupsV2_GroupPotentialMemberStatusInvitee represents the Invitee enum in the GroupsV2.GroupPotentialMemberStatus component.
    GroupsV2_GroupPotentialMemberStatusInvitee int32 = 2
)
