// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Common_Models_CoreSystem struct {
    // Enabled.
    //
    // 
    Enabled bool `json:"enabled"`

    // Parameters.
    //
    // 
    Parameters any `json:"parameters"`
}
