// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Fireteam_FireteamResponse struct {
    // Alternates.
    //
    // 
    Alternates []Fireteam_FireteamMember `json:"Alternates"`

    // Members.
    //
    // 
    Members []Fireteam_FireteamMember `json:"Members"`

    // Summary.
    //
    // 
    Summary Fireteam_FireteamSummary `json:"Summary"`
}
