// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Milestones_DestinyMilestoneContentItemCategory struct {
    // Title.
    //
    // 
    Title string `json:"title"`

    // ItemHashes.
    //
    // 
    ItemHashes []uint32 `json:"itemHashes"`
}
