// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_DestinyGenderMale represents the Male enum in the Destiny.DestinyGender component.
    Destiny_DestinyGenderMale int32 = 0

    // Destiny_DestinyGenderFemale represents the Female enum in the Destiny.DestinyGender component.
    Destiny_DestinyGenderFemale int32 = 1

    // Destiny_DestinyGenderUnknown represents the Unknown enum in the Destiny.DestinyGender component.
    Destiny_DestinyGenderUnknown int32 = 2
)
