// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type FireteamFinder_DestinyFireteamFinderLobbyListingReference struct {
    // LobbyId.
    //
    // 
    LobbyId int64 `json:"lobbyId"`

    // ListingId.
    //
    // 
    ListingId int64 `json:"listingId"`
}
