// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Misc_DestinyColor struct {
    // Alpha.
    //
    // 
    Alpha byte `json:"alpha"`

    // Blue.
    //
    // 
    Blue byte `json:"blue"`

    // Green.
    //
    // 
    Green byte `json:"green"`

    // Red.
    //
    // 
    Red byte `json:"red"`
}
