// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_DestinyActivityInsertionPointDefinition struct {
    // PhaseHash.
    //
    // A unique hash value representing the phase. This can be useful for, for example, comparing how different instances of Raids have phases in different orders!
    PhaseHash uint32 `json:"phaseHash"`
}
