// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type FireteamFinder_DestinyFireteamFinderRespondToApplicationRequest struct {
    // Accepted.
    //
    // 
    Accepted bool `json:"accepted"`
}
