// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type FireteamFinder_DestinyFireteamFinderOffer struct {
    // State.
    //
    // 
    State int32 `json:"state"`

    // TargetId.
    //
    // 
    TargetId any `json:"targetId"`

    // ApplicationId.
    //
    // 
    ApplicationId int64 `json:"applicationId"`

    // CreatedDateTime.
    //
    // 
    CreatedDateTime string `json:"createdDateTime"`

    // LobbyId.
    //
    // 
    LobbyId int64 `json:"lobbyId"`

    // OfferId.
    //
    // 
    OfferId int64 `json:"offerId"`

    // Revision.
    //
    // 
    Revision int32 `json:"revision"`
}
