// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Content_NewsArticleRssItem struct {
    // Link.
    //
    // 
    Link string `json:"Link"`

    // OptionalMobileImagePath.
    //
    // 
    OptionalMobileImagePath string `json:"OptionalMobileImagePath"`

    // PubDate.
    //
    // 
    PubDate string `json:"PubDate"`

    // Title.
    //
    // 
    Title string `json:"Title"`

    // UniqueIdentifier.
    //
    // 
    UniqueIdentifier string `json:"UniqueIdentifier"`

    // Description.
    //
    // 
    Description string `json:"Description"`

    // HtmlContent.
    //
    // 
    HtmlContent string `json:"HtmlContent"`

    // ImagePath.
    //
    // 
    ImagePath string `json:"ImagePath"`
}
