// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Entities_Vendors_DestinyVendorCategoriesComponent struct {
    // Categories.
    //
    // The list of categories for items that the vendor sells, in rendering order.
    //
    // These categories each point to a "display category" in the displayCategories property of the DestinyVendorDefinition, as opposed to the other categories.
    Categories []Destiny_Entities_Vendors_DestinyVendorCategory `json:"categories"`
}
