// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Components_Vendors_DestinyVendorGroupComponent struct {
    // Groups.
    //
    // The ordered list of groups being returned.
    Groups []Destiny_Components_Vendors_DestinyVendorGroup `json:"groups"`
}
