// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Components_Craftables_DestinyCraftableSocketComponent struct {
    // PlugSetHash.
    //
    // 
    PlugSetHash uint32 `json:"plugSetHash"`

    // Plugs.
    //
    // Unlock state for plugs in the socket plug set definition
    Plugs []Destiny_Components_Craftables_DestinyCraftableSocketPlugComponent `json:"plugs"`
}
