// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_GuardianRanks_DestinyGuardianRankIconBackgroundsDefinition struct {
    // BackgroundEmptyBlueGradientBorderedImagePath.
    //
    // 
    BackgroundEmptyBlueGradientBorderedImagePath string `json:"backgroundEmptyBlueGradientBorderedImagePath"`

    // BackgroundEmptyBorderedImagePath.
    //
    // 
    BackgroundEmptyBorderedImagePath string `json:"backgroundEmptyBorderedImagePath"`

    // BackgroundFilledBlueBorderedImagePath.
    //
    // 
    BackgroundFilledBlueBorderedImagePath string `json:"backgroundFilledBlueBorderedImagePath"`

    // BackgroundFilledBlueGradientBorderedImagePath.
    //
    // 
    BackgroundFilledBlueGradientBorderedImagePath string `json:"backgroundFilledBlueGradientBorderedImagePath"`

    // BackgroundFilledBlueLowAlphaImagePath.
    //
    // 
    BackgroundFilledBlueLowAlphaImagePath string `json:"backgroundFilledBlueLowAlphaImagePath"`

    // BackgroundFilledBlueMediumAlphaImagePath.
    //
    // 
    BackgroundFilledBlueMediumAlphaImagePath string `json:"backgroundFilledBlueMediumAlphaImagePath"`

    // BackgroundFilledGrayHeavyAlphaBorderedImagePath.
    //
    // 
    BackgroundFilledGrayHeavyAlphaBorderedImagePath string `json:"backgroundFilledGrayHeavyAlphaBorderedImagePath"`

    // BackgroundFilledGrayMediumAlphaBorderedImagePath.
    //
    // 
    BackgroundFilledGrayMediumAlphaBorderedImagePath string `json:"backgroundFilledGrayMediumAlphaBorderedImagePath"`

    // BackgroundFilledWhiteImagePath.
    //
    // 
    BackgroundFilledWhiteImagePath string `json:"backgroundFilledWhiteImagePath"`

    // BackgroundFilledWhiteMediumAlphaImagePath.
    //
    // 
    BackgroundFilledWhiteMediumAlphaImagePath string `json:"backgroundFilledWhiteMediumAlphaImagePath"`

    // BackgroundPlateBlackAlphaImagePath.
    //
    // 
    BackgroundPlateBlackAlphaImagePath string `json:"backgroundPlateBlackAlphaImagePath"`

    // BackgroundPlateBlackImagePath.
    //
    // 
    BackgroundPlateBlackImagePath string `json:"backgroundPlateBlackImagePath"`

    // BackgroundPlateWhiteImagePath.
    //
    // 
    BackgroundPlateWhiteImagePath string `json:"backgroundPlateWhiteImagePath"`
}
