// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_HistoricalStats_DestinyPostGameCarnageReportEntry struct {
    // Score.
    //
    // Score of the player if available
    Score any `json:"score"`

    // Standing.
    //
    // Standing of the player
    Standing int32 `json:"standing"`

    // Values.
    //
    // Collection of stats for the player in this activity.
    Values any `json:"values"`

    // CharacterId.
    //
    // ID of the player's character used in the activity.
    CharacterId int64 `json:"characterId"`

    // Extended.
    //
    // Extended data extracted from the activity blob.
    Extended any `json:"extended"`

    // Player.
    //
    // Identity details of the player
    Player any `json:"player"`
}
