// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Queries_PagedQuery struct {
    // RequestContinuationToken.
    //
    // 
    RequestContinuationToken string `json:"requestContinuationToken"`

    // CurrentPage.
    //
    // 
    CurrentPage int32 `json:"currentPage"`

    // ItemsPerPage.
    //
    // 
    ItemsPerPage int32 `json:"itemsPerPage"`
}
