// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type GroupsV2_GroupV2 struct {
    // IsPublicTopicAdminOnly.
    //
    // 
    IsPublicTopicAdminOnly bool `json:"isPublicTopicAdminOnly"`

    // EnableInvitationMessagingForAdmins.
    //
    // 
    EnableInvitationMessagingForAdmins bool `json:"enableInvitationMessagingForAdmins"`

    // BanExpireDate.
    //
    // 
    BanExpireDate string `json:"banExpireDate"`

    // IsDefaultPostPublic.
    //
    // 
    IsDefaultPostPublic bool `json:"isDefaultPostPublic"`

    // MembershipOption.
    //
    // 
    MembershipOption int32 `json:"membershipOption"`

    // About.
    //
    // 
    About string `json:"about"`

    // Motto.
    //
    // 
    Motto string `json:"motto"`

    // Name.
    //
    // 
    Name string `json:"name"`

    // DefaultPublicity.
    //
    // 
    DefaultPublicity int32 `json:"defaultPublicity"`

    // Homepage.
    //
    // 
    Homepage int32 `json:"homepage"`

    // AllowChat.
    //
    // 
    AllowChat bool `json:"allowChat"`

    // RemoteGroupId.
    //
    // 
    RemoteGroupId int64 `json:"remoteGroupId"`

    // BannerPath.
    //
    // 
    BannerPath string `json:"bannerPath"`

    // MemberCount.
    //
    // 
    MemberCount int32 `json:"memberCount"`

    // ModificationDate.
    //
    // 
    ModificationDate string `json:"modificationDate"`

    // ChatSecurity.
    //
    // 
    ChatSecurity int32 `json:"chatSecurity"`

    // IsPublic.
    //
    // 
    IsPublic bool `json:"isPublic"`

    // MembershipIdCreated.
    //
    // 
    MembershipIdCreated int64 `json:"membershipIdCreated"`

    // Tags.
    //
    // 
    Tags []any `json:"tags"`

    // GroupId.
    //
    // 
    GroupId int64 `json:"groupId"`

    // GroupType.
    //
    // 
    GroupType int32 `json:"groupType"`

    // Locale.
    //
    // 
    Locale string `json:"locale"`

    // Features.
    //
    // 
    Features any `json:"features"`

    // ClanInfo.
    //
    // The same as GroupV2ClanInfo, but includes any investment data.
    ClanInfo any `json:"clanInfo"`

    // ConversationId.
    //
    // 
    ConversationId int64 `json:"conversationId"`

    // AvatarImageIndex.
    //
    // 
    AvatarImageIndex int32 `json:"avatarImageIndex"`

    // CreationDate.
    //
    // 
    CreationDate string `json:"creationDate"`

    // AvatarPath.
    //
    // 
    AvatarPath string `json:"avatarPath"`

    // Theme.
    //
    // 
    Theme string `json:"theme"`
}
