// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type FireteamFinder_DestinyFireteamFinderGetApplicationResponse struct {
    // ApplicationType.
    //
    // 
    ApplicationType int32 `json:"applicationType"`

    // ReferralToken.
    //
    // 
    ReferralToken int64 `json:"referralToken"`

    // Revision.
    //
    // 
    Revision int32 `json:"revision"`

    // CreatedDateTime.
    //
    // 
    CreatedDateTime string `json:"createdDateTime"`

    // ApplicationId.
    //
    // 
    ApplicationId int64 `json:"applicationId"`

    // ListingId.
    //
    // 
    ListingId int64 `json:"listingId"`

    // SubmitterId.
    //
    // 
    SubmitterId FireteamFinder_DestinyFireteamFinderPlayerId `json:"submitterId"`

    // State.
    //
    // 
    State int32 `json:"state"`

    // ApplicantSet.
    //
    // 
    ApplicantSet FireteamFinder_DestinyFireteamFinderApplicantSet `json:"applicantSet"`
}
