// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Trending_TrendingDetail struct {
    // Creation.
    //
    // 
    Creation Trending_TrendingEntryCommunityCreation `json:"creation"`

    // DestinyActivity.
    //
    // 
    DestinyActivity Trending_TrendingEntryDestinyActivity `json:"destinyActivity"`

    // DestinyItem.
    //
    // 
    DestinyItem Trending_TrendingEntryDestinyItem `json:"destinyItem"`

    // DestinyRitual.
    //
    // 
    DestinyRitual Trending_TrendingEntryDestinyRitual `json:"destinyRitual"`

    // EntityType.
    //
    // 
    EntityType int32 `json:"entityType"`

    // Identifier.
    //
    // 
    Identifier string `json:"identifier"`

    // News.
    //
    // 
    News Trending_TrendingEntryNews `json:"news"`

    // Support.
    //
    // 
    Support Trending_TrendingEntrySupportArticle `json:"support"`
}
