// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Forum_PollResult struct {
    // RequestingUserVoted.
    //
    // 
    RequestingUserVoted bool `json:"requestingUserVoted"`

    // Votes.
    //
    // 
    Votes int32 `json:"votes"`

    // AnswerSlot.
    //
    // 
    AnswerSlot int32 `json:"answerSlot"`

    // AnswerText.
    //
    // 
    AnswerText string `json:"answerText"`

    // LastVoteDate.
    //
    // 
    LastVoteDate string `json:"lastVoteDate"`
}
