// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Forum_ForumRecruitmentDetail struct {
    // Tone.
    //
    // 
    Tone byte `json:"tone"`

    // TopicId.
    //
    // 
    TopicId int64 `json:"topicId"`

    // Intensity.
    //
    // 
    Intensity byte `json:"intensity"`

    // MicrophoneRequired.
    //
    // 
    MicrophoneRequired bool `json:"microphoneRequired"`

    // Approved.
    //
    // 
    Approved bool `json:"approved"`

    // KickedPlayerIds.
    //
    // 
    KickedPlayerIds []int64 `json:"kickedPlayerIds"`

    // PlayerSlotsRemaining.
    //
    // 
    PlayerSlotsRemaining int32 `json:"playerSlotsRemaining"`

    // PlayerSlotsTotal.
    //
    // 
    PlayerSlotsTotal int32 `json:"playerSlotsTotal"`

    // Fireteam.
    //
    // 
    Fireteam []User_GeneralUser `json:"Fireteam"`

    // ConversationId.
    //
    // 
    ConversationId int64 `json:"conversationId"`
}
