// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_Records_DestinyRecordDefinition struct {
    // RecordTypeName.
    //
    // A display name for the type of record this is (Triumphs, Lore, Medals, Seasonal Challenge, etc.).
    RecordTypeName string `json:"recordTypeName"`

    // TraitHashes.
    //
    // 
    TraitHashes []any `json:"traitHashes"`

    // ParentNodeHashes.
    //
    // A quick reference to presentation nodes that have this node as a child. Presentation nodes can be parented under multiple parents.
    ParentNodeHashes []any `json:"parentNodeHashes"`

    // IntervalInfo.
    //
    // Some records have multiple 'interval' objectives, and the record may be claimed at each completed interval
    IntervalInfo any `json:"intervalInfo"`

    // Hash.
    //
    // The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.
    //
    // When entities refer to each other in Destiny content, it is this hash that they are referring to.
    Hash uint32 `json:"hash"`

    // RewardItems.
    //
    // If there is any publicly available information about rewards earned for achieving this record, this is the list of those items.
    //
    //  However, note that some records intentionally have "hidden" rewards. These will not be returned in this list.
    RewardItems []Destiny_DestinyItemQuantity `json:"rewardItems"`

    // TraitIds.
    //
    // 
    TraitIds []any `json:"traitIds"`

    // StateInfo.
    //
    // 
    StateInfo any `json:"stateInfo"`

    // CompletionInfo.
    //
    // 
    CompletionInfo any `json:"completionInfo"`

    // PresentationNodeType.
    //
    // 
    PresentationNodeType int32 `json:"presentationNodeType"`

    // Scope.
    //
    // Indicates whether this Record's state is determined on a per-character or on an account-wide basis.
    Scope int32 `json:"scope"`

    // Index.
    //
    // The index of the entity as it was found in the investment tables.
    Index int32 `json:"index"`

    // RecordValueStyle.
    //
    // 
    RecordValueStyle int32 `json:"recordValueStyle"`

    // TitleInfo.
    //
    // 
    TitleInfo any `json:"titleInfo"`

    // ObjectiveHashes.
    //
    // 
    ObjectiveHashes []any `json:"objectiveHashes"`

    // Redacted.
    //
    // If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry!
    Redacted bool `json:"redacted"`

    // ShouldShowLargeIcons.
    //
    // A hint to show a large icon for a reward
    ShouldShowLargeIcons bool `json:"shouldShowLargeIcons"`

    // LoreHash.
    //
    // 
    LoreHash uint32 `json:"loreHash"`

    // PresentationInfo.
    //
    // 
    PresentationInfo any `json:"presentationInfo"`

    // Requirements.
    //
    // Presentation nodes can be restricted by various requirements. This defines the rules of those requirements, and the message(s) to be shown if these requirements aren't met.
    Requirements any `json:"requirements"`

    // DisplayProperties.
    //
    // Many Destiny*Definition contracts - the "first order" entities of Destiny that have their own tables in the Manifest Database - also have displayable information. This is the base class for that display information.
    DisplayProperties any `json:"displayProperties"`

    // ExpirationInfo.
    //
    // If this record has an expiration after which it cannot be earned, this is some information about that expiration.
    ExpirationInfo any `json:"expirationInfo"`

    // ForTitleGilding.
    //
    // 
    ForTitleGilding bool `json:"forTitleGilding"`
}
