// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_DestinyStatDefinition struct {
    // Hash.
    //
    // The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.
    //
    // When entities refer to each other in Destiny content, it is this hash that they are referring to.
    Hash uint32 `json:"hash"`

    // Index.
    //
    // The index of the entity as it was found in the investment tables.
    Index int32 `json:"index"`

    // Redacted.
    //
    // If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry!
    Redacted bool `json:"redacted"`

    // StatCategory.
    //
    // The category of the stat, according to the game.
    StatCategory int32 `json:"statCategory"`

    // AggregationType.
    //
    // Stats can exist on a character or an item, and they may potentially be aggregated in different ways. The DestinyStatAggregationType enum value indicates the way that this stat is being aggregated.
    AggregationType int32 `json:"aggregationType"`

    // DisplayProperties.
    //
    // Many Destiny*Definition contracts - the "first order" entities of Destiny that have their own tables in the Manifest Database - also have displayable information. This is the base class for that display information.
    DisplayProperties any `json:"displayProperties"`

    // HasComputedBlock.
    //
    // True if the stat is computed rather than being delivered as a raw value on items.
    //
    // For instance, the Light stat in Destiny 1 was a computed stat.
    HasComputedBlock bool `json:"hasComputedBlock"`
}
