// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Entities_Items_DestinyItemPerksComponent struct {
    // Perks.
    //
    // The list of perks to display in an item tooltip - and whether or not they have been activated.
    Perks []Destiny_Perks_DestinyPerkReference `json:"perks"`
}
