// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // GlobalAlertLevelUnknown represents the Unknown enum in the GlobalAlertLevel component.
    GlobalAlertLevelUnknown int32 = 0

    // GlobalAlertLevelBlue represents the Blue enum in the GlobalAlertLevel component.
    GlobalAlertLevelBlue int32 = 1

    // GlobalAlertLevelYellow represents the Yellow enum in the GlobalAlertLevel component.
    GlobalAlertLevelYellow int32 = 2

    // GlobalAlertLevelRed represents the Red enum in the GlobalAlertLevel component.
    GlobalAlertLevelRed int32 = 3
)
