// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Config_GroupTheme struct {
    // Folder.
    //
    // 
    Folder string `json:"folder"`

    // Name.
    //
    // 
    Name string `json:"name"`

    // Description.
    //
    // 
    Description string `json:"description"`
}
