// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type GroupsV2_GroupBanRequest struct {
    // Comment.
    //
    // 
    Comment string `json:"comment"`

    // Length.
    //
    // 
    Length int32 `json:"length"`
}
