// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Forum_ForumMediaTypeNone represents the None enum in the Forum.ForumMediaType component.
    Forum_ForumMediaTypeNone int32 = 0

    // Forum_ForumMediaTypeImage represents the Image enum in the Forum.ForumMediaType component.
    Forum_ForumMediaTypeImage int32 = 1

    // Forum_ForumMediaTypeVideo represents the Video enum in the Forum.ForumMediaType component.
    Forum_ForumMediaTypeVideo int32 = 2

    // Forum_ForumMediaTypeYoutube represents the Youtube enum in the Forum.ForumMediaType component.
    Forum_ForumMediaTypeYoutube int32 = 3
)
