// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_DestinyRaceDefinition struct {
    // RaceType.
    //
    // An enumeration defining the existing, known Races/Species for player characters. This value will be the enum value matching this definition.
    RaceType int32 `json:"raceType"`

    // Redacted.
    //
    // If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry!
    Redacted bool `json:"redacted"`

    // DisplayProperties.
    //
    // Many Destiny*Definition contracts - the "first order" entities of Destiny that have their own tables in the Manifest Database - also have displayable information. This is the base class for that display information.
    DisplayProperties any `json:"displayProperties"`

    // GenderedRaceNames.
    //
    // A localized string referring to the singular form of the Race's name when referred to in gendered form. Keyed by the DestinyGender.
    GenderedRaceNames any `json:"genderedRaceNames"`

    // GenderedRaceNamesByGenderHash.
    //
    // 
    GenderedRaceNamesByGenderHash any `json:"genderedRaceNamesByGenderHash"`

    // Hash.
    //
    // The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.
    //
    // When entities refer to each other in Destiny content, it is this hash that they are referring to.
    Hash uint32 `json:"hash"`

    // Index.
    //
    // The index of the entity as it was found in the investment tables.
    Index int32 `json:"index"`
}
