// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Content_ContentItemPublicContract struct {
    // ModifyDate.
    //
    // 
    ModifyDate string `json:"modifyDate"`

    // Author.
    //
    // 
    Author any `json:"author"`

    // Representations.
    //
    // 
    Representations []Content_ContentRepresentation `json:"representations"`

    // AutoEnglishPropertyFallback.
    //
    // 
    AutoEnglishPropertyFallback bool `json:"autoEnglishPropertyFallback"`

    // AllowComments.
    //
    // 
    AllowComments bool `json:"allowComments"`

    // CType.
    //
    // 
    CType string `json:"cType"`

    // MinimumAge.
    //
    // 
    MinimumAge int32 `json:"minimumAge"`

    // CreationDate.
    //
    // 
    CreationDate string `json:"creationDate"`

    // Tags.
    //
    // NOTE: Tags will always be lower case.
    Tags []any `json:"tags"`

    // CmsPath.
    //
    // 
    CmsPath string `json:"cmsPath"`

    // RatingImagePath.
    //
    // 
    RatingImagePath string `json:"ratingImagePath"`

    // HasAgeGate.
    //
    // 
    HasAgeGate bool `json:"hasAgeGate"`

    // Properties.
    //
    // Firehose content is really a collection of metadata and "properties", which are the potentially-but-not-strictly localizable data that comprises the meat of whatever content is being shown.
    //
    // As Cole Porter would have crooned, "Anything Goes" with Firehose properties. They are most often strings, but they can theoretically be anything. They are JSON encoded, and could be JSON structures, simple strings, numbers etc... The Content Type of the item (cType) will describe the properties, and thus how they ought to be deserialized.
    Properties any `json:"properties"`

    // ContentId.
    //
    // 
    ContentId int64 `json:"contentId"`

    // CommentSummary.
    //
    // 
    CommentSummary any `json:"commentSummary"`
}
