// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_HistoricalStats_DestinyAggregateActivityResults struct {
    // Activities.
    //
    // List of all activities the player has participated in.
    Activities []Destiny_HistoricalStats_DestinyAggregateActivityStats `json:"activities"`
}
