// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_DestinyUnlockValueUIStyleAutomatic represents the Automatic enum in the Destiny.DestinyUnlockValueUIStyle component.
    //
    // Generally, Automatic means "Just show the number"
    Destiny_DestinyUnlockValueUIStyleAutomatic int32 = 0

    // Destiny_DestinyUnlockValueUIStyleFraction represents the Fraction enum in the Destiny.DestinyUnlockValueUIStyle component.
    //
    // Show the number as a fractional value. For this to make sense, the value being displayed should have a comparable upper bound, like the progress to the next level of a Progression.
    Destiny_DestinyUnlockValueUIStyleFraction int32 = 1

    // Destiny_DestinyUnlockValueUIStyleCheckbox represents the Checkbox enum in the Destiny.DestinyUnlockValueUIStyle component.
    //
    // Show the number as a checkbox. 0 Will mean unchecked, any other value will mean checked.
    Destiny_DestinyUnlockValueUIStyleCheckbox int32 = 2

    // Destiny_DestinyUnlockValueUIStylePercentage represents the Percentage enum in the Destiny.DestinyUnlockValueUIStyle component.
    //
    // Show the number as a percentage. For this to make sense, the value being displayed should have a comparable upper bound, like the progress to the next level of a Progression.
    Destiny_DestinyUnlockValueUIStylePercentage int32 = 3

    // Destiny_DestinyUnlockValueUIStyleDateTime represents the DateTime enum in the Destiny.DestinyUnlockValueUIStyle component.
    //
    // Show the number as a date and time. The number will be the number of seconds since the Unix Epoch (January 1st, 1970 at midnight UTC). It'll be up to you to convert this into a date and time format understandable to the user in their time zone.
    Destiny_DestinyUnlockValueUIStyleDateTime int32 = 4

    // Destiny_DestinyUnlockValueUIStyleFractionFloat represents the FractionFloat enum in the Destiny.DestinyUnlockValueUIStyle component.
    //
    // Show the number as a floating point value that represents a fraction, where 0 is min and 1 is max. For this to make sense, the value being displayed should have a comparable upper bound, like the progress to the next level of a Progression.
    Destiny_DestinyUnlockValueUIStyleFractionFloat int32 = 5

    // Destiny_DestinyUnlockValueUIStyleInteger represents the Integer enum in the Destiny.DestinyUnlockValueUIStyle component.
    //
    // Show the number as a straight-up integer.
    Destiny_DestinyUnlockValueUIStyleInteger int32 = 6

    // Destiny_DestinyUnlockValueUIStyleTimeDuration represents the TimeDuration enum in the Destiny.DestinyUnlockValueUIStyle component.
    //
    // Show the number as a time duration. The value will be returned as seconds.
    Destiny_DestinyUnlockValueUIStyleTimeDuration int32 = 7

    // Destiny_DestinyUnlockValueUIStyleHidden represents the Hidden enum in the Destiny.DestinyUnlockValueUIStyle component.
    //
    // Don't bother showing the value at all, it's not easily human-interpretable, and used for some internal purpose.
    Destiny_DestinyUnlockValueUIStyleHidden int32 = 8

    // Destiny_DestinyUnlockValueUIStyleMultiplier represents the Multiplier enum in the Destiny.DestinyUnlockValueUIStyle component.
    //
    // Example: "1.5x"
    Destiny_DestinyUnlockValueUIStyleMultiplier int32 = 9

    // Destiny_DestinyUnlockValueUIStyleGreenPips represents the GreenPips enum in the Destiny.DestinyUnlockValueUIStyle component.
    //
    // Show the value as a series of green pips, like the wins in a Trials of Osiris score card.
    Destiny_DestinyUnlockValueUIStyleGreenPips int32 = 10

    // Destiny_DestinyUnlockValueUIStyleRedPips represents the RedPips enum in the Destiny.DestinyUnlockValueUIStyle component.
    //
    // Show the value as a series of red pips, like the losses in a Trials of Osiris score card.
    Destiny_DestinyUnlockValueUIStyleRedPips int32 = 11

    // Destiny_DestinyUnlockValueUIStyleExplicitPercentage represents the ExplicitPercentage enum in the Destiny.DestinyUnlockValueUIStyle component.
    //
    // Show the value as a percentage. For example: "51%" - Does no division, only appends '%'
    Destiny_DestinyUnlockValueUIStyleExplicitPercentage int32 = 12

    // Destiny_DestinyUnlockValueUIStyleRawFloat represents the RawFloat enum in the Destiny.DestinyUnlockValueUIStyle component.
    //
    // Show the value as a floating-point number. For example: "4.52" NOTE: Passed along from Investment as whole number with last two digits as decimal values (452 -> 4.52)
    Destiny_DestinyUnlockValueUIStyleRawFloat int32 = 13

    // Destiny_DestinyUnlockValueUIStyleLevelAndReward represents the LevelAndReward enum in the Destiny.DestinyUnlockValueUIStyle component.
    //
    // Show the value as a level and a reward.
    Destiny_DestinyUnlockValueUIStyleLevelAndReward int32 = 14
)
