// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_DestinyClassTitan represents the Titan enum in the Destiny.DestinyClass component.
    Destiny_DestinyClassTitan int32 = 0

    // Destiny_DestinyClassHunter represents the Hunter enum in the Destiny.DestinyClass component.
    Destiny_DestinyClassHunter int32 = 1

    // Destiny_DestinyClassWarlock represents the Warlock enum in the Destiny.DestinyClass component.
    Destiny_DestinyClassWarlock int32 = 2

    // Destiny_DestinyClassUnknown represents the Unknown enum in the Destiny.DestinyClass component.
    Destiny_DestinyClassUnknown int32 = 3
)
