// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Fireteam_FireteamPlatformAny represents the Any enum in the Fireteam.FireteamPlatform component.
    Fireteam_FireteamPlatformAny byte = 0

    // Fireteam_FireteamPlatformPlaystation4 represents the Playstation4 enum in the Fireteam.FireteamPlatform component.
    Fireteam_FireteamPlatformPlaystation4 byte = 1

    // Fireteam_FireteamPlatformXboxOne represents the XboxOne enum in the Fireteam.FireteamPlatform component.
    Fireteam_FireteamPlatformXboxOne byte = 2

    // Fireteam_FireteamPlatformBlizzard represents the Blizzard enum in the Fireteam.FireteamPlatform component.
    Fireteam_FireteamPlatformBlizzard byte = 3

    // Fireteam_FireteamPlatformSteam represents the Steam enum in the Fireteam.FireteamPlatform component.
    Fireteam_FireteamPlatformSteam byte = 4

    // Fireteam_FireteamPlatformStadia represents the Stadia enum in the Fireteam.FireteamPlatform component.
    Fireteam_FireteamPlatformStadia byte = 5

    // Fireteam_FireteamPlatformEgs represents the Egs enum in the Fireteam.FireteamPlatform component.
    Fireteam_FireteamPlatformEgs byte = 6
)
