// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_DestinyActivityModeCategoryNone represents the None enum in the Destiny.DestinyActivityModeCategory component.
    //
    // Activities that are neither PVP nor PVE, such as social activities.
    Destiny_DestinyActivityModeCategoryNone int32 = 0

    // Destiny_DestinyActivityModeCategoryPvE represents the PvE enum in the Destiny.DestinyActivityModeCategory component.
    //
    // PvE activities, where you shoot aliens in the face.
    Destiny_DestinyActivityModeCategoryPvE int32 = 1

    // Destiny_DestinyActivityModeCategoryPvP represents the PvP enum in the Destiny.DestinyActivityModeCategory component.
    //
    // PvP activities, where you shoot your "friends".
    Destiny_DestinyActivityModeCategoryPvP int32 = 2

    // Destiny_DestinyActivityModeCategoryPvECompetitive represents the PvECompetitive enum in the Destiny.DestinyActivityModeCategory component.
    //
    // PVE competitive activities, where you shoot whoever you want whenever you want. Or run around collecting small glowing triangles.
    Destiny_DestinyActivityModeCategoryPvECompetitive int32 = 3
)
