// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_FireteamFinder_DestinyFireteamFinderOptionValueDefinition struct {
    // Flags.
    //
    // 
    Flags int32 `json:"flags"`

    // Value.
    //
    // 
    Value uint32 `json:"value"`

    // DisplayProperties.
    //
    // Many Destiny*Definition contracts - the "first order" entities of Destiny that have their own tables in the Manifest Database - also have displayable information. This is the base class for that display information.
    DisplayProperties any `json:"displayProperties"`
}
