// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Tokens_PartnerOfferHistoryResponse struct {
    // PartnerOfferKey.
    //
    // 
    PartnerOfferKey string `json:"PartnerOfferKey"`

    // QuantityApplied.
    //
    // 
    QuantityApplied int32 `json:"QuantityApplied"`

    // ApplyDate.
    //
    // 
    ApplyDate string `json:"ApplyDate"`

    // IsConsumable.
    //
    // 
    IsConsumable bool `json:"IsConsumable"`

    // LocalizedDescription.
    //
    // 
    LocalizedDescription string `json:"LocalizedDescription"`

    // LocalizedName.
    //
    // 
    LocalizedName string `json:"LocalizedName"`

    // MembershipId.
    //
    // 
    MembershipId int64 `json:"MembershipId"`

    // MembershipType.
    //
    // 
    MembershipType int32 `json:"MembershipType"`
}
