// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Constants_DestinyEnvironmentLocationMapping struct {
    // ItemHash.
    //
    // If this is populated, it is the item that you must possess for this location to be active because of this mapping. (theoretically, a location can have multiple mappings, and some might require an item while others don't)
    ItemHash uint32 `json:"itemHash"`

    // LocationHash.
    //
    // The location that is revealed on the director by this mapping.
    LocationHash uint32 `json:"locationHash"`

    // ObjectiveHash.
    //
    // If this is populated, this is an objective related to the location.
    ObjectiveHash uint32 `json:"objectiveHash"`

    // ActivationSource.
    //
    // A hint that the UI uses to figure out how this location is activated by the player.
    ActivationSource string `json:"activationSource"`

    // ActivityHash.
    //
    // If this is populated, this is the activity you have to be playing in order to see this location appear because of this mapping. (theoretically, a location can have multiple mappings, and some might require you to be in a specific activity when others don't)
    ActivityHash uint32 `json:"activityHash"`
}
