// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_HistoricalStats_Definitions_UnitTypeNone represents the None enum in the Destiny.HistoricalStats.Definitions.UnitType component.
    Destiny_HistoricalStats_Definitions_UnitTypeNone int32 = 0

    // Destiny_HistoricalStats_Definitions_UnitTypeCount represents the Count enum in the Destiny.HistoricalStats.Definitions.UnitType component.
    //
    // Indicates the statistic is a simple count of something.
    Destiny_HistoricalStats_Definitions_UnitTypeCount int32 = 1

    // Destiny_HistoricalStats_Definitions_UnitTypePerGame represents the PerGame enum in the Destiny.HistoricalStats.Definitions.UnitType component.
    //
    // Indicates the statistic is a per game average.
    Destiny_HistoricalStats_Definitions_UnitTypePerGame int32 = 2

    // Destiny_HistoricalStats_Definitions_UnitTypeSeconds represents the Seconds enum in the Destiny.HistoricalStats.Definitions.UnitType component.
    //
    // Indicates the number of seconds
    Destiny_HistoricalStats_Definitions_UnitTypeSeconds int32 = 3

    // Destiny_HistoricalStats_Definitions_UnitTypePoints represents the Points enum in the Destiny.HistoricalStats.Definitions.UnitType component.
    //
    // Indicates the number of points earned
    Destiny_HistoricalStats_Definitions_UnitTypePoints int32 = 4

    // Destiny_HistoricalStats_Definitions_UnitTypeTeam represents the Team enum in the Destiny.HistoricalStats.Definitions.UnitType component.
    //
    // Values represents a team ID
    Destiny_HistoricalStats_Definitions_UnitTypeTeam int32 = 5

    // Destiny_HistoricalStats_Definitions_UnitTypeDistance represents the Distance enum in the Destiny.HistoricalStats.Definitions.UnitType component.
    //
    // Values represents a distance (units to-be-determined)
    Destiny_HistoricalStats_Definitions_UnitTypeDistance int32 = 6

    // Destiny_HistoricalStats_Definitions_UnitTypePercent represents the Percent enum in the Destiny.HistoricalStats.Definitions.UnitType component.
    //
    // Ratio represented as a whole value from 0 to 100.
    Destiny_HistoricalStats_Definitions_UnitTypePercent int32 = 7

    // Destiny_HistoricalStats_Definitions_UnitTypeRatio represents the Ratio enum in the Destiny.HistoricalStats.Definitions.UnitType component.
    //
    // Ratio of something, shown with decimal places
    Destiny_HistoricalStats_Definitions_UnitTypeRatio int32 = 8

    // Destiny_HistoricalStats_Definitions_UnitTypeBoolean represents the Boolean enum in the Destiny.HistoricalStats.Definitions.UnitType component.
    //
    // True or false
    Destiny_HistoricalStats_Definitions_UnitTypeBoolean int32 = 9

    // Destiny_HistoricalStats_Definitions_UnitTypeWeaponType represents the WeaponType enum in the Destiny.HistoricalStats.Definitions.UnitType component.
    //
    // The stat is actually a weapon type.
    Destiny_HistoricalStats_Definitions_UnitTypeWeaponType int32 = 10

    // Destiny_HistoricalStats_Definitions_UnitTypeStanding represents the Standing enum in the Destiny.HistoricalStats.Definitions.UnitType component.
    //
    // Indicates victory, defeat, or something in between.
    Destiny_HistoricalStats_Definitions_UnitTypeStanding int32 = 11

    // Destiny_HistoricalStats_Definitions_UnitTypeMilliseconds represents the Milliseconds enum in the Destiny.HistoricalStats.Definitions.UnitType component.
    //
    // Number of milliseconds some event spanned. For example, race time, or lap time.
    Destiny_HistoricalStats_Definitions_UnitTypeMilliseconds int32 = 12

    // Destiny_HistoricalStats_Definitions_UnitTypeCompletionReason represents the CompletionReason enum in the Destiny.HistoricalStats.Definitions.UnitType component.
    //
    // The value is a enumeration of the Completion Reason type.
    Destiny_HistoricalStats_Definitions_UnitTypeCompletionReason int32 = 13
)
