// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_Definitions_DestinyRewardSourceCategoryNone represents the None enum in the Destiny.Definitions.DestinyRewardSourceCategory component.
    //
    // The source doesn't fit well into any of the other types.
    Destiny_Definitions_DestinyRewardSourceCategoryNone int32 = 0

    // Destiny_Definitions_DestinyRewardSourceCategoryActivity represents the Activity enum in the Destiny.Definitions.DestinyRewardSourceCategory component.
    //
    // The source is directly related to the rewards gained by playing an activity or set of activities. This currently includes Quests and other action in-game.
    Destiny_Definitions_DestinyRewardSourceCategoryActivity int32 = 1

    // Destiny_Definitions_DestinyRewardSourceCategoryVendor represents the Vendor enum in the Destiny.Definitions.DestinyRewardSourceCategory component.
    //
    // This source is directly related to items that Vendors sell.
    Destiny_Definitions_DestinyRewardSourceCategoryVendor int32 = 2

    // Destiny_Definitions_DestinyRewardSourceCategoryAggregate represents the Aggregate enum in the Destiny.Definitions.DestinyRewardSourceCategory component.
    //
    // This source is a custom aggregation of items that can be earned in many ways, but that share some other property in common that is useful to share. For instance, in Destiny 1 we would make "Reward Sources" for every game expansion: that way, you could search reward sources to see what items became available with any given Expansion.
    Destiny_Definitions_DestinyRewardSourceCategoryAggregate int32 = 3
)
