// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Entities_Items_DestinyItemObjectivesComponent struct {
    // DateCompleted.
    //
    // If we have any information on when these objectives were completed, this will be the date of that completion. This won't be on many items, but could be interesting for some items that do store this information.
    DateCompleted *string `json:"dateCompleted"`

    // FlavorObjective.
    //
    // I may regret naming it this way - but this represents when an item has an objective that doesn't serve a beneficial purpose, but rather is used for "flavor" or additional information. For instance, when Emblems track specific stats, those stats are represented as Objectives on the item.
    FlavorObjective any `json:"flavorObjective"`

    // Objectives.
    //
    // If the item has a hard association with objectives, your progress on them will be defined here. 
    //
    // Objectives are our standard way to describe a series of tasks that have to be completed for a reward.
    Objectives []Destiny_Quests_DestinyObjectiveProgress `json:"objectives"`
}
