// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_HistoricalStats_DestinyHistoricalWeaponStatsData struct {
    // Weapons.
    //
    // List of weapons and their perspective values.
    Weapons []Destiny_HistoricalStats_DestinyHistoricalWeaponStats `json:"weapons"`
}
