// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_DestinyVendorActionDefinition struct {
    // Verb.
    //
    // 
    Verb string `json:"verb"`

    // ActionHash.
    //
    // 
    ActionHash uint32 `json:"actionHash"`

    // ActionId.
    //
    // 
    ActionId string `json:"actionId"`

    // Icon.
    //
    // 
    Icon string `json:"icon"`

    // ExecuteSeconds.
    //
    // 
    ExecuteSeconds int32 `json:"executeSeconds"`

    // AutoPerformAction.
    //
    // 
    AutoPerformAction bool `json:"autoPerformAction"`

    // Description.
    //
    // 
    Description string `json:"description"`

    // IsPositive.
    //
    // 
    IsPositive bool `json:"isPositive"`

    // Name.
    //
    // 
    Name string `json:"name"`
}
