// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Applications_ApiUsage struct {
    // ApiCalls.
    //
    // Counts for on API calls made for the time range.
    ApiCalls []Applications_Series `json:"apiCalls"`

    // ThrottledRequests.
    //
    // Instances of blocked requests or requests that crossed the warn threshold during the time range.
    ThrottledRequests []Applications_Series `json:"throttledRequests"`
}
