// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_DestinyVendorRequirementDisplayEntryDefinition struct {
    // Icon.
    //
    // 
    Icon string `json:"icon"`

    // Name.
    //
    // 
    Name string `json:"name"`

    // Source.
    //
    // 
    Source string `json:"source"`

    // Type.
    //
    // 
    Type string `json:"type"`
}
