// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Tokens_RewardDisplayProperties struct {
    // Name.
    //
    // 
    Name string `json:"Name"`

    // Description.
    //
    // 
    Description string `json:"Description"`

    // ImagePath.
    //
    // 
    ImagePath string `json:"ImagePath"`
}
