// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_HistoricalStats_Definitions_DestinyHistoricalStatsDefinition struct {
    // UnitType.
    //
    // Unit, if any, for the statistic
    UnitType int32 `json:"unitType"`

    // StatDescription.
    //
    // Description of a stat if applicable.
    StatDescription string `json:"statDescription"`

    // IconImage.
    //
    // Optional URI to an icon for the statistic
    IconImage string `json:"iconImage"`

    // PeriodTypes.
    //
    // Time periods the statistic covers
    PeriodTypes []any `json:"periodTypes"`

    // StatNameAbbr.
    //
    // Display name abbreviated
    StatNameAbbr string `json:"statNameAbbr"`

    // UnitLabel.
    //
    // Localized Unit Name for the stat.
    UnitLabel string `json:"unitLabel"`

    // Category.
    //
    // Category for the stat.
    Category int32 `json:"category"`

    // MedalTierHash.
    //
    // The tier associated with this medal - be it implicitly or explicitly.
    MedalTierHash uint32 `json:"medalTierHash"`

    // MergeMethod.
    //
    // Optional icon for the statistic
    MergeMethod int32 `json:"mergeMethod"`

    // StatName.
    //
    // Display name
    StatName string `json:"statName"`

    // Weight.
    //
    // Weight assigned to this stat indicating its relative impressiveness.
    Weight int32 `json:"weight"`

    // Group.
    //
    // Statistic group
    Group int32 `json:"group"`

    // Modes.
    //
    // Game modes where this statistic can be reported.
    Modes []any `json:"modes"`

    // StatId.
    //
    // Unique programmer friendly ID for this stat
    StatId string `json:"statId"`
}
