// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_EquippingItemBlockAttributesNone represents the None enum in the Destiny.EquippingItemBlockAttributes component.
    Destiny_EquippingItemBlockAttributesNone int32 = 0

    // Destiny_EquippingItemBlockAttributesEquipOnAcquire represents the EquipOnAcquire enum in the Destiny.EquippingItemBlockAttributes component.
    Destiny_EquippingItemBlockAttributesEquipOnAcquire int32 = 1
)
