// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Forum_ForumRecruitmentToneLabelNone represents the None enum in the Forum.ForumRecruitmentToneLabel component.
    Forum_ForumRecruitmentToneLabelNone byte = 0

    // Forum_ForumRecruitmentToneLabelFamilyFriendly represents the FamilyFriendly enum in the Forum.ForumRecruitmentToneLabel component.
    Forum_ForumRecruitmentToneLabelFamilyFriendly byte = 1

    // Forum_ForumRecruitmentToneLabelRowdy represents the Rowdy enum in the Forum.ForumRecruitmentToneLabel component.
    Forum_ForumRecruitmentToneLabelRowdy byte = 2
)
