// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Common_Models_CoreSettingsConfiguration struct {
    // DefaultGroupTheme.
    //
    // 
    DefaultGroupTheme Common_Models_CoreSetting `json:"defaultGroupTheme"`

    // Environment.
    //
    // 
    Environment string `json:"environment"`

    // ClanBannerDecals.
    //
    // 
    ClanBannerDecals []Common_Models_CoreSetting `json:"clanBannerDecals"`

    // RecruitmentMiscTags.
    //
    // 
    RecruitmentMiscTags []Common_Models_CoreSetting `json:"recruitmentMiscTags"`

    // EmailSettings.
    //
    // The set of all email subscription/opt-in settings and definitions.
    EmailSettings User_EmailSettings `json:"emailSettings"`

    // GroupAvatars.
    //
    // 
    GroupAvatars []Common_Models_CoreSetting `json:"groupAvatars"`

    // RecruitmentPlatformTags.
    //
    // 
    RecruitmentPlatformTags []Common_Models_CoreSetting `json:"recruitmentPlatformTags"`

    // SystemContentLocales.
    //
    // 
    SystemContentLocales []Common_Models_CoreSetting `json:"systemContentLocales"`

    // ForumCategories.
    //
    // 
    ForumCategories []Common_Models_CoreSetting `json:"forumCategories"`

    // ClanBannerGonfalonDetails.
    //
    // 
    ClanBannerGonfalonDetails []Common_Models_CoreSetting `json:"clanBannerGonfalonDetails"`

    // IgnoreReasons.
    //
    // 
    IgnoreReasons []Common_Models_CoreSetting `json:"ignoreReasons"`

    // ClanBannerGonfalonColors.
    //
    // 
    ClanBannerGonfalonColors []Common_Models_CoreSetting `json:"clanBannerGonfalonColors"`

    // DestinyMembershipTypes.
    //
    // 
    DestinyMembershipTypes []Common_Models_CoreSetting `json:"destinyMembershipTypes"`

    // FireteamActivities.
    //
    // 
    FireteamActivities []Common_Models_CoreSetting `json:"fireteamActivities"`

    // ClanBannerGonfalonDetailColors.
    //
    // 
    ClanBannerGonfalonDetailColors []Common_Models_CoreSetting `json:"clanBannerGonfalonDetailColors"`

    // Systems.
    //
    // 
    Systems any `json:"systems"`

    // ClanBannerDecalColors.
    //
    // 
    ClanBannerDecalColors []Common_Models_CoreSetting `json:"clanBannerDecalColors"`

    // ClanBannerGonfalons.
    //
    // 
    ClanBannerGonfalons []Common_Models_CoreSetting `json:"clanBannerGonfalons"`

    // Destiny2CoreSettings.
    //
    // 
    Destiny2CoreSettings Common_Models_Destiny2CoreSettings `json:"destiny2CoreSettings"`

    // RecruitmentActivities.
    //
    // 
    RecruitmentActivities []Common_Models_CoreSetting `json:"recruitmentActivities"`

    // UserContentLocales.
    //
    // 
    UserContentLocales []Common_Models_CoreSetting `json:"userContentLocales"`

    // ClanBannerStandards.
    //
    // 
    ClanBannerStandards []Common_Models_CoreSetting `json:"clanBannerStandards"`
}
