// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_DestinyItemTalentGridBlockDefinition struct {
    // HudIcon.
    //
    // If the talent grid has a special icon that's shown in the game UI (like builds, funny that), this is the identifier for that icon. Sadly, we don't actually get that icon right now. I'll be looking to replace this with a path to the actual icon itself.
    HudIcon string `json:"hudIcon"`

    // ItemDetailString.
    //
    // This is meant to be a subtitle for looking at the talent grid. In practice, somewhat frustratingly, this always merely says the localized word for "Details". Great. Maybe it'll have more if talent grids ever get used for more than builds and subclasses again.
    ItemDetailString string `json:"itemDetailString"`

    // TalentGridHash.
    //
    // The hash identifier of the DestinyTalentGridDefinition attached to this item.
    TalentGridHash uint32 `json:"talentGridHash"`

    // BuildName.
    //
    // A shortcut string identifier for the "build" in question, if this talent grid has an associated build. Doesn't map to anything we can expose at the moment.
    BuildName string `json:"buildName"`

    // HudDamageType.
    //
    // If the talent grid implies a damage type, this is the enum value for that damage type.
    HudDamageType int32 `json:"hudDamageType"`
}
