// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type GroupsV2_ClanBanner struct {
    // GonfalonColorId.
    //
    // 
    GonfalonColorId uint32 `json:"gonfalonColorId"`

    // GonfalonDetailColorId.
    //
    // 
    GonfalonDetailColorId uint32 `json:"gonfalonDetailColorId"`

    // GonfalonDetailId.
    //
    // 
    GonfalonDetailId uint32 `json:"gonfalonDetailId"`

    // GonfalonId.
    //
    // 
    GonfalonId uint32 `json:"gonfalonId"`

    // DecalBackgroundColorId.
    //
    // 
    DecalBackgroundColorId uint32 `json:"decalBackgroundColorId"`

    // DecalColorId.
    //
    // 
    DecalColorId uint32 `json:"decalColorId"`

    // DecalId.
    //
    // 
    DecalId uint32 `json:"decalId"`
}
