// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_DestinyItemTooltipNotification struct {
    // DisplayStyle.
    //
    // 
    DisplayStyle string `json:"displayStyle"`

    // DisplayString.
    //
    // 
    DisplayString string `json:"displayString"`
}
