// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_Checklists_DestinyChecklistDefinition struct {
    // Entries.
    //
    // The individual checklist items. Gotta catch 'em all.
    Entries []Destiny_Definitions_Checklists_DestinyChecklistEntryDefinition `json:"entries"`

    // Hash.
    //
    // The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.
    //
    // When entities refer to each other in Destiny content, it is this hash that they are referring to.
    Hash uint32 `json:"hash"`

    // Index.
    //
    // The index of the entity as it was found in the investment tables.
    Index int32 `json:"index"`

    // Redacted.
    //
    // If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry!
    Redacted bool `json:"redacted"`

    // Scope.
    //
    // Indicates whether you will find this checklist on the Profile or Character components.
    Scope int32 `json:"scope"`

    // ViewActionString.
    //
    // A localized string prompting you to view the checklist.
    ViewActionString string `json:"viewActionString"`

    // DisplayProperties.
    //
    // Many Destiny*Definition contracts - the "first order" entities of Destiny that have their own tables in the Manifest Database - also have displayable information. This is the base class for that display information.
    DisplayProperties any `json:"displayProperties"`
}
