// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Components_Loadouts_DestinyLoadoutItemComponent struct {
    // ItemInstanceId.
    //
    // 
    ItemInstanceId int64 `json:"itemInstanceId"`

    // PlugItemHashes.
    //
    // 
    PlugItemHashes []uint32 `json:"plugItemHashes"`
}
