// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // GroupsV2_HostGuidedGamesPermissionLevelNone represents the None enum in the GroupsV2.HostGuidedGamesPermissionLevel component.
    GroupsV2_HostGuidedGamesPermissionLevelNone int32 = 0

    // GroupsV2_HostGuidedGamesPermissionLevelBeginner represents the Beginner enum in the GroupsV2.HostGuidedGamesPermissionLevel component.
    GroupsV2_HostGuidedGamesPermissionLevelBeginner int32 = 1

    // GroupsV2_HostGuidedGamesPermissionLevelMember represents the Member enum in the GroupsV2.HostGuidedGamesPermissionLevel component.
    GroupsV2_HostGuidedGamesPermissionLevelMember int32 = 2
)
