// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_HistoricalStats_Definitions_DestinyStatsCategoryTypeNone represents the None enum in the Destiny.HistoricalStats.Definitions.DestinyStatsCategoryType component.
    Destiny_HistoricalStats_Definitions_DestinyStatsCategoryTypeNone int32 = 0

    // Destiny_HistoricalStats_Definitions_DestinyStatsCategoryTypeKills represents the Kills enum in the Destiny.HistoricalStats.Definitions.DestinyStatsCategoryType component.
    Destiny_HistoricalStats_Definitions_DestinyStatsCategoryTypeKills int32 = 1

    // Destiny_HistoricalStats_Definitions_DestinyStatsCategoryTypeAssists represents the Assists enum in the Destiny.HistoricalStats.Definitions.DestinyStatsCategoryType component.
    Destiny_HistoricalStats_Definitions_DestinyStatsCategoryTypeAssists int32 = 2

    // Destiny_HistoricalStats_Definitions_DestinyStatsCategoryTypeDeaths represents the Deaths enum in the Destiny.HistoricalStats.Definitions.DestinyStatsCategoryType component.
    Destiny_HistoricalStats_Definitions_DestinyStatsCategoryTypeDeaths int32 = 3

    // Destiny_HistoricalStats_Definitions_DestinyStatsCategoryTypeCriticals represents the Criticals enum in the Destiny.HistoricalStats.Definitions.DestinyStatsCategoryType component.
    Destiny_HistoricalStats_Definitions_DestinyStatsCategoryTypeCriticals int32 = 4

    // Destiny_HistoricalStats_Definitions_DestinyStatsCategoryTypeKDa represents the KDa enum in the Destiny.HistoricalStats.Definitions.DestinyStatsCategoryType component.
    Destiny_HistoricalStats_Definitions_DestinyStatsCategoryTypeKDa int32 = 5

    // Destiny_HistoricalStats_Definitions_DestinyStatsCategoryTypeKD represents the KD enum in the Destiny.HistoricalStats.Definitions.DestinyStatsCategoryType component.
    Destiny_HistoricalStats_Definitions_DestinyStatsCategoryTypeKD int32 = 6

    // Destiny_HistoricalStats_Definitions_DestinyStatsCategoryTypeScore represents the Score enum in the Destiny.HistoricalStats.Definitions.DestinyStatsCategoryType component.
    Destiny_HistoricalStats_Definitions_DestinyStatsCategoryTypeScore int32 = 7

    // Destiny_HistoricalStats_Definitions_DestinyStatsCategoryTypeEntered represents the Entered enum in the Destiny.HistoricalStats.Definitions.DestinyStatsCategoryType component.
    Destiny_HistoricalStats_Definitions_DestinyStatsCategoryTypeEntered int32 = 8

    // Destiny_HistoricalStats_Definitions_DestinyStatsCategoryTypeTimePlayed represents the TimePlayed enum in the Destiny.HistoricalStats.Definitions.DestinyStatsCategoryType component.
    Destiny_HistoricalStats_Definitions_DestinyStatsCategoryTypeTimePlayed int32 = 9

    // Destiny_HistoricalStats_Definitions_DestinyStatsCategoryTypeMedalWins represents the MedalWins enum in the Destiny.HistoricalStats.Definitions.DestinyStatsCategoryType component.
    Destiny_HistoricalStats_Definitions_DestinyStatsCategoryTypeMedalWins int32 = 10

    // Destiny_HistoricalStats_Definitions_DestinyStatsCategoryTypeMedalGame represents the MedalGame enum in the Destiny.HistoricalStats.Definitions.DestinyStatsCategoryType component.
    Destiny_HistoricalStats_Definitions_DestinyStatsCategoryTypeMedalGame int32 = 11

    // Destiny_HistoricalStats_Definitions_DestinyStatsCategoryTypeMedalSpecialKills represents the MedalSpecialKills enum in the Destiny.HistoricalStats.Definitions.DestinyStatsCategoryType component.
    Destiny_HistoricalStats_Definitions_DestinyStatsCategoryTypeMedalSpecialKills int32 = 12

    // Destiny_HistoricalStats_Definitions_DestinyStatsCategoryTypeMedalSprees represents the MedalSprees enum in the Destiny.HistoricalStats.Definitions.DestinyStatsCategoryType component.
    Destiny_HistoricalStats_Definitions_DestinyStatsCategoryTypeMedalSprees int32 = 13

    // Destiny_HistoricalStats_Definitions_DestinyStatsCategoryTypeMedalMultiKills represents the MedalMultiKills enum in the Destiny.HistoricalStats.Definitions.DestinyStatsCategoryType component.
    Destiny_HistoricalStats_Definitions_DestinyStatsCategoryTypeMedalMultiKills int32 = 14

    // Destiny_HistoricalStats_Definitions_DestinyStatsCategoryTypeMedalAbilities represents the MedalAbilities enum in the Destiny.HistoricalStats.Definitions.DestinyStatsCategoryType component.
    Destiny_HistoricalStats_Definitions_DestinyStatsCategoryTypeMedalAbilities int32 = 15
)
