// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_DestinyEquipItemResults struct {
    // EquipResults.
    //
    // 
    EquipResults []Destiny_DestinyEquipItemResult `json:"equipResults"`
}
