// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Forum_ForumTopicsCategoryFiltersEnumNone represents the None enum in the Forum.ForumTopicsCategoryFiltersEnum component.
    Forum_ForumTopicsCategoryFiltersEnumNone int32 = 0

    // Forum_ForumTopicsCategoryFiltersEnumLinks represents the Links enum in the Forum.ForumTopicsCategoryFiltersEnum component.
    Forum_ForumTopicsCategoryFiltersEnumLinks int32 = 1

    // Forum_ForumTopicsCategoryFiltersEnumQuestions represents the Questions enum in the Forum.ForumTopicsCategoryFiltersEnum component.
    Forum_ForumTopicsCategoryFiltersEnumQuestions int32 = 2

    // Forum_ForumTopicsCategoryFiltersEnumAnsweredQuestions represents the AnsweredQuestions enum in the Forum.ForumTopicsCategoryFiltersEnum component.
    Forum_ForumTopicsCategoryFiltersEnumAnsweredQuestions int32 = 4

    // Forum_ForumTopicsCategoryFiltersEnumMedia represents the Media enum in the Forum.ForumTopicsCategoryFiltersEnum component.
    Forum_ForumTopicsCategoryFiltersEnumMedia int32 = 8

    // Forum_ForumTopicsCategoryFiltersEnumTextOnly represents the TextOnly enum in the Forum.ForumTopicsCategoryFiltersEnum component.
    Forum_ForumTopicsCategoryFiltersEnumTextOnly int32 = 16

    // Forum_ForumTopicsCategoryFiltersEnumAnnouncement represents the Announcement enum in the Forum.ForumTopicsCategoryFiltersEnum component.
    Forum_ForumTopicsCategoryFiltersEnumAnnouncement int32 = 32

    // Forum_ForumTopicsCategoryFiltersEnumBungieOfficial represents the BungieOfficial enum in the Forum.ForumTopicsCategoryFiltersEnum component.
    Forum_ForumTopicsCategoryFiltersEnumBungieOfficial int32 = 64

    // Forum_ForumTopicsCategoryFiltersEnumPolls represents the Polls enum in the Forum.ForumTopicsCategoryFiltersEnum component.
    Forum_ForumTopicsCategoryFiltersEnumPolls int32 = 128
)
