// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_DestinyItemSortTypeItemId represents the ItemId enum in the Destiny.DestinyItemSortType component.
    Destiny_DestinyItemSortTypeItemId int32 = 0

    // Destiny_DestinyItemSortTypeTimestamp represents the Timestamp enum in the Destiny.DestinyItemSortType component.
    Destiny_DestinyItemSortTypeTimestamp int32 = 1

    // Destiny_DestinyItemSortTypeStackSize represents the StackSize enum in the Destiny.DestinyItemSortType component.
    Destiny_DestinyItemSortTypeStackSize int32 = 2
)
