// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_DestinySandboxPatternDefinition struct {
    // Filters.
    //
    // 
    Filters []Destiny_Definitions_DestinyArrangementRegionFilterDefinition `json:"filters"`

    // Hash.
    //
    // The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.
    //
    // When entities refer to each other in Destiny content, it is this hash that they are referring to.
    Hash uint32 `json:"hash"`

    // Index.
    //
    // The index of the entity as it was found in the investment tables.
    Index int32 `json:"index"`

    // PatternGlobalTagIdHash.
    //
    // 
    PatternGlobalTagIdHash uint32 `json:"patternGlobalTagIdHash"`

    // PatternHash.
    //
    // 
    PatternHash uint32 `json:"patternHash"`

    // Redacted.
    //
    // If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry!
    Redacted bool `json:"redacted"`

    // WeaponContentGroupHash.
    //
    // 
    WeaponContentGroupHash uint32 `json:"weaponContentGroupHash"`

    // WeaponTranslationGroupHash.
    //
    // 
    WeaponTranslationGroupHash uint32 `json:"weaponTranslationGroupHash"`

    // WeaponType.
    //
    // 
    WeaponType int32 `json:"weaponType"`

    // WeaponTypeHash.
    //
    // 
    WeaponTypeHash *uint32 `json:"weaponTypeHash"`
}
