// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_DestinyVendorFilterNone represents the None enum in the Destiny.DestinyVendorFilter component.
    Destiny_DestinyVendorFilterNone int32 = 0

    // Destiny_DestinyVendorFilterApiPurchasable represents the ApiPurchasable enum in the Destiny.DestinyVendorFilter component.
    Destiny_DestinyVendorFilterApiPurchasable int32 = 1
)
