// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // GroupsV2_CapabilitiesNone represents the None enum in the GroupsV2.Capabilities component.
    GroupsV2_CapabilitiesNone int32 = 0

    // GroupsV2_CapabilitiesLeaderboards represents the Leaderboards enum in the GroupsV2.Capabilities component.
    GroupsV2_CapabilitiesLeaderboards int32 = 1

    // GroupsV2_CapabilitiesCallsign represents the Callsign enum in the GroupsV2.Capabilities component.
    GroupsV2_CapabilitiesCallsign int32 = 2

    // GroupsV2_CapabilitiesOptionalConversations represents the OptionalConversations enum in the GroupsV2.Capabilities component.
    GroupsV2_CapabilitiesOptionalConversations int32 = 4

    // GroupsV2_CapabilitiesClanBanner represents the ClanBanner enum in the GroupsV2.Capabilities component.
    GroupsV2_CapabilitiesClanBanner int32 = 8

    // GroupsV2_CapabilitiesD2InvestmentData represents the D2InvestmentData enum in the GroupsV2.Capabilities component.
    GroupsV2_CapabilitiesD2InvestmentData int32 = 16

    // GroupsV2_CapabilitiesTags represents the Tags enum in the GroupsV2.Capabilities component.
    GroupsV2_CapabilitiesTags int32 = 32

    // GroupsV2_CapabilitiesAlliances represents the Alliances enum in the GroupsV2.Capabilities component.
    GroupsV2_CapabilitiesAlliances int32 = 64
)
