// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_Director_DestinyActivityGraphNodeStateEntry struct {
    // State.
    //
    // 
    State int32 `json:"state"`
}
