// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Requests_Actions_DestinyItemSetActionRequest struct {
    // MembershipType.
    //
    // 
    MembershipType int32 `json:"membershipType"`

    // CharacterId.
    //
    // 
    CharacterId int64 `json:"characterId"`

    // ItemIds.
    //
    // 
    ItemIds []int64 `json:"itemIds"`
}
