// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Config_GearAssetDataBaseDefinition struct {
    // Path.
    //
    // 
    Path string `json:"path"`

    // Version.
    //
    // 
    Version int32 `json:"version"`
}
