// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type FireteamFinder_DestinyFireteamFinderLobbyPlayer struct {
    // ReferralToken.
    //
    // 
    ReferralToken int64 `json:"referralToken"`

    // State.
    //
    // 
    State int32 `json:"state"`

    // OfferId.
    //
    // 
    OfferId int64 `json:"offerId"`

    // PlayerId.
    //
    // 
    PlayerId FireteamFinder_DestinyFireteamFinderPlayerId `json:"playerId"`
}
