// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_DestinyTalentNodeStateInvalid represents the Invalid enum in the Destiny.DestinyTalentNodeState component.
    Destiny_DestinyTalentNodeStateInvalid int32 = 0

    // Destiny_DestinyTalentNodeStateCanUpgrade represents the CanUpgrade enum in the Destiny.DestinyTalentNodeState component.
    Destiny_DestinyTalentNodeStateCanUpgrade int32 = 1

    // Destiny_DestinyTalentNodeStateNoPoints represents the NoPoints enum in the Destiny.DestinyTalentNodeState component.
    Destiny_DestinyTalentNodeStateNoPoints int32 = 2

    // Destiny_DestinyTalentNodeStateNoPrerequisites represents the NoPrerequisites enum in the Destiny.DestinyTalentNodeState component.
    Destiny_DestinyTalentNodeStateNoPrerequisites int32 = 3

    // Destiny_DestinyTalentNodeStateNoSteps represents the NoSteps enum in the Destiny.DestinyTalentNodeState component.
    Destiny_DestinyTalentNodeStateNoSteps int32 = 4

    // Destiny_DestinyTalentNodeStateNoUnlock represents the NoUnlock enum in the Destiny.DestinyTalentNodeState component.
    Destiny_DestinyTalentNodeStateNoUnlock int32 = 5

    // Destiny_DestinyTalentNodeStateNoMaterial represents the NoMaterial enum in the Destiny.DestinyTalentNodeState component.
    Destiny_DestinyTalentNodeStateNoMaterial int32 = 6

    // Destiny_DestinyTalentNodeStateNoGridLevel represents the NoGridLevel enum in the Destiny.DestinyTalentNodeState component.
    Destiny_DestinyTalentNodeStateNoGridLevel int32 = 7

    // Destiny_DestinyTalentNodeStateSwappingLocked represents the SwappingLocked enum in the Destiny.DestinyTalentNodeState component.
    Destiny_DestinyTalentNodeStateSwappingLocked int32 = 8

    // Destiny_DestinyTalentNodeStateMustSwap represents the MustSwap enum in the Destiny.DestinyTalentNodeState component.
    Destiny_DestinyTalentNodeStateMustSwap int32 = 9

    // Destiny_DestinyTalentNodeStateComplete represents the Complete enum in the Destiny.DestinyTalentNodeState component.
    Destiny_DestinyTalentNodeStateComplete int32 = 10

    // Destiny_DestinyTalentNodeStateUnknown represents the Unknown enum in the Destiny.DestinyTalentNodeState component.
    Destiny_DestinyTalentNodeStateUnknown int32 = 11

    // Destiny_DestinyTalentNodeStateCreationOnly represents the CreationOnly enum in the Destiny.DestinyTalentNodeState component.
    Destiny_DestinyTalentNodeStateCreationOnly int32 = 12

    // Destiny_DestinyTalentNodeStateHidden represents the Hidden enum in the Destiny.DestinyTalentNodeState component.
    Destiny_DestinyTalentNodeStateHidden int32 = 13
)
