// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Applications_Application struct {
    // Name.
    //
    // Name of the application
    Name string `json:"name"`

    // Origin.
    //
    // Value of the Origin header sent in requests generated by this application.
    Origin string `json:"origin"`

    // OverrideAuthorizeViewName.
    //
    // An optional override for the Authorize view name.
    OverrideAuthorizeViewName string `json:"overrideAuthorizeViewName"`

    // Scope.
    //
    // Permissions the application needs to work
    Scope int64 `json:"scope"`

    // ApplicationId.
    //
    // Unique ID assigned to the application
    ApplicationId int32 `json:"applicationId"`

    // CreationDate.
    //
    // Date the application was first added to our database.
    CreationDate string `json:"creationDate"`

    // StatusChanged.
    //
    // Date the application status last changed.
    StatusChanged string `json:"statusChanged"`

    // Team.
    //
    // List of team members who manage this application on Bungie.net. Will always consist of at least the application owner.
    Team []Applications_ApplicationDeveloper `json:"team"`

    // ApplicationType.
    //
    // 
    ApplicationType int32 `json:"applicationType"`

    // Link.
    //
    // Link to website for the application where a user can learn more about the app.
    Link string `json:"link"`

    // FirstPublished.
    //
    // Date the first time the application status entered the 'Public' status.
    FirstPublished string `json:"firstPublished"`

    // RedirectUrl.
    //
    // URL used to pass the user's authorization code to the application
    RedirectUrl string `json:"redirectUrl"`

    // Status.
    //
    // Current status of the application.
    Status int32 `json:"status"`
}
