// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type GroupsV2_GroupEditHistory struct {
    // MottoEditors.
    //
    // 
    MottoEditors int64 `json:"mottoEditors"`

    // Name.
    //
    // 
    Name string `json:"name"`

    // ClanCallsignEditors.
    //
    // 
    ClanCallsignEditors int64 `json:"clanCallsignEditors"`

    // Motto.
    //
    // 
    Motto string `json:"motto"`

    // EditDate.
    //
    // 
    EditDate string `json:"editDate"`

    // About.
    //
    // 
    About string `json:"about"`

    // AboutEditors.
    //
    // 
    AboutEditors int64 `json:"aboutEditors"`

    // ClanCallsign.
    //
    // 
    ClanCallsign string `json:"clanCallsign"`

    // NameEditors.
    //
    // 
    NameEditors int64 `json:"nameEditors"`

    // GroupEditors.
    //
    // 
    GroupEditors []User_UserInfoCard `json:"groupEditors"`

    // GroupId.
    //
    // 
    GroupId int64 `json:"groupId"`
}
