// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_Records_DestinyRecordIntervalRewards struct {
    // IntervalRewardItems.
    //
    // 
    IntervalRewardItems []Destiny_DestinyItemQuantity `json:"intervalRewardItems"`
}
