// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_Records_DestinyRecordExpirationBlock struct {
    // Description.
    //
    // 
    Description string `json:"description"`

    // HasExpiration.
    //
    // 
    HasExpiration bool `json:"hasExpiration"`

    // Icon.
    //
    // 
    Icon string `json:"icon"`
}
