// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_FireteamFinderOptionValueProviderTypeNone represents the None enum in the Destiny.FireteamFinderOptionValueProviderType component.
    Destiny_FireteamFinderOptionValueProviderTypeNone int32 = 0

    // Destiny_FireteamFinderOptionValueProviderTypeValues represents the Values enum in the Destiny.FireteamFinderOptionValueProviderType component.
    Destiny_FireteamFinderOptionValueProviderTypeValues int32 = 1

    // Destiny_FireteamFinderOptionValueProviderTypePlayerCount represents the PlayerCount enum in the Destiny.FireteamFinderOptionValueProviderType component.
    Destiny_FireteamFinderOptionValueProviderTypePlayerCount int32 = 2

    // Destiny_FireteamFinderOptionValueProviderTypeFireteamFinderLabels represents the FireteamFinderLabels enum in the Destiny.FireteamFinderOptionValueProviderType component.
    Destiny_FireteamFinderOptionValueProviderTypeFireteamFinderLabels int32 = 3

    // Destiny_FireteamFinderOptionValueProviderTypeFireteamFinderActivityGraph represents the FireteamFinderActivityGraph enum in the Destiny.FireteamFinderOptionValueProviderType component.
    Destiny_FireteamFinderOptionValueProviderTypeFireteamFinderActivityGraph int32 = 4
)
