// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type GroupsV2_GroupV2ClanInfoAndInvestment struct {
    // D2ClanProgressions.
    //
    // 
    D2ClanProgressions any `json:"d2ClanProgressions"`

    // ClanBannerData.
    //
    // 
    ClanBannerData GroupsV2_ClanBanner `json:"clanBannerData"`

    // ClanCallsign.
    //
    // 
    ClanCallsign string `json:"clanCallsign"`
}
