// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Challenges_DestinyChallengeStatus struct {
    // Objective.
    //
    // The progress - including completion status - of the active challenge.
    Objective any `json:"objective"`
}
