// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_DestinyArrangementRegionFilterDefinition struct {
    // ArrangementIndexByStatValue.
    //
    // 
    ArrangementIndexByStatValue any `json:"arrangementIndexByStatValue"`

    // ArtArrangementRegionHash.
    //
    // 
    ArtArrangementRegionHash uint32 `json:"artArrangementRegionHash"`

    // ArtArrangementRegionIndex.
    //
    // 
    ArtArrangementRegionIndex int32 `json:"artArrangementRegionIndex"`

    // StatHash.
    //
    // 
    StatHash uint32 `json:"statHash"`
}
