// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type DestinyBaseItemComponentSetOfint32 struct {
    // Objectives.
    //
    // 
    Objectives any `json:"objectives"`

    // Perks.
    //
    // 
    Perks any `json:"perks"`
}
