// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type GroupsV2_GroupMembership struct {
    // Group.
    //
    // 
    Group GroupsV2_GroupV2 `json:"group"`

    // Member.
    //
    // 
    Member GroupsV2_GroupMember `json:"member"`
}
