// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Responses_DestinyItemResponse struct {
    // Item.
    //
    // Common data for the item relevant to its non-instanced properties.
    //
    // COMPONENT TYPE: ItemCommonData
    Item any `json:"item"`

    // PlugObjectives.
    //
    // Information about objectives on Plugs for a given item. See the component's documentation for more info.
    //
    // COMPONENT TYPE: ItemPlugObjectives
    PlugObjectives any `json:"plugObjectives"`

    // ReusablePlugs.
    //
    // Information about the Reusable Plugs for sockets on an item. These are plugs that you can insert into the given socket regardless of if you actually own an instance of that plug: they are logic-driven plugs rather than inventory-driven.
    //
    //  These may need to be combined with Plug Set component data to get a full picture of available plugs on a given socket.
    //
    //  COMPONENT TYPE: ItemReusablePlugs
    ReusablePlugs any `json:"reusablePlugs"`

    // Sockets.
    //
    // Information about the sockets of the item: which are currently active, what potential sockets you could have and the stats/abilities/perks you can gain from them.
    //
    // COMPONENT TYPE: ItemSockets
    Sockets any `json:"sockets"`

    // Stats.
    //
    // Information about the computed stats of the item: power, defense, etc...
    //
    // COMPONENT TYPE: ItemStats
    Stats any `json:"stats"`

    // TalentGrid.
    //
    // Information about the talent grid attached to the item. Talent nodes can provide a variety of benefits and abilities, and in Destiny 2 are used almost exclusively for the character's "Builds".
    //
    // COMPONENT TYPE: ItemTalentGrids
    TalentGrid any `json:"talentGrid"`

    // Instance.
    //
    // Basic instance data for the item.
    //
    // COMPONENT TYPE: ItemInstances
    Instance any `json:"instance"`

    // Objectives.
    //
    // Information specifically about the item's objectives.
    //
    // COMPONENT TYPE: ItemObjectives
    Objectives any `json:"objectives"`

    // CharacterId.
    //
    // If the item is on a character, this will return the ID of the character that is holding the item.
    CharacterId int64 `json:"characterId"`

    // Perks.
    //
    // Information specifically about the perks currently active on the item.
    //
    // COMPONENT TYPE: ItemPerks
    Perks any `json:"perks"`

    // RenderData.
    //
    // Information about how to render the item in 3D.
    //
    // COMPONENT TYPE: ItemRenderData
    RenderData any `json:"renderData"`
}
