// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_HistoricalStats_DestinyHistoricalStatsByPeriod struct {
    // AllTime.
    //
    // 
    AllTime any `json:"allTime"`

    // AllTimeTier1.
    //
    // 
    AllTimeTier1 any `json:"allTimeTier1"`

    // AllTimeTier2.
    //
    // 
    AllTimeTier2 any `json:"allTimeTier2"`

    // AllTimeTier3.
    //
    // 
    AllTimeTier3 any `json:"allTimeTier3"`

    // Daily.
    //
    // 
    Daily []Destiny_HistoricalStats_DestinyHistoricalStatsPeriodGroup `json:"daily"`

    // Monthly.
    //
    // 
    Monthly []Destiny_HistoricalStats_DestinyHistoricalStatsPeriodGroup `json:"monthly"`
}
