// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_DestinyRecordValueStyleInteger represents the Integer enum in the Destiny.DestinyRecordValueStyle component.
    Destiny_DestinyRecordValueStyleInteger int32 = 0

    // Destiny_DestinyRecordValueStylePercentage represents the Percentage enum in the Destiny.DestinyRecordValueStyle component.
    Destiny_DestinyRecordValueStylePercentage int32 = 1

    // Destiny_DestinyRecordValueStyleMilliseconds represents the Milliseconds enum in the Destiny.DestinyRecordValueStyle component.
    Destiny_DestinyRecordValueStyleMilliseconds int32 = 2

    // Destiny_DestinyRecordValueStyleBoolean represents the Boolean enum in the Destiny.DestinyRecordValueStyle component.
    Destiny_DestinyRecordValueStyleBoolean int32 = 3

    // Destiny_DestinyRecordValueStyleDecimal represents the Decimal enum in the Destiny.DestinyRecordValueStyle component.
    Destiny_DestinyRecordValueStyleDecimal int32 = 4
)
