// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type DestinyVendorItemComponentSetOfint32 struct {
    // Instances.
    //
    // 
    Instances DictionaryComponentResponseOfint32AndDestinyItemInstanceComponent `json:"instances"`

    // ItemComponents.
    //
    // 
    ItemComponents DictionaryComponentResponseOfint32AndDestinyItemComponent `json:"itemComponents"`

    // Objectives.
    //
    // 
    Objectives DictionaryComponentResponseOfint32AndDestinyItemObjectivesComponent `json:"objectives"`

    // Perks.
    //
    // 
    Perks DictionaryComponentResponseOfint32AndDestinyItemPerksComponent `json:"perks"`

    // PlugObjectives.
    //
    // 
    PlugObjectives DictionaryComponentResponseOfint32AndDestinyItemPlugObjectivesComponent `json:"plugObjectives"`

    // PlugStates.
    //
    // 
    PlugStates DictionaryComponentResponseOfuint32AndDestinyItemPlugComponent `json:"plugStates"`

    // RenderData.
    //
    // 
    RenderData DictionaryComponentResponseOfint32AndDestinyItemRenderComponent `json:"renderData"`

    // ReusablePlugs.
    //
    // 
    ReusablePlugs DictionaryComponentResponseOfint32AndDestinyItemReusablePlugsComponent `json:"reusablePlugs"`

    // Sockets.
    //
    // 
    Sockets DictionaryComponentResponseOfint32AndDestinyItemSocketsComponent `json:"sockets"`

    // Stats.
    //
    // 
    Stats DictionaryComponentResponseOfint32AndDestinyItemStatsComponent `json:"stats"`

    // TalentGrids.
    //
    // 
    TalentGrids DictionaryComponentResponseOfint32AndDestinyItemTalentGridComponent `json:"talentGrids"`
}
