// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_VendorItemStatusSuccess represents the Success enum in the Destiny.VendorItemStatus component.
    Destiny_VendorItemStatusSuccess int32 = 0

    // Destiny_VendorItemStatusNoInventorySpace represents the NoInventorySpace enum in the Destiny.VendorItemStatus component.
    Destiny_VendorItemStatusNoInventorySpace int32 = 1

    // Destiny_VendorItemStatusNoFunds represents the NoFunds enum in the Destiny.VendorItemStatus component.
    Destiny_VendorItemStatusNoFunds int32 = 2

    // Destiny_VendorItemStatusNoProgression represents the NoProgression enum in the Destiny.VendorItemStatus component.
    Destiny_VendorItemStatusNoProgression int32 = 4

    // Destiny_VendorItemStatusNoUnlock represents the NoUnlock enum in the Destiny.VendorItemStatus component.
    Destiny_VendorItemStatusNoUnlock int32 = 8

    // Destiny_VendorItemStatusNoQuantity represents the NoQuantity enum in the Destiny.VendorItemStatus component.
    Destiny_VendorItemStatusNoQuantity int32 = 16

    // Destiny_VendorItemStatusOutsidePurchaseWindow represents the OutsidePurchaseWindow enum in the Destiny.VendorItemStatus component.
    Destiny_VendorItemStatusOutsidePurchaseWindow int32 = 32

    // Destiny_VendorItemStatusNotAvailable represents the NotAvailable enum in the Destiny.VendorItemStatus component.
    Destiny_VendorItemStatusNotAvailable int32 = 64

    // Destiny_VendorItemStatusUniquenessViolation represents the UniquenessViolation enum in the Destiny.VendorItemStatus component.
    Destiny_VendorItemStatusUniquenessViolation int32 = 128

    // Destiny_VendorItemStatusUnknownError represents the UnknownError enum in the Destiny.VendorItemStatus component.
    Destiny_VendorItemStatusUnknownError int32 = 256

    // Destiny_VendorItemStatusAlreadySelling represents the AlreadySelling enum in the Destiny.VendorItemStatus component.
    Destiny_VendorItemStatusAlreadySelling int32 = 512

    // Destiny_VendorItemStatusUnsellable represents the Unsellable enum in the Destiny.VendorItemStatus component.
    Destiny_VendorItemStatusUnsellable int32 = 1024

    // Destiny_VendorItemStatusSellingInhibited represents the SellingInhibited enum in the Destiny.VendorItemStatus component.
    Destiny_VendorItemStatusSellingInhibited int32 = 2048

    // Destiny_VendorItemStatusAlreadyOwned represents the AlreadyOwned enum in the Destiny.VendorItemStatus component.
    Destiny_VendorItemStatusAlreadyOwned int32 = 4096

    // Destiny_VendorItemStatusDisplayOnly represents the DisplayOnly enum in the Destiny.VendorItemStatus component.
    Destiny_VendorItemStatusDisplayOnly int32 = 8192
)
