// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Ignores_IgnoreResponse struct {
    // IgnoreFlags.
    //
    // 
    IgnoreFlags int32 `json:"ignoreFlags"`

    // IsIgnored.
    //
    // 
    IsIgnored bool `json:"isIgnored"`
}
