// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_DestinyProgressionResetEntry struct {
    // Resets.
    //
    // 
    Resets int32 `json:"resets"`

    // Season.
    //
    // 
    Season int32 `json:"season"`
}
