// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type User_EmailViewDefinitionSetting struct {
    // Localization.
    //
    // A dictionary of localized text for the EMail setting, keyed by the locale.
    Localization any `json:"localization"`

    // Name.
    //
    // The identifier for this UI Setting, which can be used to relate it to custom strings or other data as desired.
    Name string `json:"name"`

    // OptInAggregateValue.
    //
    // The OptInFlags value to set or clear if this setting is set or cleared in the UI. It is the aggregate of all underlying opt-in flags related to this setting.
    OptInAggregateValue int64 `json:"optInAggregateValue"`

    // SetByDefault.
    //
    // If true, this setting should be set by default if the user hasn't chosen whether it's set or cleared yet.
    SetByDefault bool `json:"setByDefault"`

    // Subscriptions.
    //
    // The subscriptions to show as children of this setting, if any.
    Subscriptions []User_EmailSubscriptionDefinition `json:"subscriptions"`
}
