// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Forums_ForumFlagsEnumNone represents the None enum in the Forums.ForumFlagsEnum component.
    Forums_ForumFlagsEnumNone int32 = 0

    // Forums_ForumFlagsEnumBungieStaffPost represents the BungieStaffPost enum in the Forums.ForumFlagsEnum component.
    Forums_ForumFlagsEnumBungieStaffPost int32 = 1

    // Forums_ForumFlagsEnumForumNinjaPost represents the ForumNinjaPost enum in the Forums.ForumFlagsEnum component.
    Forums_ForumFlagsEnumForumNinjaPost int32 = 2

    // Forums_ForumFlagsEnumForumMentorPost represents the ForumMentorPost enum in the Forums.ForumFlagsEnum component.
    Forums_ForumFlagsEnumForumMentorPost int32 = 4

    // Forums_ForumFlagsEnumTopicBungieStaffPosted represents the TopicBungieStaffPosted enum in the Forums.ForumFlagsEnum component.
    Forums_ForumFlagsEnumTopicBungieStaffPosted int32 = 8

    // Forums_ForumFlagsEnumTopicBungieVolunteerPosted represents the TopicBungieVolunteerPosted enum in the Forums.ForumFlagsEnum component.
    Forums_ForumFlagsEnumTopicBungieVolunteerPosted int32 = 16

    // Forums_ForumFlagsEnumQuestionAnsweredByBungie represents the QuestionAnsweredByBungie enum in the Forums.ForumFlagsEnum component.
    Forums_ForumFlagsEnumQuestionAnsweredByBungie int32 = 32

    // Forums_ForumFlagsEnumQuestionAnsweredByNinja represents the QuestionAnsweredByNinja enum in the Forums.ForumFlagsEnum component.
    Forums_ForumFlagsEnumQuestionAnsweredByNinja int32 = 64

    // Forums_ForumFlagsEnumCommunityContent represents the CommunityContent enum in the Forums.ForumFlagsEnum component.
    Forums_ForumFlagsEnumCommunityContent int32 = 128
)
