// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_ItemStateNone represents the None enum in the Destiny.ItemState component.
    Destiny_ItemStateNone int32 = 0

    // Destiny_ItemStateLocked represents the Locked enum in the Destiny.ItemState component.
    //
    // If this bit is set, the item has been "locked" by the user and cannot be deleted. You may want to represent this visually with a "lock" icon.
    Destiny_ItemStateLocked int32 = 1

    // Destiny_ItemStateTracked represents the Tracked enum in the Destiny.ItemState component.
    //
    // If this bit is set, the item is a quest that's being tracked by the user. You may want a visual indicator to show that this is a tracked quest.
    Destiny_ItemStateTracked int32 = 2

    // Destiny_ItemStateMasterwork represents the Masterwork enum in the Destiny.ItemState component.
    //
    // If this bit is set, the item has a Masterwork plug inserted. This usually coincides with having a special "glowing" effect applied to the item's icon.
    Destiny_ItemStateMasterwork int32 = 4

    // Destiny_ItemStateCrafted represents the Crafted enum in the Destiny.ItemState component.
    //
    // If this bit is set, the item has been 'crafted' by the player. You may want to represent this visually with a "crafted" icon overlay.
    Destiny_ItemStateCrafted int32 = 8

    // Destiny_ItemStateHighlightedObjective represents the HighlightedObjective enum in the Destiny.ItemState component.
    //
    // If this bit is set, the item has a 'highlighted' objective. You may want to represent this with an orange-red icon border color.
    Destiny_ItemStateHighlightedObjective int32 = 16
)
