// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Forum_CommunityContentSortModeTrending represents the Trending enum in the Forum.CommunityContentSortMode component.
    Forum_CommunityContentSortModeTrending byte = 0

    // Forum_CommunityContentSortModeLatest represents the Latest enum in the Forum.CommunityContentSortMode component.
    Forum_CommunityContentSortModeLatest byte = 1

    // Forum_CommunityContentSortModeHighestRated represents the HighestRated enum in the Forum.CommunityContentSortMode component.
    Forum_CommunityContentSortModeHighestRated byte = 2
)
