// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Components_PlugSets_DestinyPlugSetsComponent struct {
    // Plugs.
    //
    // The shared list of plugs for each relevant PlugSet, keyed by the hash identifier of the PlugSet (DestinyPlugSetDefinition).
    Plugs map[uint32][]Destiny_Sockets_DestinyItemPlug `json:"plugs"`
}
