// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Requests_Actions_DestinyInsertPlugsActionRequest struct {
    // CharacterId.
    //
    // 
    CharacterId int64 `json:"characterId"`

    // ItemInstanceId.
    //
    // The instance ID of the item having a plug inserted. Only instanced items can have sockets.
    ItemInstanceId int64 `json:"itemInstanceId"`

    // MembershipType.
    //
    // 
    MembershipType int32 `json:"membershipType"`

    // Plug.
    //
    // The plugs being inserted.
    Plug any `json:"plug"`

    // ActionToken.
    //
    // Action token provided by the AwaGetActionToken API call.
    ActionToken string `json:"actionToken"`
}
