// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_SocketTypeActionTypeInsertPlug represents the InsertPlug enum in the Destiny.SocketTypeActionType component.
    Destiny_SocketTypeActionTypeInsertPlug int32 = 0

    // Destiny_SocketTypeActionTypeInfuseItem represents the InfuseItem enum in the Destiny.SocketTypeActionType component.
    Destiny_SocketTypeActionTypeInfuseItem int32 = 1

    // Destiny_SocketTypeActionTypeReinitializeSocket represents the ReinitializeSocket enum in the Destiny.SocketTypeActionType component.
    Destiny_SocketTypeActionTypeReinitializeSocket int32 = 2
)
