// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // FireteamFinder_DestinyFireteamFinderApplicationTypeUnknown represents the Unknown enum in the FireteamFinder.DestinyFireteamFinderApplicationType component.
    FireteamFinder_DestinyFireteamFinderApplicationTypeUnknown int32 = 0

    // FireteamFinder_DestinyFireteamFinderApplicationTypeCreator represents the Creator enum in the FireteamFinder.DestinyFireteamFinderApplicationType component.
    FireteamFinder_DestinyFireteamFinderApplicationTypeCreator int32 = 1

    // FireteamFinder_DestinyFireteamFinderApplicationTypeSearch represents the Search enum in the FireteamFinder.DestinyFireteamFinderApplicationType component.
    FireteamFinder_DestinyFireteamFinderApplicationTypeSearch int32 = 2

    // FireteamFinder_DestinyFireteamFinderApplicationTypeInvite represents the Invite enum in the FireteamFinder.DestinyFireteamFinderApplicationType component.
    FireteamFinder_DestinyFireteamFinderApplicationTypeInvite int32 = 3

    // FireteamFinder_DestinyFireteamFinderApplicationTypeFriend represents the Friend enum in the FireteamFinder.DestinyFireteamFinderApplicationType component.
    FireteamFinder_DestinyFireteamFinderApplicationTypeFriend int32 = 4

    // FireteamFinder_DestinyFireteamFinderApplicationTypeEncounter represents the Encounter enum in the FireteamFinder.DestinyFireteamFinderApplicationType component.
    FireteamFinder_DestinyFireteamFinderApplicationTypeEncounter int32 = 5

    // FireteamFinder_DestinyFireteamFinderApplicationTypePublic represents the Public enum in the FireteamFinder.DestinyFireteamFinderApplicationType component.
    FireteamFinder_DestinyFireteamFinderApplicationTypePublic int32 = 6
)
