// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_HistoricalStats_DestinyAggregateActivityStats struct {
    // ActivityHash.
    //
    // Hash ID that can be looked up in the DestinyActivityTable.
    ActivityHash uint32 `json:"activityHash"`

    // Values.
    //
    // Collection of stats for the player in this activity.
    Values any `json:"values"`
}
