// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type GroupsV2_GroupV2Card struct {
    // Theme.
    //
    // 
    Theme string `json:"theme"`

    // About.
    //
    // 
    About string `json:"about"`

    // AvatarPath.
    //
    // 
    AvatarPath string `json:"avatarPath"`

    // Capabilities.
    //
    // 
    Capabilities int32 `json:"capabilities"`

    // GroupId.
    //
    // 
    GroupId int64 `json:"groupId"`

    // Locale.
    //
    // 
    Locale string `json:"locale"`

    // Name.
    //
    // 
    Name string `json:"name"`

    // MemberCount.
    //
    // 
    MemberCount int32 `json:"memberCount"`

    // MembershipOption.
    //
    // 
    MembershipOption int32 `json:"membershipOption"`

    // RemoteGroupId.
    //
    // 
    RemoteGroupId int64 `json:"remoteGroupId"`

    // GroupType.
    //
    // 
    GroupType int32 `json:"groupType"`

    // Motto.
    //
    // 
    Motto string `json:"motto"`

    // ClanInfo.
    //
    // This contract contains clan-specific group information. It does not include any investment data.
    ClanInfo GroupsV2_GroupV2ClanInfo `json:"clanInfo"`

    // CreationDate.
    //
    // 
    CreationDate string `json:"creationDate"`
}
