// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Artifacts_DestinyArtifactCharacterScoped struct {
    // ArtifactHash.
    //
    // 
    ArtifactHash uint32 `json:"artifactHash"`

    // PointsUsed.
    //
    // 
    PointsUsed int32 `json:"pointsUsed"`

    // ResetCount.
    //
    // 
    ResetCount int32 `json:"resetCount"`

    // Tiers.
    //
    // 
    Tiers []Destiny_Artifacts_DestinyArtifactTier `json:"tiers"`
}
