// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Activities_DestinyPublicActivityStatus struct {
    // ChallengeObjectiveHashes.
    //
    // Active Challenges for the activity, if any - represented as hashes for DestinyObjectiveDefinitions.
    ChallengeObjectiveHashes []uint32 `json:"challengeObjectiveHashes"`

    // ModifierHashes.
    //
    // The active modifiers on this activity, if any - represented as hashes for DestinyActivityModifierDefinitions.
    ModifierHashes []uint32 `json:"modifierHashes"`

    // RewardTooltipItems.
    //
    // If the activity itself provides any specific "mock" rewards, this will be the items and their quantity.
    //
    // Why "mock", you ask? Because these are the rewards as they are represented in the tooltip of the Activity.
    //
    // These are often pointers to fake items that look good in a tooltip, but represent an abstract concept of what you will get for a reward rather than the specific items you may obtain.
    RewardTooltipItems []Destiny_DestinyItemQuantity `json:"rewardTooltipItems"`
}
