// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type GroupsV2_GroupBan struct {
    // BungieNetUserInfo.
    //
    // This contract supplies basic information commonly used to display a minimal amount of information about a user. Take care to not add more properties here unless the property applies in all (or at least the majority) of the situations where UserInfoCard is used. Avoid adding game specific or platform specific details here. In cases where UserInfoCard is a subset of the data needed in a contract, use UserInfoCard as a property of other contracts.
    BungieNetUserInfo User_UserInfoCard `json:"bungieNetUserInfo"`

    // Comment.
    //
    // 
    Comment string `json:"comment"`

    // CreatedBy.
    //
    // This contract supplies basic information commonly used to display a minimal amount of information about a user. Take care to not add more properties here unless the property applies in all (or at least the majority) of the situations where UserInfoCard is used. Avoid adding game specific or platform specific details here. In cases where UserInfoCard is a subset of the data needed in a contract, use UserInfoCard as a property of other contracts.
    CreatedBy User_UserInfoCard `json:"createdBy"`

    // DateBanned.
    //
    // 
    DateBanned string `json:"dateBanned"`

    // DateExpires.
    //
    // 
    DateExpires string `json:"dateExpires"`

    // DestinyUserInfo.
    //
    // 
    DestinyUserInfo GroupsV2_GroupUserInfoCard `json:"destinyUserInfo"`

    // GroupId.
    //
    // 
    GroupId int64 `json:"groupId"`

    // LastModifiedBy.
    //
    // This contract supplies basic information commonly used to display a minimal amount of information about a user. Take care to not add more properties here unless the property applies in all (or at least the majority) of the situations where UserInfoCard is used. Avoid adding game specific or platform specific details here. In cases where UserInfoCard is a subset of the data needed in a contract, use UserInfoCard as a property of other contracts.
    LastModifiedBy User_UserInfoCard `json:"lastModifiedBy"`
}
