// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // FireteamFinder_DestinyFireteamFinderOfferStateUnknown represents the Unknown enum in the FireteamFinder.DestinyFireteamFinderOfferState component.
    FireteamFinder_DestinyFireteamFinderOfferStateUnknown int32 = 0

    // FireteamFinder_DestinyFireteamFinderOfferStatePending represents the Pending enum in the FireteamFinder.DestinyFireteamFinderOfferState component.
    FireteamFinder_DestinyFireteamFinderOfferStatePending int32 = 1

    // FireteamFinder_DestinyFireteamFinderOfferStateAccepted represents the Accepted enum in the FireteamFinder.DestinyFireteamFinderOfferState component.
    FireteamFinder_DestinyFireteamFinderOfferStateAccepted int32 = 2

    // FireteamFinder_DestinyFireteamFinderOfferStateRejected represents the Rejected enum in the FireteamFinder.DestinyFireteamFinderOfferState component.
    FireteamFinder_DestinyFireteamFinderOfferStateRejected int32 = 3

    // FireteamFinder_DestinyFireteamFinderOfferStateDeleted represents the Deleted enum in the FireteamFinder.DestinyFireteamFinderOfferState component.
    FireteamFinder_DestinyFireteamFinderOfferStateDeleted int32 = 4

    // FireteamFinder_DestinyFireteamFinderOfferStateExpired represents the Expired enum in the FireteamFinder.DestinyFireteamFinderOfferState component.
    FireteamFinder_DestinyFireteamFinderOfferStateExpired int32 = 5
)
