// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_Collectibles_DestinyCollectibleStateBlock struct {
    // ObscuredOverrideItemHash.
    //
    // 
    ObscuredOverrideItemHash uint32 `json:"obscuredOverrideItemHash"`

    // Requirements.
    //
    // Presentation nodes can be restricted by various requirements. This defines the rules of those requirements, and the message(s) to be shown if these requirements aren't met.
    Requirements Destiny_Definitions_Presentation_DestinyPresentationNodeRequirementsBlock `json:"requirements"`
}
