// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type FireteamFinder_DestinyFireteamFinderGetPlayerApplicationsResponse struct {
    // NextPageToken.
    //
    // String token to request next page of results.
    NextPageToken string `json:"nextPageToken"`

    // Applications.
    //
    // All applications that this player has sent.
    Applications []FireteamFinder_DestinyFireteamFinderApplication `json:"applications"`
}
