// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type FireteamFinder_DestinyFireteamFinderListingFilter struct {
    // MatchType.
    //
    // 
    MatchType int `json:"matchType"`

    // RangeType.
    //
    // 
    RangeType int `json:"rangeType"`

    // ListingValue.
    //
    // 
    ListingValue any `json:"listingValue"`
}
