// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type GroupsV2_GroupPotentialMembership struct {
    // Group.
    //
    // 
    Group any `json:"group"`

    // Member.
    //
    // 
    Member any `json:"member"`
}
