// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_DestinyItemCraftingBlockDefinition struct {
    // RequiredSocketTypeHashes.
    //
    // A list of socket type hashes that describes which sockets are required for crafting with this recipe.
    RequiredSocketTypeHashes []any `json:"requiredSocketTypeHashes"`

    // BaseMaterialRequirements.
    //
    // A reference to the base material requirements for crafting with this recipe.
    BaseMaterialRequirements uint32 `json:"baseMaterialRequirements"`

    // BonusPlugs.
    //
    // A list of 'bonus' socket plugs that may be available if certain requirements are met.
    BonusPlugs []Destiny_Definitions_DestinyItemCraftingBlockBonusPlugDefinition `json:"bonusPlugs"`

    // FailedRequirementStrings.
    //
    // 
    FailedRequirementStrings []any `json:"failedRequirementStrings"`

    // OutputItemHash.
    //
    // A reference to the item definition that is created when crafting with this 'recipe' item.
    OutputItemHash uint32 `json:"outputItemHash"`
}
