// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_DestinyObjectiveDefinition struct {
    // AllowNegativeValue.
    //
    // If true, the value is allowed to go negative.
    AllowNegativeValue bool `json:"allowNegativeValue"`

    // AllowOvercompletion.
    //
    // If True, the progress will continue even beyond the point where the objective met its minimum completion requirements. Your UI will have to accommodate it.
    AllowOvercompletion bool `json:"allowOvercompletion"`

    // AllowValueChangeWhenCompleted.
    //
    // If true, you can effectively "un-complete" this objective if you lose progress after crossing the completion threshold. 
    //
    // If False, once you complete the task it will remain completed forever by locking the value.
    AllowValueChangeWhenCompleted bool `json:"allowValueChangeWhenCompleted"`

    // CompletedValueStyle.
    //
    // The style to use when the objective is completed.
    CompletedValueStyle int32 `json:"completedValueStyle"`

    // CompletionValue.
    //
    // The value that the unlock value defined in unlockValueHash must reach in order for the objective to be considered Completed. Used in calculating progress and completion status.
    CompletionValue int32 `json:"completionValue"`

    // DisplayProperties.
    //
    // Ideally, this should tell you what your task is. I'm not going to lie to you though. Sometimes this doesn't have useful information at all. Which sucks, but there's nothing either of us can do about it.
    DisplayProperties any `json:"displayProperties"`

    // Hash.
    //
    // The unique identifier for this entity. Guaranteed to be unique for the type of entity, but not globally.
    //
    // When entities refer to each other in Destiny content, it is this hash that they are referring to.
    Hash uint32 `json:"hash"`

    // InProgressValueStyle.
    //
    // The style to use when the objective is still in progress.
    InProgressValueStyle int32 `json:"inProgressValueStyle"`

    // Index.
    //
    // The index of the entity as it was found in the investment tables.
    Index int32 `json:"index"`

    // IsCountingDownward.
    //
    // If true, completion means having an unlock value less than or equal to the completionValue.
    //
    // If False, completion means having an unlock value greater than or equal to the completionValue.
    IsCountingDownward bool `json:"isCountingDownward"`

    // LocationHash.
    //
    // OPTIONAL: a hash identifier for the location at which this objective must be accomplished, if there is a location defined. Look up the DestinyLocationDefinition for this hash for that additional location info.
    LocationHash uint32 `json:"locationHash"`

    // MinimumVisibilityThreshold.
    //
    // If nonzero, this is the minimum value at which the objective's progression should be shown. Otherwise, don't show it yet.
    MinimumVisibilityThreshold int32 `json:"minimumVisibilityThreshold"`

    // Perks.
    //
    // If this objective enables Perks intrinsically, the conditions for that enabling are defined here.
    Perks any `json:"perks"`

    // ProgressDescription.
    //
    // Text to describe the progress bar.
    ProgressDescription string `json:"progressDescription"`

    // Redacted.
    //
    // If this is true, then there is an entity with this identifier/type combination, but BNet is not yet allowed to show it. Sorry!
    Redacted bool `json:"redacted"`

    // Scope.
    //
    // A shortcut for determining the most restrictive gating that this Objective is set to use. This includes both the dynamic determination of progress and of completion values. See the DestinyGatingScope enum's documentation for more details.
    Scope int32 `json:"scope"`

    // ShowValueOnComplete.
    //
    // If True, you should continue showing the progression value in the UI after it's complete. I mean, we already do that in BNet anyways, but if you want to be better behaved than us you could honor this flag.
    ShowValueOnComplete bool `json:"showValueOnComplete"`

    // Stats.
    //
    // If this objective enables modifications on a player's stats intrinsically, the conditions are defined here.
    Stats any `json:"stats"`

    // UiLabel.
    //
    // Objectives can have arbitrary UI-defined identifiers that define the style applied to objectives. For convenience, known UI labels will be defined in the uiStyle enum value.
    UiLabel string `json:"uiLabel"`

    // UiStyle.
    //
    // If the objective has a known UI label value, this property will represent it.
    UiStyle int32 `json:"uiStyle"`

    // ValueStyle.
    //
    // The UI style applied to the objective. It's an enum, take a look at DestinyUnlockValueUIStyle for details of the possible styles. Use this info as you wish to customize your UI.
    //
    // DEPRECATED: This is no longer populated by Destiny 2 game content. Please use inProgressValueStyle and completedValueStyle instead.
    ValueStyle int32 `json:"valueStyle"`
}
