// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Applications_DeveloperRoleNone represents the None enum in the Applications.DeveloperRole component.
    Applications_DeveloperRoleNone int32 = 0

    // Applications_DeveloperRoleOwner represents the Owner enum in the Applications.DeveloperRole component.
    Applications_DeveloperRoleOwner int32 = 1

    // Applications_DeveloperRoleTeamMember represents the TeamMember enum in the Applications.DeveloperRole component.
    Applications_DeveloperRoleTeamMember int32 = 2
)
