// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Character_DestinyCharacterCustomization struct {
    // Face.
    //
    // 
    Face uint32 `json:"face"`

    // HairIndex.
    //
    // 
    HairIndex int32 `json:"hairIndex"`

    // LipColor.
    //
    // 
    LipColor uint32 `json:"lipColor"`

    // WearHelmet.
    //
    // 
    WearHelmet bool `json:"wearHelmet"`

    // DecalColor.
    //
    // 
    DecalColor uint32 `json:"decalColor"`

    // DecalIndex.
    //
    // 
    DecalIndex int32 `json:"decalIndex"`

    // EyeColor.
    //
    // 
    EyeColor uint32 `json:"eyeColor"`

    // FeatureIndex.
    //
    // 
    FeatureIndex int32 `json:"featureIndex"`

    // HairColors.
    //
    // 
    HairColors []any `json:"hairColors"`

    // FeatureColors.
    //
    // 
    FeatureColors []any `json:"featureColors"`

    // Personality.
    //
    // 
    Personality uint32 `json:"personality"`

    // SkinColor.
    //
    // 
    SkinColor uint32 `json:"skinColor"`
}
