// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type User_UserMembership struct {
    // BungieGlobalDisplayName.
    //
    // The bungie global display name, if set.
    BungieGlobalDisplayName string `json:"bungieGlobalDisplayName"`

    // BungieGlobalDisplayNameCode.
    //
    // The bungie global display name code, if set.
    BungieGlobalDisplayNameCode int16 `json:"bungieGlobalDisplayNameCode"`

    // DisplayName.
    //
    // Display Name the player has chosen for themselves. The display name is optional when the data type is used as input to a platform API.
    DisplayName string `json:"displayName"`

    // MembershipId.
    //
    // Membership ID as they user is known in the Accounts service
    MembershipId int64 `json:"membershipId"`

    // MembershipType.
    //
    // Type of the membership. Not necessarily the native type.
    MembershipType int32 `json:"membershipType"`
}
