// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Tokens_BungieRewardDisplay struct {
    // RewardDisplayProperties.
    //
    // 
    RewardDisplayProperties any `json:"RewardDisplayProperties"`

    // UserRewardAvailabilityModel.
    //
    // 
    UserRewardAvailabilityModel any `json:"UserRewardAvailabilityModel"`

    // ObjectiveDisplayProperties.
    //
    // 
    ObjectiveDisplayProperties any `json:"ObjectiveDisplayProperties"`
}
