// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Components_Collectibles_DestinyCollectiblesComponent struct {
    // CollectionBadgesRootNodeHash.
    //
    // The hash for the root presentation node definition of Collection Badges.
    CollectionBadgesRootNodeHash uint32 `json:"collectionBadgesRootNodeHash"`

    // CollectionCategoriesRootNodeHash.
    //
    // The hash for the root presentation node definition of Collection categories.
    CollectionCategoriesRootNodeHash uint32 `json:"collectionCategoriesRootNodeHash"`

    // Collectibles.
    //
    // 
    Collectibles any `json:"collectibles"`
}
