// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type GroupsV2_GroupNameSearchRequest struct {
    // GroupName.
    //
    // 
    GroupName string `json:"groupName"`

    // GroupType.
    //
    // 
    GroupType int32 `json:"groupType"`
}
