// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_FireteamFinderOptionControlTypeNone represents the None enum in the Destiny.FireteamFinderOptionControlType component.
    Destiny_FireteamFinderOptionControlTypeNone int32 = 0

    // Destiny_FireteamFinderOptionControlTypeValueCollection represents the ValueCollection enum in the Destiny.FireteamFinderOptionControlType component.
    Destiny_FireteamFinderOptionControlTypeValueCollection int32 = 1

    // Destiny_FireteamFinderOptionControlTypeRadioButton represents the RadioButton enum in the Destiny.FireteamFinderOptionControlType component.
    Destiny_FireteamFinderOptionControlTypeRadioButton int32 = 2
)
