// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_Items_DestinyDerivedItemCategoryDefinition struct {
    // CategoryDescription.
    //
    // The localized string for the category title. This will be something describing the items you can get as a group, or your likelihood/the quantity you'll get.
    CategoryDescription string `json:"categoryDescription"`

    // Items.
    //
    // This is the list of all of the items for this category and the basic properties we'll know about them.
    Items []Destiny_Definitions_Items_DestinyDerivedItemDefinition `json:"items"`
}
