// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_FireteamFinder_DestinyFireteamFinderOptionSettingsControl struct {
    // MaxSelectedItems.
    //
    // 
    MaxSelectedItems int32 `json:"maxSelectedItems"`

    // MinSelectedItems.
    //
    // 
    MinSelectedItems int32 `json:"minSelectedItems"`

    // Type.
    //
    // 
    Type int32 `json:"type"`
}
