// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Forum_ForumPostPopularityEmpty represents the Empty enum in the Forum.ForumPostPopularity component.
    Forum_ForumPostPopularityEmpty int32 = 0

    // Forum_ForumPostPopularityDefault represents the Default enum in the Forum.ForumPostPopularity component.
    Forum_ForumPostPopularityDefault int32 = 1

    // Forum_ForumPostPopularityDiscussed represents the Discussed enum in the Forum.ForumPostPopularity component.
    Forum_ForumPostPopularityDiscussed int32 = 2

    // Forum_ForumPostPopularityCoolStory represents the CoolStory enum in the Forum.ForumPostPopularity component.
    Forum_ForumPostPopularityCoolStory int32 = 3

    // Forum_ForumPostPopularityHeatingUp represents the HeatingUp enum in the Forum.ForumPostPopularity component.
    Forum_ForumPostPopularityHeatingUp int32 = 4

    // Forum_ForumPostPopularityHot represents the Hot enum in the Forum.ForumPostPopularity component.
    Forum_ForumPostPopularityHot int32 = 5
)
