// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type FireteamFinder_DestinyFireteamFinderSearchListingsByFiltersResponse struct {
    // Listings.
    //
    // 
    Listings []FireteamFinder_DestinyFireteamFinderListing `json:"listings"`

    // PageToken.
    //
    // 
    PageToken string `json:"pageToken"`
}
