// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_Seasons_DestinyEventCardImages struct {
    // CardCompleteWrapImagePath.
    //
    // 
    CardCompleteWrapImagePath string `json:"cardCompleteWrapImagePath"`

    // CardIncompleteImagePath.
    //
    // 
    CardIncompleteImagePath string `json:"cardIncompleteImagePath"`

    // ProgressIconImagePath.
    //
    // 
    ProgressIconImagePath string `json:"progressIconImagePath"`

    // ThemeBackgroundImagePath.
    //
    // 
    ThemeBackgroundImagePath string `json:"themeBackgroundImagePath"`

    // UnownedCardSleeveImagePath.
    //
    // 
    UnownedCardSleeveImagePath string `json:"unownedCardSleeveImagePath"`

    // UnownedCardSleeveWrapImagePath.
    //
    // 
    UnownedCardSleeveWrapImagePath string `json:"unownedCardSleeveWrapImagePath"`

    // CardCompleteImagePath.
    //
    // 
    CardCompleteImagePath string `json:"cardCompleteImagePath"`
}
