// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_Presentation_DestinyPresentationNodeChildrenBlock struct {
    // Metrics.
    //
    // 
    Metrics []Destiny_Definitions_Presentation_DestinyPresentationNodeMetricChildEntry `json:"metrics"`

    // PresentationNodes.
    //
    // 
    PresentationNodes []Destiny_Definitions_Presentation_DestinyPresentationNodeChildEntry `json:"presentationNodes"`

    // Records.
    //
    // 
    Records []Destiny_Definitions_Presentation_DestinyPresentationNodeRecordChildEntry `json:"records"`

    // Collectibles.
    //
    // 
    Collectibles []Destiny_Definitions_Presentation_DestinyPresentationNodeCollectibleChildEntry `json:"collectibles"`

    // Craftables.
    //
    // 
    Craftables []Destiny_Definitions_Presentation_DestinyPresentationNodeCraftableChildEntry `json:"craftables"`
}
