// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_Records_DestinyRecordIntervalBlock struct {
    // IntervalRewards.
    //
    // 
    IntervalRewards []Destiny_Definitions_Records_DestinyRecordIntervalRewards `json:"intervalRewards"`

    // OriginalObjectiveArrayInsertionIndex.
    //
    // 
    OriginalObjectiveArrayInsertionIndex int32 `json:"originalObjectiveArrayInsertionIndex"`

    // IntervalObjectives.
    //
    // 
    IntervalObjectives []Destiny_Definitions_Records_DestinyRecordIntervalObjective `json:"intervalObjectives"`
}
