// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // GroupsV2_GroupsForMemberFilterAll represents the All enum in the GroupsV2.GroupsForMemberFilter component.
    GroupsV2_GroupsForMemberFilterAll int32 = 0

    // GroupsV2_GroupsForMemberFilterFounded represents the Founded enum in the GroupsV2.GroupsForMemberFilter component.
    GroupsV2_GroupsForMemberFilterFounded int32 = 1

    // GroupsV2_GroupsForMemberFilterNonFounded represents the NonFounded enum in the GroupsV2.GroupsForMemberFilter component.
    GroupsV2_GroupsForMemberFilterNonFounded int32 = 2
)
