// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Content_Models_ContentPropertyDataTypeEnumNone represents the None enum in the Content.Models.ContentPropertyDataTypeEnum component.
    Content_Models_ContentPropertyDataTypeEnumNone int32 = 0

    // Content_Models_ContentPropertyDataTypeEnumPlaintext represents the Plaintext enum in the Content.Models.ContentPropertyDataTypeEnum component.
    Content_Models_ContentPropertyDataTypeEnumPlaintext int32 = 1

    // Content_Models_ContentPropertyDataTypeEnumHtml represents the Html enum in the Content.Models.ContentPropertyDataTypeEnum component.
    Content_Models_ContentPropertyDataTypeEnumHtml int32 = 2

    // Content_Models_ContentPropertyDataTypeEnumDropdown represents the Dropdown enum in the Content.Models.ContentPropertyDataTypeEnum component.
    Content_Models_ContentPropertyDataTypeEnumDropdown int32 = 3

    // Content_Models_ContentPropertyDataTypeEnumList represents the List enum in the Content.Models.ContentPropertyDataTypeEnum component.
    Content_Models_ContentPropertyDataTypeEnumList int32 = 4

    // Content_Models_ContentPropertyDataTypeEnumJson represents the Json enum in the Content.Models.ContentPropertyDataTypeEnum component.
    Content_Models_ContentPropertyDataTypeEnumJson int32 = 5

    // Content_Models_ContentPropertyDataTypeEnumContent represents the Content enum in the Content.Models.ContentPropertyDataTypeEnum component.
    Content_Models_ContentPropertyDataTypeEnumContent int32 = 6

    // Content_Models_ContentPropertyDataTypeEnumRepresentation represents the Representation enum in the Content.Models.ContentPropertyDataTypeEnum component.
    Content_Models_ContentPropertyDataTypeEnumRepresentation int32 = 7

    // Content_Models_ContentPropertyDataTypeEnumSet represents the Set enum in the Content.Models.ContentPropertyDataTypeEnum component.
    Content_Models_ContentPropertyDataTypeEnumSet int32 = 8

    // Content_Models_ContentPropertyDataTypeEnumFile represents the File enum in the Content.Models.ContentPropertyDataTypeEnum component.
    Content_Models_ContentPropertyDataTypeEnumFile int32 = 9

    // Content_Models_ContentPropertyDataTypeEnumFolderSet represents the FolderSet enum in the Content.Models.ContentPropertyDataTypeEnum component.
    Content_Models_ContentPropertyDataTypeEnumFolderSet int32 = 10

    // Content_Models_ContentPropertyDataTypeEnumDate represents the Date enum in the Content.Models.ContentPropertyDataTypeEnum component.
    Content_Models_ContentPropertyDataTypeEnumDate int32 = 11

    // Content_Models_ContentPropertyDataTypeEnumMultilinePlaintext represents the MultilinePlaintext enum in the Content.Models.ContentPropertyDataTypeEnum component.
    Content_Models_ContentPropertyDataTypeEnumMultilinePlaintext int32 = 12

    // Content_Models_ContentPropertyDataTypeEnumDestinyContent represents the DestinyContent enum in the Content.Models.ContentPropertyDataTypeEnum component.
    Content_Models_ContentPropertyDataTypeEnumDestinyContent int32 = 13

    // Content_Models_ContentPropertyDataTypeEnumColor represents the Color enum in the Content.Models.ContentPropertyDataTypeEnum component.
    Content_Models_ContentPropertyDataTypeEnumColor int32 = 14
)
