// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // GroupsV2_GroupApplicationResolveStateUnresolved represents the Unresolved enum in the GroupsV2.GroupApplicationResolveState component.
    GroupsV2_GroupApplicationResolveStateUnresolved int32 = 0

    // GroupsV2_GroupApplicationResolveStateAccepted represents the Accepted enum in the GroupsV2.GroupApplicationResolveState component.
    GroupsV2_GroupApplicationResolveStateAccepted int32 = 1

    // GroupsV2_GroupApplicationResolveStateDenied represents the Denied enum in the GroupsV2.GroupApplicationResolveState component.
    GroupsV2_GroupApplicationResolveStateDenied int32 = 2

    // GroupsV2_GroupApplicationResolveStateRescinded represents the Rescinded enum in the GroupsV2.GroupApplicationResolveState component.
    GroupsV2_GroupApplicationResolveStateRescinded int32 = 3
)
