// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_DestinyVendorGroupReference struct {
    // VendorGroupHash.
    //
    // The DestinyVendorGroupDefinition to which this Vendor can belong.
    VendorGroupHash uint32 `json:"vendorGroupHash"`
}
