// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_Seasons_DestinySeasonActDefinition struct {
    // DisplayName.
    //
    // The name of the Act.
    DisplayName string `json:"displayName"`

    // RankCount.
    //
    // The number of ranks included in the Act.
    RankCount int32 `json:"rankCount"`

    // StartTime.
    //
    // The start time of the Act.
    StartTime string `json:"startTime"`
}
