// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // BungieCredentialTypeNone represents the None enum in the BungieCredentialType component.
    BungieCredentialTypeNone byte = 0

    // BungieCredentialTypeXuid represents the Xuid enum in the BungieCredentialType component.
    BungieCredentialTypeXuid byte = 1

    // BungieCredentialTypePsnid represents the Psnid enum in the BungieCredentialType component.
    BungieCredentialTypePsnid byte = 2

    // BungieCredentialTypeWlid represents the Wlid enum in the BungieCredentialType component.
    BungieCredentialTypeWlid byte = 3

    // BungieCredentialTypeFake represents the Fake enum in the BungieCredentialType component.
    BungieCredentialTypeFake byte = 4

    // BungieCredentialTypeFacebook represents the Facebook enum in the BungieCredentialType component.
    BungieCredentialTypeFacebook byte = 5

    // BungieCredentialTypeGoogle represents the Google enum in the BungieCredentialType component.
    BungieCredentialTypeGoogle byte = 8

    // BungieCredentialTypeWindows represents the Windows enum in the BungieCredentialType component.
    BungieCredentialTypeWindows byte = 9

    // BungieCredentialTypeDemonId represents the DemonId enum in the BungieCredentialType component.
    BungieCredentialTypeDemonId byte = 10

    // BungieCredentialTypeSteamId represents the SteamId enum in the BungieCredentialType component.
    BungieCredentialTypeSteamId byte = 12

    // BungieCredentialTypeBattleNetId represents the BattleNetId enum in the BungieCredentialType component.
    BungieCredentialTypeBattleNetId byte = 14

    // BungieCredentialTypeStadiaId represents the StadiaId enum in the BungieCredentialType component.
    BungieCredentialTypeStadiaId byte = 16

    // BungieCredentialTypeTwitchId represents the TwitchId enum in the BungieCredentialType component.
    BungieCredentialTypeTwitchId byte = 18

    // BungieCredentialTypeEgsId represents the EgsId enum in the BungieCredentialType component.
    BungieCredentialTypeEgsId byte = 20
)
