// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_DestinyPresentationDisplayStyleCategory represents the Category enum in the Destiny.DestinyPresentationDisplayStyle component.
    //
    // Display the item as a category, through which sub-items are filtered.
    Destiny_DestinyPresentationDisplayStyleCategory int32 = 0

    // Destiny_DestinyPresentationDisplayStyleBadge represents the Badge enum in the Destiny.DestinyPresentationDisplayStyle component.
    Destiny_DestinyPresentationDisplayStyleBadge int32 = 1

    // Destiny_DestinyPresentationDisplayStyleMedals represents the Medals enum in the Destiny.DestinyPresentationDisplayStyle component.
    Destiny_DestinyPresentationDisplayStyleMedals int32 = 2

    // Destiny_DestinyPresentationDisplayStyleCollectible represents the Collectible enum in the Destiny.DestinyPresentationDisplayStyle component.
    Destiny_DestinyPresentationDisplayStyleCollectible int32 = 3

    // Destiny_DestinyPresentationDisplayStyleRecord represents the Record enum in the Destiny.DestinyPresentationDisplayStyle component.
    Destiny_DestinyPresentationDisplayStyleRecord int32 = 4

    // Destiny_DestinyPresentationDisplayStyleSeasonalTriumph represents the SeasonalTriumph enum in the Destiny.DestinyPresentationDisplayStyle component.
    Destiny_DestinyPresentationDisplayStyleSeasonalTriumph int32 = 5

    // Destiny_DestinyPresentationDisplayStyleGuardianRank represents the GuardianRank enum in the Destiny.DestinyPresentationDisplayStyle component.
    Destiny_DestinyPresentationDisplayStyleGuardianRank int32 = 6

    // Destiny_DestinyPresentationDisplayStyleCategoryCollectibles represents the CategoryCollectibles enum in the Destiny.DestinyPresentationDisplayStyle component.
    Destiny_DestinyPresentationDisplayStyleCategoryCollectibles int32 = 7

    // Destiny_DestinyPresentationDisplayStyleCategoryCurrencies represents the CategoryCurrencies enum in the Destiny.DestinyPresentationDisplayStyle component.
    Destiny_DestinyPresentationDisplayStyleCategoryCurrencies int32 = 8

    // Destiny_DestinyPresentationDisplayStyleCategoryEmblems represents the CategoryEmblems enum in the Destiny.DestinyPresentationDisplayStyle component.
    Destiny_DestinyPresentationDisplayStyleCategoryEmblems int32 = 9

    // Destiny_DestinyPresentationDisplayStyleCategoryEmotes represents the CategoryEmotes enum in the Destiny.DestinyPresentationDisplayStyle component.
    Destiny_DestinyPresentationDisplayStyleCategoryEmotes int32 = 10

    // Destiny_DestinyPresentationDisplayStyleCategoryEngrams represents the CategoryEngrams enum in the Destiny.DestinyPresentationDisplayStyle component.
    Destiny_DestinyPresentationDisplayStyleCategoryEngrams int32 = 11

    // Destiny_DestinyPresentationDisplayStyleCategoryFinishers represents the CategoryFinishers enum in the Destiny.DestinyPresentationDisplayStyle component.
    Destiny_DestinyPresentationDisplayStyleCategoryFinishers int32 = 12

    // Destiny_DestinyPresentationDisplayStyleCategoryGhosts represents the CategoryGhosts enum in the Destiny.DestinyPresentationDisplayStyle component.
    Destiny_DestinyPresentationDisplayStyleCategoryGhosts int32 = 13

    // Destiny_DestinyPresentationDisplayStyleCategoryMisc represents the CategoryMisc enum in the Destiny.DestinyPresentationDisplayStyle component.
    Destiny_DestinyPresentationDisplayStyleCategoryMisc int32 = 14

    // Destiny_DestinyPresentationDisplayStyleCategoryMods represents the CategoryMods enum in the Destiny.DestinyPresentationDisplayStyle component.
    Destiny_DestinyPresentationDisplayStyleCategoryMods int32 = 15

    // Destiny_DestinyPresentationDisplayStyleCategoryOrnaments represents the CategoryOrnaments enum in the Destiny.DestinyPresentationDisplayStyle component.
    Destiny_DestinyPresentationDisplayStyleCategoryOrnaments int32 = 16

    // Destiny_DestinyPresentationDisplayStyleCategoryShaders represents the CategoryShaders enum in the Destiny.DestinyPresentationDisplayStyle component.
    Destiny_DestinyPresentationDisplayStyleCategoryShaders int32 = 17

    // Destiny_DestinyPresentationDisplayStyleCategoryShips represents the CategoryShips enum in the Destiny.DestinyPresentationDisplayStyle component.
    Destiny_DestinyPresentationDisplayStyleCategoryShips int32 = 18

    // Destiny_DestinyPresentationDisplayStyleCategorySpawnfx represents the CategorySpawnfx enum in the Destiny.DestinyPresentationDisplayStyle component.
    Destiny_DestinyPresentationDisplayStyleCategorySpawnfx int32 = 19

    // Destiny_DestinyPresentationDisplayStyleCategoryUpgradeMaterials represents the CategoryUpgradeMaterials enum in the Destiny.DestinyPresentationDisplayStyle component.
    Destiny_DestinyPresentationDisplayStyleCategoryUpgradeMaterials int32 = 20
)
