// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type FireteamFinder_DestinyFireteamFinderListingValue struct {
    // ValueType.
    //
    // 
    ValueType uint32 `json:"valueType"`

    // Values.
    //
    // 
    Values []any `json:"values"`
}
