// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_DestinyVendorCategoryOverlayDefinition struct {
    // ChoiceDescription.
    //
    // 
    ChoiceDescription string `json:"choiceDescription"`

    // CurrencyItemHash.
    //
    // If this overlay has a currency item that it features, this is said featured item.
    CurrencyItemHash *uint32 `json:"currencyItemHash"`

    // Description.
    //
    // 
    Description string `json:"description"`

    // Icon.
    //
    // 
    Icon string `json:"icon"`

    // Title.
    //
    // 
    Title string `json:"title"`
}
