// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type FireteamFinder_DestinyFireteamFinderRespondToApplicationResponse struct {
    // ApplicationId.
    //
    // 
    ApplicationId int64 `json:"applicationId"`

    // ApplicationRevision.
    //
    // 
    ApplicationRevision int32 `json:"applicationRevision"`
}
