// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Forum_PostResponse struct {
    // IgnoreStatus.
    //
    // 
    IgnoreStatus Ignores_IgnoreResponse `json:"ignoreStatus"`

    // IsActive.
    //
    // 
    IsActive bool `json:"isActive"`

    // IsAnnouncement.
    //
    // 
    IsAnnouncement bool `json:"isAnnouncement"`

    // IsPinned.
    //
    // 
    IsPinned bool `json:"IsPinned"`

    // LastReplyTimestamp.
    //
    // 
    LastReplyTimestamp string `json:"lastReplyTimestamp"`

    // LatestReplyAuthorId.
    //
    // 
    LatestReplyAuthorId int64 `json:"latestReplyAuthorId"`

    // LatestReplyPostId.
    //
    // 
    LatestReplyPostId int64 `json:"latestReplyPostId"`

    // Locale.
    //
    // 
    Locale string `json:"locale"`

    // Popularity.
    //
    // 
    Popularity int32 `json:"popularity"`

    // Thumbnail.
    //
    // 
    Thumbnail string `json:"thumbnail"`

    // UrlMediaType.
    //
    // 
    UrlMediaType int32 `json:"urlMediaType"`

    // UserHasMutedPost.
    //
    // 
    UserHasMutedPost bool `json:"userHasMutedPost"`

    // UserHasRated.
    //
    // 
    UserHasRated bool `json:"userHasRated"`

    // UserRating.
    //
    // 
    UserRating int32 `json:"userRating"`
}
