// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_DestinyPresentationNodeTypeDefault represents the Default enum in the Destiny.DestinyPresentationNodeType component.
    Destiny_DestinyPresentationNodeTypeDefault int32 = 0

    // Destiny_DestinyPresentationNodeTypeCategory represents the Category enum in the Destiny.DestinyPresentationNodeType component.
    Destiny_DestinyPresentationNodeTypeCategory int32 = 1

    // Destiny_DestinyPresentationNodeTypeCollectibles represents the Collectibles enum in the Destiny.DestinyPresentationNodeType component.
    Destiny_DestinyPresentationNodeTypeCollectibles int32 = 2

    // Destiny_DestinyPresentationNodeTypeRecords represents the Records enum in the Destiny.DestinyPresentationNodeType component.
    Destiny_DestinyPresentationNodeTypeRecords int32 = 3

    // Destiny_DestinyPresentationNodeTypeMetric represents the Metric enum in the Destiny.DestinyPresentationNodeType component.
    Destiny_DestinyPresentationNodeTypeMetric int32 = 4

    // Destiny_DestinyPresentationNodeTypeCraftable represents the Craftable enum in the Destiny.DestinyPresentationNodeType component.
    Destiny_DestinyPresentationNodeTypeCraftable int32 = 5
)
