// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type SingleComponentResponseOfDestinyItemStatsComponent struct {
    // Disabled.
    //
    // If true, this component is disabled.
    Disabled bool `json:"disabled"`

    // Privacy.
    //
    // 
    Privacy int32 `json:"privacy"`

    // Data.
    //
    // If you want the stats on an item's instanced data, get this component.
    //
    // These are stats like Attack, Defense etc... and *not* historical stats.
    //
    // Note that some stats have additional computation in-game at runtime - for instance, Magazine Size - and thus these stats might not be 100% accurate compared to what you see in-game for some stats. I know, it sucks. I hate it too.
    Data Destiny_Entities_Items_DestinyItemStatsComponent `json:"data"`
}
