// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Components_Craftables_DestinyCraftableComponent struct {
    // FailedRequirementIndexes.
    //
    // If the requirements are not met for crafting this item, these will index into the list of failure strings.
    FailedRequirementIndexes []int32 `json:"failedRequirementIndexes"`

    // Sockets.
    //
    // Plug item state for the crafting sockets.
    Sockets []Destiny_Components_Craftables_DestinyCraftableSocketComponent `json:"sockets"`

    // Visible.
    //
    // 
    Visible bool `json:"visible"`
}
