// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Forum_ForumPostSortEnumDefault represents the Default enum in the Forum.ForumPostSortEnum component.
    Forum_ForumPostSortEnumDefault int32 = 0

    // Forum_ForumPostSortEnumOldestFirst represents the OldestFirst enum in the Forum.ForumPostSortEnum component.
    Forum_ForumPostSortEnumOldestFirst int32 = 1
)
