// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_HistoricalStats_DestinyHistoricalStatsValuePair struct {
    // DisplayValue.
    //
    // Localized formated version of the value.
    DisplayValue string `json:"displayValue"`

    // Value.
    //
    // Raw value of the statistic
    Value float64 `json:"value"`
}
