// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type User_UserSearchResponse struct {
    // Page.
    //
    // 
    Page int32 `json:"page"`

    // SearchResults.
    //
    // 
    SearchResults []User_UserSearchResponseDetail `json:"searchResults"`

    // HasMore.
    //
    // 
    HasMore bool `json:"hasMore"`
}
