// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_PlugAvailabilityModeNormal represents the Normal enum in the Destiny.PlugAvailabilityMode component.
    Destiny_PlugAvailabilityModeNormal int32 = 0

    // Destiny_PlugAvailabilityModeUnavailableIfSocketContainsMatchingPlugCategory represents the UnavailableIfSocketContainsMatchingPlugCategory enum in the Destiny.PlugAvailabilityMode component.
    Destiny_PlugAvailabilityModeUnavailableIfSocketContainsMatchingPlugCategory int32 = 1

    // Destiny_PlugAvailabilityModeAvailableIfSocketContainsMatchingPlugCategory represents the AvailableIfSocketContainsMatchingPlugCategory enum in the Destiny.PlugAvailabilityMode component.
    Destiny_PlugAvailabilityModeAvailableIfSocketContainsMatchingPlugCategory int32 = 2
)
