// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_DestinyItemSackBlockDefinition struct {
    // SelectItemCount.
    //
    // 
    SelectItemCount int32 `json:"selectItemCount"`

    // VendorSackType.
    //
    // 
    VendorSackType string `json:"vendorSackType"`

    // DetailAction.
    //
    // A description of what will happen when you open the sack. As far as I can tell, this is blank currently. Unknown whether it will eventually be populated with useful info.
    DetailAction string `json:"detailAction"`

    // OpenAction.
    //
    // The localized name of the action being performed when you open the sack.
    OpenAction string `json:"openAction"`

    // OpenOnAcquire.
    //
    // 
    OpenOnAcquire bool `json:"openOnAcquire"`
}
