// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_DestinyGameVersionsNone represents the None enum in the Destiny.DestinyGameVersions component.
    Destiny_DestinyGameVersionsNone int32 = 0

    // Destiny_DestinyGameVersionsDestiny2 represents the Destiny2 enum in the Destiny.DestinyGameVersions component.
    Destiny_DestinyGameVersionsDestiny2 int32 = 1

    // Destiny_DestinyGameVersionsDLC1 represents the DLC1 enum in the Destiny.DestinyGameVersions component.
    Destiny_DestinyGameVersionsDLC1 int32 = 2

    // Destiny_DestinyGameVersionsDLC2 represents the DLC2 enum in the Destiny.DestinyGameVersions component.
    Destiny_DestinyGameVersionsDLC2 int32 = 4

    // Destiny_DestinyGameVersionsForsaken represents the Forsaken enum in the Destiny.DestinyGameVersions component.
    Destiny_DestinyGameVersionsForsaken int32 = 8

    // Destiny_DestinyGameVersionsYearTwoAnnualPass represents the YearTwoAnnualPass enum in the Destiny.DestinyGameVersions component.
    Destiny_DestinyGameVersionsYearTwoAnnualPass int32 = 16

    // Destiny_DestinyGameVersionsShadowkeep represents the Shadowkeep enum in the Destiny.DestinyGameVersions component.
    Destiny_DestinyGameVersionsShadowkeep int32 = 32

    // Destiny_DestinyGameVersionsBeyondLight represents the BeyondLight enum in the Destiny.DestinyGameVersions component.
    Destiny_DestinyGameVersionsBeyondLight int32 = 64

    // Destiny_DestinyGameVersionsAnniversary30th represents the Anniversary30th enum in the Destiny.DestinyGameVersions component.
    Destiny_DestinyGameVersionsAnniversary30th int32 = 128

    // Destiny_DestinyGameVersionsTheWitchQueen represents the TheWitchQueen enum in the Destiny.DestinyGameVersions component.
    Destiny_DestinyGameVersionsTheWitchQueen int32 = 256

    // Destiny_DestinyGameVersionsLightfall represents the Lightfall enum in the Destiny.DestinyGameVersions component.
    Destiny_DestinyGameVersionsLightfall int32 = 512

    // Destiny_DestinyGameVersionsTheFinalShape represents the TheFinalShape enum in the Destiny.DestinyGameVersions component.
    Destiny_DestinyGameVersionsTheFinalShape int32 = 1024
)
