// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_Definitions_Milestones_DestinyMilestoneDisplayPreferenceMilestoneDefinition represents the MilestoneDefinition enum in the Destiny.Definitions.Milestones.DestinyMilestoneDisplayPreference component.
    //
    // Indicates you should show DestinyMilestoneDefinition.displayProperties for this Milestone.
    Destiny_Definitions_Milestones_DestinyMilestoneDisplayPreferenceMilestoneDefinition int32 = 0

    // Destiny_Definitions_Milestones_DestinyMilestoneDisplayPreferenceCurrentQuestSteps represents the CurrentQuestSteps enum in the Destiny.Definitions.Milestones.DestinyMilestoneDisplayPreference component.
    //
    // Indicates you should show the displayProperties for any currently active Quest Steps in DestinyMilestone.availableQuests.
    Destiny_Definitions_Milestones_DestinyMilestoneDisplayPreferenceCurrentQuestSteps int32 = 1

    // Destiny_Definitions_Milestones_DestinyMilestoneDisplayPreferenceCurrentActivityChallenges represents the CurrentActivityChallenges enum in the Destiny.Definitions.Milestones.DestinyMilestoneDisplayPreference component.
    //
    // Indicates you should show the displayProperties for any currently active Activities and their Challenges in DestinyMilestone.activities.
    Destiny_Definitions_Milestones_DestinyMilestoneDisplayPreferenceCurrentActivityChallenges int32 = 2
)
