// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_DestinyRecordStateNone represents the None enum in the Destiny.DestinyRecordState component.
    //
    // If there are no flags set, the record is in a state where it *could* be redeemed, but it has not been yet.
    Destiny_DestinyRecordStateNone int32 = 0

    // Destiny_DestinyRecordStateRecordRedeemed represents the RecordRedeemed enum in the Destiny.DestinyRecordState component.
    //
    // If this is set, the completed record has been redeemed.
    Destiny_DestinyRecordStateRecordRedeemed int32 = 1

    // Destiny_DestinyRecordStateRewardUnavailable represents the RewardUnavailable enum in the Destiny.DestinyRecordState component.
    //
    // If this is set, there's a reward available from this Record but it's unavailable for redemption.
    Destiny_DestinyRecordStateRewardUnavailable int32 = 2

    // Destiny_DestinyRecordStateObjectiveNotCompleted represents the ObjectiveNotCompleted enum in the Destiny.DestinyRecordState component.
    //
    // If this is set, the objective for this Record has not yet been completed.
    Destiny_DestinyRecordStateObjectiveNotCompleted int32 = 4

    // Destiny_DestinyRecordStateObscured represents the Obscured enum in the Destiny.DestinyRecordState component.
    //
    // If this is set, the game recommends that you replace the display text of this Record with DestinyRecordDefinition.stateInfo.obscuredDescription.
    Destiny_DestinyRecordStateObscured int32 = 8

    // Destiny_DestinyRecordStateInvisible represents the Invisible enum in the Destiny.DestinyRecordState component.
    //
    // If this is set, the game recommends that you not show this record. Do what you will with this recommendation.
    Destiny_DestinyRecordStateInvisible int32 = 16

    // Destiny_DestinyRecordStateEntitlementUnowned represents the EntitlementUnowned enum in the Destiny.DestinyRecordState component.
    //
    // If this is set, you can't complete this record because you lack some permission that's required to complete it.
    Destiny_DestinyRecordStateEntitlementUnowned int32 = 32

    // Destiny_DestinyRecordStateCanEquipTitle represents the CanEquipTitle enum in the Destiny.DestinyRecordState component.
    //
    // If this is set, the record has a title (check DestinyRecordDefinition for title info) and you can equip it.
    Destiny_DestinyRecordStateCanEquipTitle int32 = 64
)
