// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_Definitions_DestinyTalentNodeStepGuardianAttributesNone represents the None enum in the Destiny.Definitions.DestinyTalentNodeStepGuardianAttributes component.
    Destiny_Definitions_DestinyTalentNodeStepGuardianAttributesNone int32 = 0

    // Destiny_Definitions_DestinyTalentNodeStepGuardianAttributesStats represents the Stats enum in the Destiny.Definitions.DestinyTalentNodeStepGuardianAttributes component.
    Destiny_Definitions_DestinyTalentNodeStepGuardianAttributesStats int32 = 1

    // Destiny_Definitions_DestinyTalentNodeStepGuardianAttributesShields represents the Shields enum in the Destiny.Definitions.DestinyTalentNodeStepGuardianAttributes component.
    Destiny_Definitions_DestinyTalentNodeStepGuardianAttributesShields int32 = 2

    // Destiny_Definitions_DestinyTalentNodeStepGuardianAttributesHealth represents the Health enum in the Destiny.Definitions.DestinyTalentNodeStepGuardianAttributes component.
    Destiny_Definitions_DestinyTalentNodeStepGuardianAttributesHealth int32 = 4

    // Destiny_Definitions_DestinyTalentNodeStepGuardianAttributesRevive represents the Revive enum in the Destiny.Definitions.DestinyTalentNodeStepGuardianAttributes component.
    Destiny_Definitions_DestinyTalentNodeStepGuardianAttributesRevive int32 = 8

    // Destiny_Definitions_DestinyTalentNodeStepGuardianAttributesAimUnderFire represents the AimUnderFire enum in the Destiny.Definitions.DestinyTalentNodeStepGuardianAttributes component.
    Destiny_Definitions_DestinyTalentNodeStepGuardianAttributesAimUnderFire int32 = 16

    // Destiny_Definitions_DestinyTalentNodeStepGuardianAttributesRadar represents the Radar enum in the Destiny.Definitions.DestinyTalentNodeStepGuardianAttributes component.
    Destiny_Definitions_DestinyTalentNodeStepGuardianAttributesRadar int32 = 32

    // Destiny_Definitions_DestinyTalentNodeStepGuardianAttributesInvisibility represents the Invisibility enum in the Destiny.Definitions.DestinyTalentNodeStepGuardianAttributes component.
    Destiny_Definitions_DestinyTalentNodeStepGuardianAttributesInvisibility int32 = 64

    // Destiny_Definitions_DestinyTalentNodeStepGuardianAttributesReputations represents the Reputations enum in the Destiny.Definitions.DestinyTalentNodeStepGuardianAttributes component.
    Destiny_Definitions_DestinyTalentNodeStepGuardianAttributesReputations int32 = 128

    // Destiny_Definitions_DestinyTalentNodeStepGuardianAttributesAll represents the All enum in the Destiny.Definitions.DestinyTalentNodeStepGuardianAttributes component.
    Destiny_Definitions_DestinyTalentNodeStepGuardianAttributesAll int32 = 255
)
