// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_FireteamFinderLabelFieldTypeTitle represents the Title enum in the Destiny.FireteamFinderLabelFieldType component.
    Destiny_FireteamFinderLabelFieldTypeTitle int32 = 0

    // Destiny_FireteamFinderLabelFieldTypeLabel represents the Label enum in the Destiny.FireteamFinderLabelFieldType component.
    Destiny_FireteamFinderLabelFieldTypeLabel int32 = 1
)
