// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type SingleComponentResponseOfDestinyPresentationNodesComponent struct {
    // Privacy.
    //
    // 
    Privacy int32 `json:"privacy"`

    // Data.
    //
    // 
    Data Destiny_Components_Presentation_DestinyPresentationNodesComponent `json:"data"`

    // Disabled.
    //
    // If true, this component is disabled.
    Disabled bool `json:"disabled"`
}
