// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

const (
    // Destiny_DestinyVendorInteractionRewardSelectionNone represents the None enum in the Destiny.DestinyVendorInteractionRewardSelection component.
    Destiny_DestinyVendorInteractionRewardSelectionNone int32 = 0

    // Destiny_DestinyVendorInteractionRewardSelectionOne represents the One enum in the Destiny.DestinyVendorInteractionRewardSelection component.
    Destiny_DestinyVendorInteractionRewardSelectionOne int32 = 1

    // Destiny_DestinyVendorInteractionRewardSelectionAll represents the All enum in the Destiny.DestinyVendorInteractionRewardSelection component.
    Destiny_DestinyVendorInteractionRewardSelectionAll int32 = 2
)
