// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type User_EmailSettings struct {
    // OptInDefinitions.
    //
    // Keyed by the name identifier of the opt-in definition.
    OptInDefinitions any `json:"optInDefinitions"`

    // SubscriptionDefinitions.
    //
    // Keyed by the name identifier of the Subscription definition.
    SubscriptionDefinitions any `json:"subscriptionDefinitions"`

    // Views.
    //
    // Keyed by the name identifier of the View definition.
    Views any `json:"views"`
}
