// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type FireteamFinder_DestinyFireteamFinderApplyToListingResponse struct {
    // Listing.
    //
    // 
    Listing any `json:"listing"`

    // Application.
    //
    // 
    Application any `json:"application"`

    // IsApplied.
    //
    // 
    IsApplied bool `json:"isApplied"`
}
