// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type GroupsV2_GroupBan struct {
    // GroupId.
    //
    // 
    GroupId int64 `json:"groupId"`

    // LastModifiedBy.
    //
    // This contract supplies basic information commonly used to display a minimal amount of information about a user. Take care to not add more properties here unless the property applies in all (or at least the majority) of the situations where UserInfoCard is used. Avoid adding game specific or platform specific details here. In cases where UserInfoCard is a subset of the data needed in a contract, use UserInfoCard as a property of other contracts.
    LastModifiedBy any `json:"lastModifiedBy"`

    // BungieNetUserInfo.
    //
    // This contract supplies basic information commonly used to display a minimal amount of information about a user. Take care to not add more properties here unless the property applies in all (or at least the majority) of the situations where UserInfoCard is used. Avoid adding game specific or platform specific details here. In cases where UserInfoCard is a subset of the data needed in a contract, use UserInfoCard as a property of other contracts.
    BungieNetUserInfo any `json:"bungieNetUserInfo"`

    // Comment.
    //
    // 
    Comment string `json:"comment"`

    // CreatedBy.
    //
    // This contract supplies basic information commonly used to display a minimal amount of information about a user. Take care to not add more properties here unless the property applies in all (or at least the majority) of the situations where UserInfoCard is used. Avoid adding game specific or platform specific details here. In cases where UserInfoCard is a subset of the data needed in a contract, use UserInfoCard as a property of other contracts.
    CreatedBy any `json:"createdBy"`

    // DateBanned.
    //
    // 
    DateBanned string `json:"dateBanned"`

    // DateExpires.
    //
    // 
    DateExpires string `json:"dateExpires"`

    // DestinyUserInfo.
    //
    // 
    DestinyUserInfo any `json:"destinyUserInfo"`
}
