// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_DestinyActivityModifierReferenceDefinition struct {
    // ActivityModifierHash.
    //
    // The hash identifier for the DestinyActivityModifierDefinition referenced by this activity.
    ActivityModifierHash uint32 `json:"activityModifierHash"`
}
