// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_Records_SchemaRecordStateBlock struct {
    // ObscuredDescription.
    //
    // A display description override to show when this record is 'obscured' instead of the default obscured display description.
    ObscuredDescription string `json:"obscuredDescription"`

    // ObscuredName.
    //
    // A display name override to show when this record is 'obscured' instead of the default obscured display name.
    ObscuredName string `json:"obscuredName"`

    // FeaturedPriority.
    //
    // 
    FeaturedPriority int32 `json:"featuredPriority"`
}
