// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_HistoricalStats_DestinyClanAggregateStat struct {
    // Value.
    //
    // Value of the stat for this player
    Value any `json:"value"`

    // Mode.
    //
    // The id of the mode of stats (allPvp, allPvE, etc)
    Mode int32 `json:"mode"`

    // StatId.
    //
    // The id of the stat
    StatId string `json:"statId"`
}
