// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_Animations_DestinyAnimationReference struct {
    // AnimIdentifier.
    //
    // 
    AnimIdentifier string `json:"animIdentifier"`

    // AnimName.
    //
    // 
    AnimName string `json:"animName"`

    // Path.
    //
    // 
    Path string `json:"path"`
}
