// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Content_CommentSummary struct {
    // CommentCount.
    //
    // 
    CommentCount int32 `json:"commentCount"`

    // TopicId.
    //
    // 
    TopicId int64 `json:"topicId"`
}
