// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Config_UserTheme struct {
    // UserThemeName.
    //
    // 
    UserThemeName string `json:"userThemeName"`

    // UserThemeDescription.
    //
    // 
    UserThemeDescription string `json:"userThemeDescription"`

    // UserThemeId.
    //
    // 
    UserThemeId int32 `json:"userThemeId"`
}
