// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type DestinyItemComponentSetOfint32 struct {
    // RenderData.
    //
    // 
    RenderData DictionaryComponentResponseOfint32AndDestinyItemRenderComponent `json:"renderData"`

    // ReusablePlugs.
    //
    // 
    ReusablePlugs DictionaryComponentResponseOfint32AndDestinyItemReusablePlugsComponent `json:"reusablePlugs"`

    // Sockets.
    //
    // 
    Sockets DictionaryComponentResponseOfint32AndDestinyItemSocketsComponent `json:"sockets"`

    // Objectives.
    //
    // 
    Objectives DictionaryComponentResponseOfint32AndDestinyItemObjectivesComponent `json:"objectives"`

    // TalentGrids.
    //
    // 
    TalentGrids DictionaryComponentResponseOfint32AndDestinyItemTalentGridComponent `json:"talentGrids"`

    // Instances.
    //
    // 
    Instances DictionaryComponentResponseOfint32AndDestinyItemInstanceComponent `json:"instances"`

    // PlugObjectives.
    //
    // 
    PlugObjectives DictionaryComponentResponseOfint32AndDestinyItemPlugObjectivesComponent `json:"plugObjectives"`

    // Perks.
    //
    // 
    Perks DictionaryComponentResponseOfint32AndDestinyItemPerksComponent `json:"perks"`

    // PlugStates.
    //
    // 
    PlugStates DictionaryComponentResponseOfuint32AndDestinyItemPlugComponent `json:"plugStates"`

    // Stats.
    //
    // 
    Stats DictionaryComponentResponseOfint32AndDestinyItemStatsComponent `json:"stats"`
}
