// This file was generated by https://github.com/taiidani/go-bungie-api/generate.
// DO NOT EDIT THIS FILE.
package api

type Destiny_Definitions_Presentation_DestinyPresentationNodeRequirementsBlock struct {
    // EntitlementUnavailableMessage.
    //
    // If this node is not accessible due to Entitlements (for instance, you don't own the required game expansion), this is the message to show.
    EntitlementUnavailableMessage string `json:"entitlementUnavailableMessage"`
}
